<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc. To
 * learn more:
 * http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

$keyword = false;
$defaultText = $this->partial()->view->defaultKeyword;
if ($this->partial()->view->params['keyword']) {
    $keyword = $this->partial()->view->params['keyword'];
}

$form = new Application_Form_KeywordSearch( array('keyword' => $keyword, 'defaultKeyword' => $defaultText));

// take advantage of the model interface that modified the default text
if (!empty($form->_defaultKeyword)) 
{
    $defaultText = $form->_defaultKeyword;
}

$urlParams = array();
if ($this->partial()->view->urlParams) 
{
    $urlParams = $this->partial()->view->urlParams;
}

$form->setAction($this->MergeUrl($urlParams + array('keyword' => null)));
if ($this->partial()->view->urlParams) 
{
    $form->setAction($this->MergeUrl($urlParams + array('keyword' => null), 'default'));
}
$form->setAttrib('id', 'search_within');
$form->setAttrib('ajax', '1');
?>

<?php if (isset($this->showAdditionalSearches) && $this->showAdditionalSearches): ?>
    <?php echo $this->partial('partials/modifyGallerySearch.phtml', array('form' => $form, 'formId' => 'search_within')); ?>
<?php endif; ?>
<?php // print the search form ?>
<div class="gallery_filter_bar" id="default_gallery_filter_bar">
    <?php echo $form->render(); ?>

    <?php
    if (!isset($this->disableType) || $this->disableType == false):
    ?>
        <div id="ktype">
		<span><?php echo $this->translate('View'); ?>:</span>
    <?php
        $currentType = $this->currentType;
		$filterTypes = $this->filterTypes;
        $optionsArray = array();
        foreach ($filterTypes as $type => $typeString)
        {
            $optionsArray[$this->MergeUrl(array('type' => $type,'sort' => null))] = $typeString;
        }
        
        $select = new Zend_Form_Element_Select('show_type', 
						array(	'multiOptions' => $optionsArray,
							  	'onchange' => 'document.location.href = $(this).val()',
								'value' => $this->MergeUrl(array('type' => $currentType,'sort' => null))));
        
        $select->setDecorators(array('ViewHelper'));
        echo $select;
        ?>

        </div>
	<?php endif; ?>
<?php /* Javascript for the live Search functionality */ ?>
    <script>
	var defaultKeyword = "<?php echo addcslashes($defaultText, '\"'); ?>";
	var searchTimeout;
	var searchVal = $('#search_within_text').val();
	$('#search_within_text').keyup(function(){
	    if($(this).val() == '' || $(this).val() == defaultKeyword) {
		$('#reset_search_within').hide();
		$("#search_within_text").removeClass("keyword");
	    }
	    else {
		$('#reset_search_within').show();
		$("#search_within_text").addClass("keyword");
	    }
        
	    if(searchVal != $(this).val()) {
		searchVal = $(this).val();
		clearTimeout(searchTimeout);
		searchTimeout=setTimeout(function(){
		    $("#search_within").submit();
		}, 800);
	    }
	});
    </script>
<?php
/* end livesearch */
if (isset($this->links) && count($this->links))
:
    ?>
        <div id="links">
	<?php echo $this->translate('View:'); ?>
	    <?php
    foreach ($this->links as $link => $label)
    {
        echo '<a href="' . $this->MergeUrl(
                array('type' => $link)) . '" class="' .
                 $label['class'] . '">' . $label['label'] . '</a>';
    }
    ?>
        </div>
<?php
	endif;
if (isset($this->sorters) && count($this->sorters)):
    ?>
        <div id="sorter">
	<?php echo $this->translate('by'); ?>:
	    <?php
    $currentSorter = $this->partial()->view->params['sort'];
    
    $i = 0;
    foreach ($this->sorters as $sorter => $label)
    {
        $class = '';
        if ($i == count($this->sorters) - 1)
        {
            $class = ' last';
        }
        if ($currentSorter == $sorter)
        {
            echo '<span class="' . $class . '">' . $label . '</span>';
        } else
        {
            echo '<a href="' . $this->MergeUrl(array('sort' => $sorter)) . '" class="' . $class .
            '">' . $label . '</a>';
        }
        $i ++;
    }
    
    ?>
        </div>
	<?php endif; ?>

</div>

<?php // render the additional galery search bars ?>
	<?php if (isset($this->showAdditionalSearches) && $this->showAdditionalSearches): ?>
	    <?php echo $this->partial('partials/additionalGallerySearches.phtml'); ?>
	<?php endif; ?>    

<?php 

