<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

    $defaultText = $this->translate('Search all media'); 
    $keyword = false;
    $search_from_type = '';
    if($this->partial()->view->searchKeyword)
    {
        $keyword = $this->String()->htmlEntities(trim($this->partial()->view->searchKeyword));
	$search_from_type = 'wide';
    }
?>
<form id="main_search" class="<?php echo $search_from_type;?>" action="<?php echo $this->baseUrl('/search/')?>" onsubmit="$('#do_main_search').click(); return false;">
    <?php
        echo $this->formText(
            'search_for',
            $keyword ? $keyword : $defaultText,
            array(
                'onfocus' => $keyword ? '' : 'if($(this).val() == "'.$defaultText.'") {$(this).val("");}',
                'onblur' => $keyword ? '' : 'if($(this).val() == "") { $(this).val("'.$defaultText.'");}',
                'id' => 'search_for'
            )
                
        );
        echo $this->formButton(
            'do_main_search',
            $this->translate('Search'),
            array(
                'type' => 'submit',
                'onclick' => 'if($("#search_for").val() != "'.$defaultText.'"){document.location.href = $("#main_search").attr("action") + encodeURIComponent($("#search_for").val());}',
                'id' => 'do_main_search',
                'value' => $this->translate('Search')
            )
        );
        if($keyword)
        {
            echo $this->formButton(
                'cancel_main_search',
                $this->translate('Search'),
                array(
                    'type' => 'button',
                    'onclick' => 'document.location.href = \''.$this->baseUrl('/').'\'',
                    'id' => 'cancel_main_search',
                    'class' => 'reset',
                    'value' => $this->translate('Reset'),
                )
            );
        }
    ?>
    <button type="button" class="reset hidden" id="cancel_main_search"><?php echo $this->translate('Reset');?></button>
</form>