<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

// disable for IE7
if($this->partial()->view->Device() != 'ie7'):
?>
<a 
    id="hide_box" 
    href="#" 
    class="" 
    onclick="$(this).toggleClass('show');$('#uploadbox<?php echo $this->id ?>').toggleClass('mini', 'normal');/*$('#uploadbox<?php echo $this->id ?> > #entry_details').slideToggle();*/$('#uploadbox<?php echo $this->id ?> .showhide').text( $('#uploadbox<?php echo $this->id ?> .showhide').text() == '<?php echo $this->translate('Hide');?>' ? '<?php echo $this->translate('Show');?>' : '<?php echo $this->translate('Hide');?>');return false;"
>
    <span class="showhide"><?php echo $this->translate('Hide');?></span>
    <em></em>
</a>
<?php
endif; 
