<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

$navigation = $this->navigation();
$pages = $this->container->getPages();
?>
<ul class="navigation limiter">
    <?php
    $activePageRendered = false;
    foreach ($pages as $page):
        if($page->get('showInMenu') !== false):
            $liClass = '';
            if (!$activePageRendered) {
	            if (get_class($page) == 'Zend_Navigation_Page_Uri' ) {
	                $front = Zend_Controller_Front::getInstance();
	                $requestUri = urldecode($front->getRequest()->getRequestUri());
	                
	                if ($requestUri == $page->getUri() || $page->isActive(true)) {
	                    $activePageRendered = true;
	                    $liClass = 'class="active"';
	                }
	            } 
	            elseif ($page->isActive(true)) {
	                $activePageRendered = true;
	                $liClass = 'class="active"';
	            } 
            }
            ?>
            <li <?php echo $liClass; ?> >
                <?php echo $navigation->menu()->htmlify($page); ?>
            </li>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>
<?php

   