<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/
/**
 * entry galleries, channels and tags section under the player in details tab
 */

	$catsOut = ''; //<ul> html output
	$entryCats = $this->String()->formatCategories($this->partial()->view->categories); //all categories for this entry
			
	//iterating thru category trees, each tree is an array of cats
	foreach($entryCats as $k => $entryCat) 
	{
		//if this is not the last category tree this will hold the seperator string
		$withDash = $k == count($entryCats) - 1 ? '' : '&nbsp;,&nbsp;'; 
		$ecatUrl = '';
		$n = 0;
		foreach($entryCat as $key => $ecat) //iterating thru categories of current tree
		{
			// if this is not the last category in the current tree will hold the seperator string
			$_withDash = ++$n == count($entryCat) ? '' : '&nbsp&gt;&nbsp;'; 
			$ecatUrl .= $ecatUrl == '' ? $ecat : '>' . $ecat;
			//fetching the anchor for the category
			$catsOut .= '<span><a href="'.$this->baseUrl('category/'.urlencode(Kms_View_Helper_String::removeSpecialChars($ecatUrl))."/".$key).'">' 
					. $this->escape(preg_replace("/^\d+_/", '', $ecat)) 
					. '</a>' . $_withDash . '</span>' ; 
		}
		$catsOut .= '<span>' . $withDash . '</span>';
	} 
	
	if($catsOut != ''):
?>
<div class="parents wrapper" id="entry_categories">    
	<div class="title"><?php echo $this->translate('Categories'); ?>:</div>
	<div class="parent_items">
		<?php echo $catsOut ?>
	</div>
</div>

<?php 
	endif;
?>                    
            
<?php
	$channelsOut = ''; //<ul> html output
	$entryChannels = $this->String()->formatChannels($this->partial()->view->categories); //all categories for this entry
			
	//iterating thru category trees, each tree is an array of cats
	foreach($entryChannels as $k => $entryChannel) 
	{
		//if this is not the last category tree this will hold the seperator string
		$withDash = $k == count($entryChannels) - 1 ? '' : '&nbsp;,&nbsp;'; 
		$echanUrl = '';
		$n = 0;
		foreach($entryChannel as $key => $echan) //iterating thru categories of current tree
		{
			// if this is not the last category in the current tree will hold the seperator string
			$_withDash = ++$n == count($entryChannel) ? '' : '&nbsp&gt;&nbsp;'; 
			$echanUrl .= $echanUrl == '' ? $echan : '>' . $echan;
			//fetching the anchor for the category
			$channelsOut .= '<span><a href="'.$this->baseUrl('channel/'.urlencode(Kms_View_Helper_String::removeSpecialChars($echanUrl))."/".$key).'">' 
					. $this->escape(preg_replace("/^\d+_/", '', $echan)) 
					. '</a>' . $_withDash . '</span>' ; 
		}
		$channelsOut .= '<span>' . $withDash . '</span>';
	} 
	
	if($channelsOut != ''):
?>
<div class="parents wrapper" id="entry_categories">
	<div class="title"><?php echo $this->translate('Channels'); ?>:</div>
	<div class="parent_items">
		<?php echo $channelsOut ?>
	</div>
</div>
<?php 
	endif;
?>                    
            
<?php
	$tagsOut = '';
	if($this->tags) {
		$entryTags = array_slice(explode(", ", $this->tags), 0, 20);
		foreach($entryTags as $entryTag) {
			if(strpos($entryTag, "displayname_") === false) {
				$tagsOut .= '<li><a href="' .$this->baseUrl('/tag/'. $this->escape($entryTag)) . '">' . $this->escape($entryTag) . '</a></li>';
			}
		}
	}
	
	if($tagsOut != ''):
?>
<div class="parents wrapper" id="tags">
	<div class="title"><?php echo $this->translate('Tags');?>:</div>
	<div class="parent_items">
		<ul id="entry_tags">
			<?php echo $tagsOut; ?>
		</ul>
	</div>
</div>
<?php             
	endif;
?>