<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/
/**
 * This view renders the tabs for the Player Block Template (tabs below the player)
 *
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_PLAYERTABS
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_PLAYERTABLINKS
 */

?>
<ul id="player_tab_buttons">
    <li><a data-tab="#details_tab"><?php echo $this->translate('Details');?></a></li>
    <?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_PLAYERTABLINKS); ?>
</ul>
<?php echo $this->partial('partials/playerBlockDetails.phtml', $this); ?>
<?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_PLAYERTABS); ?>

<script>
    $('#player_tabs > div').hide();

    $('#player_tabs > div:first').show();
    $('#player_tabs > ul li:first').addClass('current');

    $('#player_tabs > ul li > a').click(function() {
        $('#player_tabs > ul li').removeClass('current');
        $(this).parent().addClass('current');
        var currentTab = $(this).attr('data-tab');
        $('#player_tabs > div').hide();
        $(currentTab).show();
        var onShow = $(currentTab).attr('onshow');
        if(onShow) {
            eval(onShow);
        }
        
        //return false;
    });
</script>
