<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/
/**
 * Partial view template for rendering the side tabs to the right of the player
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_PLAYERSIDETABLINKS
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_PLAYERSIDETABS
 */
?>
<strong><?php echo $this->translate('Show me');?>:</strong> &nbsp;
<select id="sidetabsselect">
        <?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_PLAYERSIDETABLINKS); ?>
</select>
<?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_PLAYERSIDETABS); ?>

<script>
    $('#playersidebar > ul').hide();
    if($('option','#sidetabsselect').length > 0) {
        $('#playersidebar > ul').hide();

        $('#playersidebar > ul:first').show();

        $('#playersidebar select#sidetabsselect').change(function() {
            var currentTab = $(this).val();
            $('#playersidebar > ul').hide();
            $('#playersidebar '+currentTab).show();
            var onShow = $(currentTab).attr('onshow');
            if(onShow) {
                eval(onShow);
            }
            return false;
        });
    }
</script>