<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

/**
 * Player block template
 * 
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_PLAYERSIDETABLINKS
 */

// see if any modules are using the sidetabs viewhook and change layout accordingly
$enablePlayerBlockSide = count(Kms_Resource_Viewhook::getModulesRegisteredForViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_PLAYERSIDETABLINKS));
// add a widelayout class to player_block
$titleTag = isset($this->partial()->view->titleTag) ? $this->partial()->view->titleTag : 'h2';
?>
<div class="wrapper" id="player_wrap">
    <div class="wrapper entry_heading">
	<div class="views">
            <?php if(!$this->partial()->view->presentationView): // dont show views for video presentations ?>
                <?php echo number_format($this->views); ?><span>&nbsp;<?php echo $this->translate('views'); ?></span>
            <?php endif;?>
        </div>
    <<?php echo $titleTag;?> id="ktitle"><?php echo $this->escape($this->name) ?></<?php echo $titleTag;?>>
</div>
    <div id="player">
	<?php
	if ($this->partial()->view->converting) :
	    ?>
    	<script>
    	    // script for checking if the entry is converted or not, every 15 seconds
    	    var checkStatusInterval = setInterval(  function() {
    		$.getJSON("<?php echo $this->baseUrl('/entry/check-status/id/' . $this->id . '?format=ajax'); ?>", asyncCallback).error( transportError );
    	    }, 30 * 1000);
    	</script>
    	<div class="noplayer_converting"><h3><?php echo $this->translate('Media is being processed'); ?>  (: !</h3></div>

	    <?php
	else:
	    if ($this->partial()->view->presentationView) {
		echo $this->partial('partials/widgets/kpw.phtml', array('entryId' => $this->id));
	    } else {
		echo $this->partial('partials/widgets/kdp.phtml', array('entryId' => $this->id));
	    }
	endif;
	?>
    </div>
</div>
<?php
