<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/
/**
 * The details tab of the player block (below the player
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_POSTENTRYDETAILS
 */

?>
<div id="details_tab">
    <?php 
    /* uncomment this for flash-messages within entry details (for ajax editing)
    if(isset($this->partial()->view->messages)) :
    ?>
    <div id="entry-messages">
        <?php
        foreach($this->partial()->view->messages as $message):
        ?>
        <div class="ui-state-error ui-corner-all">
            <p class="ui-icon ui-icon-info"></p><p class="flash-message"><?php echo $message ?></p>
        </div>
        <?php
        endforeach;
        ?>
    </div>
    <script>
        setTimeout('$("#entry-messages").fadeOut()', 3000);
    </script>
    <?php
        endif;*/
    ?>
    <div id="entry_details">
        <?php if($this->partial()->view->isEntryOwner) : ?>
        <div class="tabActionLinks">
            <a id="show_edit_details" href="<?php echo $this->baseUrl('/edit/'.$this->id) . ($this->partial()->view->showPlayer ? '' : '/noplayer/1') . ($this->partial()->view->entryAsyncMode ? '/async/1' : '') ?>"><em></em><?php echo $this->translate('Edit');?></a>
            <a id="delete_entry" href="<?php echo $this->baseUrl('/entry/delete/id/'.$this->id)?>" rel="dialog"><em></em><?php echo $this->translate('Delete');?></a>
        </div>
        <?php endif; ?>
        <?php if($this->partial()->view->pending || $this->partial()->view->converting) : ?>
        <div id="status_notice" class="notice"><?php
             if($this->partial()->view->converting) : 
                ?><span id="converting_media"><?php echo $this->translate('This media is still being converted');?>.&nbsp;</span><?php
             endif; 
            ?><?php 
            if($this->partial()->view->pending) : 
                ?><span id="pending_moderation"><?php echo $this->translate('This media is pending review');?>.&nbsp;</span><?php
             endif; 
        ?></div>
        <?php endif;?>
        <div id="kdescription"><?php echo trim($this->description) ? $this->escape($this->description) : $this->translate('No description provided') ?></div>

        
        <?php echo $this->partial('partials/playerBlockCategories.phtml', $this) ?>
       
        <?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_POSTENTRYDETAILS); ?>
    </div><!-- #entry_details -->
</div>
