<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

/**
 * render the player block for an entry of an unknown type.
 */

// see if any modules are using the sidetabs viewhook and change layout accordingly
$enablePlayerBlockSide = count(Kms_Resource_Viewhook::getModulesRegisteredForViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_PLAYERSIDETABLINKS));
// add a widelayout class to player_block
$titleTag = isset($this->partial()->view->titleTag) ? $this->partial()->view->titleTag : 'h2';
?>
<div class="wrapper unknown" id="player_wrap">
    <div class="wrapper entry_heading">
		<div class="views">
			<?php echo number_format($this->views); ?><span>&nbsp;<?php echo $this->translate('views'); ?></span>
		</div>
	    <<?php echo $titleTag;?> id="ktitle"><?php echo $this->escape($this->name) ?></<?php echo $titleTag;?>>
	</div>
	<?php if (!empty($this->thumbnailUrl)) :?>
    <div id="player">
		<img class="tmb" src="<?php echo $this->thumbnailUrl; ?>/width/670/height/400/type/<?php echo Kaltura_Client_Enum_ThumbCropType::CROP;?>" width="670" height="400" alt="<?php echo $this->escape($this->name); ?>" />
    </div>
	<?php endif; ?>
</div>

<?php 