<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/


    $onchange = '$("#embedForm").attr("action", this.value)';
    if(!$this->enableCustomization)
    {
        $onchange = '$("#kdp_embed_options").toggle();'.$onchange;
    }
?>
<div>
    <p><?php echo $this->translate('Select Embed Type');?>:</p>
    <?php
        echo $this->FormRadio(
                'embed_type',
                $this->baseUrl('embed/index/embed'),
                array(
                    'onchange' => $onchange,
                ),
                array(
                    $this->baseUrl('embed/index/embed') => ' HTML', 
                    $this->baseUrl('oembed/index/oembed') => ' oEmbed',
                ),
                '&nbsp;&nbsp;&nbsp;'
        );
    ?>
</div>
