<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

$this->JsonContent(array(
        'target' => '#embed_code',
        'content' => $this->oembedLink,
        'action' => 'value'
    )
);

$this->placeholder('script')->captureStart('SET', 'script');
?>
$('#embed_code').select();
$('#copy_notice').show(); 
setTimeout(function(){ 
    $('#copy_notice').fadeOut(500)
},1000);
<?php
if($this->enableCustomization):
?>
$('#embed_sizes > label').removeClass('selected');
$('#embed_sizes input[value=<?php echo $this->size; ?>]').attr('checked', 'checked').closest('label').addClass('selected');
<?php
endif;

$this->placeholder('script')->captureEnd();
$this->JsonScript($this->placeholder('script')->script);