<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

if(isset($this->label) && $this->label):
?>
<li <?php echo $this->class != '' ? 'class="active"' : ''; ?> >
    <a href="<?php echo $this->url ?>" <?php echo $this->target ? 'target='.$this->target : '' ?> >
        <?php echo $this->escape($this->label);?>
    </a>
</li>
<?php endif;
