<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

?>
<li class="kmenu"><a ><?php echo $this->label ?><em></em></a><ul>
    <?php
    if(isset($this->items) && count($this->items)):
        foreach ($this->items as $submenuitem):
        ?>
            <li><a href="<?php echo $submenuitem->link ?>" target="_blank"><?php echo $this->escape($submenuitem->label); ?></a></li>
        <?php
        endforeach;
    endif;
    ?>
</ul></li>
