<?php if ($this->renderTags) : 
// url of entry page in KMS 
$entry_url = $this->serverUrl() . $this->EntryLink($this->entry->id, $this->entry->name);
// strip http[s]
$entry_url_no_http = preg_replace('#http[s]?://#', '', $entry_url);
// entry thumbnail no http[s]
$thumb_url = preg_replace('#http[s]?://#', '', $this->entry->thumbnailUrl) . "/width/" . $this->uiconf->width;
?>
<!-- BEGIN FACEBOOK OPEN GRAPH TAGS -->
<meta property="og:type" content="video.other" />
<meta property="og:site_name" content="<?php echo $this->site_name ?>" />
<meta property="og:title" content="<?php echo strip_tags($this->entry->name) ?>" />
<meta property="og:description" content="<?php echo strip_tags($this->entry->description) ?>" />
<meta property="og:url" content="<?php echo $entry_url ?>" />
<meta property="og:image" content="http://<?php echo $thumb_url ?>" />
<meta property="og:image:secure_url" content="https://<?php echo $thumb_url ?>" />
<?php if ($this->renderVideoTags) : ?>
<meta property="og:video" content="http://<?php echo $this->service_url ?>/index.php/kwidget/wid/_<?php echo $this->entry->partnerId; ?>/uiconf_id/<?php echo $this->uiConfId; ?>/entry_id/<?php echo $this->entry->id; ?>" />
<meta property="og:video:secure_url" content="https://<?php echo $this->service_url ?>/index.php/kwidget/wid/_<?php echo $this->entry->partnerId; ?>/uiconf_id/<?php echo $this->uiConfId; ?>/entry_id/<?php echo $this->entry->id; ?>" />
<meta property="og:video:width" content="<?php echo $this->uiconf->width ?>" />
<meta property="og:video:height" content="<?php echo $this->uiconf->height ?>" />
<meta property="og:video:type" content="application/x-shockwave-flash" />
<?php 	if ($this->flavor_url) : ?>
<meta property="og:video" content="http://<?php echo $this->service_url . $this->flavor_url ?>" />
<meta property="og:video:secure_url" content="https://<?php echo $this->service_url . $this->flavor_url ?>" />
<meta property="og:video:width" content="<?php echo $this->uiconf->width ?>" />
<meta property="og:video:height" content="<?php echo $this->uiconf->height ?>" />
<meta property="og:video:type" content="video/mp4" />
<?php 	endif; ?>
<?php endif; ?>
<?php if ($this->renderTextTags) : ?>
<meta property="og:video" content="http://<?php echo $entry_url_no_http ?>" />
<meta property="og:video:secure_url" content="https://<?php echo $entry_url_no_http ?>" />
<meta property="og:video:width" content="<?php echo $this->uiconf->width ?>" />
<meta property="og:video:height" content="<?php echo $this->uiconf->height ?>" />
<meta property="og:video:type" content="text/html" />
<?php endif; ?>
<!-- END FACEBOOK OPEN GRAPH TAGS -->
<?php endif; ?>