<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/
/**
 * @ignore
 */
$ks = Kms_Resource_Client::getAdminClient()->getKs();

?>
<div id="view-content">
    <p class="donesuccess"><?php echo $this->translate('KMS') . $this->MajorVersion() . ' ' . $this->translate('was setup successfully');?>.</p>
    <p><?php echo $this->translate('You can visit your Kaltura MediaSpace site');?>: <a href="<?php echo $this->baseUrl('/'); ?>"><?php echo $this->translate('here');?></a>.</p>
    <p><?php echo $this->translate('You can create new users for your Kaltura MediaSpace site');?>: <a href="<?php echo $this->baseUrl('admin/user-list?ks='.$ks); ?>"><?php echo $this->translate('here');?></a>.</p>
    <p><?php echo $this->translate('You can go to the administration area to set more configuration options');?>: <a href="<?php echo $this->baseUrl('admin/config?ks='.$ks); ?>"><?php echo $this->translate('here');?></a>.</p>
    <p><?php echo $this->translate('Note that some functionality might be limited or broken until you complete all of the required configurations');?>.</p>
<!--    <p><?php echo $this->translate('To run the UnitTests please click ');?> <a href="<?php echo $this->baseUrl('admin/unit-tests');?>" target="_blank"><?php echo $this->translate('here');?></a>.</p>-->

</div>
<?php if(isset($this->deploymentErrors)):?>
<div id="deployment-errors">
<?php foreach($this->deploymentErrors as $error): ?>
    <div><?php echo $error; ?></div>
<?php endforeach; ?>
    <?php endif;?>
</div>