<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/
/**
 * @ignore
 */

?>
<br /><br />
<div id="view-content">
    <?php echo $this->error; ?>
    <h3 style="font-weight: bold;"><?php echo $this->translate('Please fill all the fields!')?></h3>
    <?php echo $this->form; ?>
</div>
<div class="loader">
    <div class="loader_message"><?php echo $this->translate('Installation in progress. Please wait...');?></div>
</div>

<script type="text/javascript">
    
    $('form').submit(function(){
	$('.loader').fadeIn('slow');
    });

</script>