<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
?>
<ul id="channel_topics">
<?php
// the All Topics item
// a bit ugly, but works with no deafult value in routes.ini, and does not need excessive work with routes
$topicsArray['All'] = array('topic' => $this->translate('All'),'link' => $this->url(array('topic'=>null)), 'active' =>true);

// all the topics
foreach($this->topics as $topic)
{
    $topicsArray[$topic] = array('topic' => $topic, 'link' => $this->url(array('topic' => $topic)),'active' =>false);
}

// set the active topic
if ($this->currentTopic)
{
    // only set if it exists - to avoid adding an empty topic
    if (isset($topicsArray[$this->currentTopic])){
        $topicsArray[$this->currentTopic]['active'] = true;
    }
    $topicsArray['All']['active'] = false;
}

echo $this->partialLoop('partials/topicLine.phtml', 'channeltopics', $topicsArray);
?>
</ul>
<?php 
