<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

?>
<div id="bulk_actions" class="wrapper">
    <div class="operate fleft">
        <?php echo $this->formCheckbox(
                    'checkall',
                    null,
                    array('title' => $this->translate('All'))
                );
        ?>
    </div>
    <div class="fright">
        
        <div class="views_switch fright">
            <a class="short_view" href="<?php echo $this->MergeUrl(array('view' => 'short', 'page' => '1'));?>" rel="async"></a>
            <a class="full_view" href="<?php echo $this->MergeUrl(array('view' => 'full', 'page' => '1'));?>" rel="async"></a>
        </div>
	<button type="submit" class="delete"><?php echo $this->translate('Delete');?></button>
        <?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_MYMEDIABULK); ?>
        
    </div>
</div>
<script>
$('#mm_wrap #bulk_actions input#checkall').click(function(){
    if($(this).attr("checked") || $(this).is("[CHECKED]")) {
        $("#mymedia #kitems label.operate .sel-entry").attr("checked", "checked");
        $("#mymedia #kitems li").addClass('selected');
    } 
    else {
        $("#mymedia #kitems label.operate .sel-entry").removeAttr("checked");
        $("#mymedia #kitems li").removeClass('selected');
    }    
});  

$('#mymedia #kitems .operate input.sel-entry').live('click', function(){
   if($(this).attr("checked") || $(this).is("[CHECKED]")) {
       $("#mymedia #kitems li[data-entryid="+$(this).val()+"]").addClass("selected");
   } 
   else {
       $("#mymedia #kitems li[data-entryid="+$(this).val()+"]").removeClass("selected");
   }
});

var redirUrl = "<?php echo urlencode($this->MergeUrl());?>";
$("#mm_wrap #bulk_actions button.delete").click(function(){
    var $items = $("#mymedia #kitems label.operate .sel-entry");
    var items = new Array();
    $.each($items, function(index, elem){
        if(($(elem).attr('checked')  || $(elem).is("[CHECKED]")) && $(elem).val()) {
            items.push($(elem).val());
        }
    })
    if(items.length) {
        var entryIds = items.join(',');
        var url = baseUrl + '/entry/delete/id/' + entryIds + '?format=dialog&redir=' + redirUrl;

        $.getScript(url, scriptCallback).error( transportError );
    }
});
</script>
