<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

    if(isset($this->entry->id) && !isset($this->entry->mediaType))
    {
        // this is a video presentation
        $data = $this->entry->dataContent;
        $dataXml = new SimpleXMLElement($data);
        $mediaEntryId = $dataXml->video->entryId->__toString();
        // change the thumbnail URL to include the entry Id of the media (video) entry
        $this->entry->thumbnailUrl = preg_replace('/\/entry_id\/([^\/])+/', '/entry_id/'.$mediaEntryId, $this->entry->thumbnailUrl);
        $divClass = 'kVidPres';
        $enableDuration = false;
        $enableViews = false;
    }
    else
    {
        $divClass = '';

        if($this->entry->mediaType == Kaltura_Client_Enum_MediaType::AUDIO)
        {
            $divClass = 'kAudio';
        }
        elseif($this->entry->mediaType == Kaltura_Client_Enum_MediaType::IMAGE)
        {
            $divClass = 'kImage';
        }

        // get the entry type related classes
        $models = Kms_Resource_Config::getModulesForInterface('Kms_Interface_Functional_Gallery_Item');
        foreach ($models as $model)
        {
            $divClass .= ' ' . $model->getItemClass($this->entry);
        }

        $enableDuration = true;
        $enableViews = true;
    }
    if(isset($this->odd) && $this->odd)
    {
        $divClass .= ' odd';
    }
    

    $desc_title = $this->escape($this->String()->shortenDescription(strip_tags($this->entry->description), 430));
	$isWebcast = ( !strpos($divClass, "webcast") === false );
    $isLive = ( $isWebcast && !strpos($divClass, "join") === false );
	$isRegister = ( $isWebcast && !strpos($divClass, "register") === false );
?>

<li <?php echo $divClass ? 'class="'.$divClass.'"' : '' ?> data-entryid="<?php echo $this->entry->id ?>" <?php echo Kms_Resource_Config::getConfiguration('gallery', 'thumbnailRotator')  && !$this->Device(array('ios', 'android')) ? $this->thumbRotator('img.tmb', $this->entry) : ''; ?>>
    <<?php echo $this->itemTag?> class="operate">
        <?php if(!$this->disableCheckbox): ?>
        <input type="checkbox" value="<?php echo $this->entry->id; ?>" name="sel-entry" id="sel-entry" class="sel-entry" />
        <?php endif; ?>
        <div class="item">
            <h3 class="name"><em></em><a href="<?php echo $this->EntryLink($this->entry->id, $this->entry->name);?>" ><?php echo $this->escape($this->entry->name);?></a></h3>
            <a class="img" href="<?php echo $this->EntryLink($this->entry->id, $this->entry->name); ?>" >
                <?php if($this->entry->status == Kaltura_Client_Enum_EntryStatus::READY): ?>
                <img class="tmb" src="<?php echo $this->entry->thumbnailUrl; ?>/width/143/height/79/type/<?php echo Kaltura_Client_Enum_ThumbCropType::CROP;?>" width="143" height="79" alt="<?php echo $this->escape($this->entry->name); ?>" />
                <div class="playIcon"></div>
                <?php if($enableDuration): ?>
                <div class="duration <?php echo $divClass; ?>">
					<?php if (!$isLive && !$isRegister):
						echo $this->String()->formatDuration($this->entry->duration).""; 
					?>'
					<?php endif; ?>
				</div>
                <?php endif; ?>
                <?php else: ?>
                <img title="<?php echo $this->translate('Converting');?>" src="<?php echo $this->baseUrl('/img/converting.png?'); echo $this->entry->status ?>" height="79" width="143" alt="<?php echo $this->escape($this->entry->name); ?>" />
                <?php endif;?>
            </a>
            <div class="item_content">
                <?php if(isset($this->entry->description) && strlen($this->entry->description)): ?>
                <span <?php echo $desc_title ? 'title="'.$desc_title.'"' : '';?> class="short_desc"><?php echo $this->escape($this->String()->shortenDescription($this->entry->description, 200));?></span>
                <?php endif; ?>
                <ul id="entry_tags" class="wrapper">
                <?php
                $tagsOut = '';
                if($this->entry->tags) 
                {
                    // max 20 tags
                    $entryTags = array_slice(explode(", ", $this->entry->tags), 0, 20);
                    foreach($entryTags as $entryTag) 
                    {
                        
                        if(strpos($entryTag, "displayname_") === false) 
                        {
                            $tagUrl = isset($this->tagUrl) && $this->tagUrl ? str_replace('%tag%', $entryTag, $this->tagUrl) : $this->MergeUrl(array('tag' => $entryTag));
                            $tagRel = isset($this->tagRel) && $this->tagRel !== null ? $this->tagRel : 'async';
                            

                            $tagsOut .= '<li><a href="' . $tagUrl . '" rel="'.$tagRel.'">' . $this->escape($entryTag) . '</a></li>';
                        }
                    }
                }
                if($tagsOut != ''):
                ?>
                        <?php echo $tagsOut; ?>
                <?php             
                endif;
                ?>
                </ul>
                <?php
                if($enableViews)
                {
                    $views = isset($this->entry->views) && $this->entry->views ? number_format($this->entry->views) : "0";
                }
                ?>
                <div class="stats">
                    <?php 
                        // check if published or not
                        $published = Kms_Resource_Models::getEntry()->isPublished($this->entry);
                        
                        if($enableViews):
                    ?>

                    <?php echo $this->translate('Views');?>: <?php echo "$views&nbsp;";?>
                    <?php endif; ?>
                	<?php if ($this->entry->moderationStatus==Kaltura_Client_Enum_EntryModerationStatus::REJECTED) echo '('. $this->translate('Not approved') .')';     
                    else
                    	if ($this->showPublish) echo '('. ($published ? $this->translate('Published') : $this->translate('Not published')).')'; ?>
                </div>     
                <div class="datetime" title="<?php echo date("F d, Y h:i A", $this->entry->createdAt); ?>"><?php echo $this->translate('uploaded') . ' ' . $this->Timespan($this->entry->createdAt, time()); ?></div>
                <div class="schedtype">
                    <?php if ($this->entry->userId == Kms_Resource_Client::getUserId())
                		if (time() > $this->entry->startDate && time() < $this->entry->endDate)
                			echo "";
                		else if (isset($this->entry->startDate) && time() < $this->entry->startDate)
                			echo $this->translate('Future Scheduling'); 
                		else if (isset($this->entry->endDate) && time() > $this->entry->endDate)
                			echo $this->translate('Past Scheduling');
                		else 
                			echo "";
                	?>
                </div>										
            </div>
        </div>
        <ul class="actionLinks">
        <?php 
        // action links
        if(isset($this->actions) && count($this->actions)): ?>
        <?php foreach($this->actions as $action): ?>
            <li><?php echo $action;?></li>
        <?php endforeach; ?>
        <?php endif; ?>
        </ul>
    </<?php echo $this->itemTag; ?>>
    <div class="drag_icon"></div>
</li>
<?php
