<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

$channel = isset($this->partialLoop()->view->channel) ? $this->partialLoop()->view->channel : null;

$displayName = $this->String()->getAuthorNameFromTags($this->tags);

$displayNameExists = $displayName ? true : false;

$_name = $displayName ? $displayName : $this->userId;
$displayName = $_name;

$divClass = '';

if($channel)
{
    $params = 'channelid='.$channel->id;
}
elseif($this->partialLoop()->view->categoryId)
{
    $params = 'catid='.$this->partialLoop()->view->categoryId;
}
else
{
    $params = '';
}


// retrieve the entryid for the thumbnail (the media entry)
$data = $this->dataContent;
$dataXml = new SimpleXMLElement($data);
$mediaEntryId = (string) $dataXml->video->entryId;
// change the thumbnail URL to include the entry Id of the media (video) entry
$this->thumbnailUrl = preg_replace('/\/entry_id\/([^\/])+/', '/entry_id/'.$mediaEntryId, $this->thumbnailUrl);

$title = $this->escape($this->String()->shortenDescription(strip_tags($this->description), 240));
?>
<li class="kVidPres" data-entryid="<?php echo $this->id ?>" <?php echo Kms_Resource_Config::getConfiguration('gallery', 'thumbnailRotator') && !$this->Device(array('ios','android')) ? 'onmouseover="KalturaThumbRotator.start($(this).find(\'.item_link > img\').get(0))" onmouseout="KalturaThumbRotator.end($(this).find(\'.item_link > img\').get(0))"' : ''; ?> >
    <a <?php echo $params ? 'data-params="'.$params.'"' : ''; ?> href="<?php echo $this->EntryLink($this->id, $this->name); ?>" class="item_link" <?php echo $title ? 'title="'.$title.'"' : '';?>>
        <img src="<?php echo $this->thumbnailUrl; ?>/width/148/height/84/type/<?php echo Kaltura_Client_Enum_ThumbCropType::CROP;?>" height="84" width="148" alt="<?php echo $this->escape($this->name); ?>">
        <span class="duration"><?php echo $this->String()->formatDuration($this->duration); ?>'</span>
        <span class="icon"></span>
        <span class="item_name"><?php echo $this->escape($this->name); ?></span>
    
    </a>
    <span class="createdBy"><?php echo $this->translate('By'); ?>:&nbsp;<a class="nickname" href="<?php echo $this->baseUrl("/createdby/" . $displayName . ($displayNameExists ? '/dn' : ''));?>"><?php echo $displayName; ?></a> <nobr><?php echo $this->Timespan($this->createdAt); ?></nobr></span>
<?php 
// echo $this->partial('partials/entryItem/removeLink.phtml', $this);
?>
</li>
<?php
