<?php

/*
 *  All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 *  To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
$iterator = new RecursiveIteratorIterator($this->container, RecursiveIteratorIterator::SELF_FIRST);

$depth = -1;
$i = 1;

$dlOpened = false;
foreach ($iterator as $level => $page)
{
    // check if page is a category
    if ($page->categoryname)
    {
        if ($depth < $iterator->getDepth() && !$dlOpened)
        {
            echo '<dl style="padding-left: ' . (10 * $iterator->getDepth()) . 'px">';
            $dlOpened = true;
        }
        elseif ($depth > $iterator->getDepth())
        {
            if ($dlOpened)
            {
                echo '</dl>';
            }
            echo '<dl style="padding-left: ' . (10 * $iterator->getDepth()) . 'px">';
        }
        $depth = $iterator->getDepth();
        
        echo $this->partial('partials/bulkCategoryItem.phtml', 'publish', array
            (
            'label' => $page->getLabel(),
            'catid' => $page->catNum,
            'depth' => $iterator->getDepth(),
            'id' => $i,
                )
        );
        $i++;
    }
}
