<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/


$action = $this->checked ? 'unpublish' : 'publish';

?>
<li style="padding-left: <?php echo (30 * $this->depth);?>px">
<a href="<?php echo $this->baseUrl('/publish/index/'.$action.'/boxId/'.$this->id.'/entry/'.urlencode($this->entry->id).'/category/'.urlencode($this->catid));?>" rel="async" class="wrapper">
<?php
    echo $this->formCheckbox('publish_'.$this->id, $this->catid, array('checked' => $this->checked));
?>
&nbsp;
<?php
    echo $this->formLabel('publish_'.$this->id, $this->label);
?>
</a>
</li>
