<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

?>
<li data-id="<?php echo $this->category->id?>">
    <?php echo Kms_View_Helper_String::formatCategoryName($this->category->name) ?>
    <span>
        <a class="remove_playlist" href="<?php echo $this->baseUrl('/publish/index/unpublish/entry/'.urlencode($this->entryId).'/category/'.urlencode($this->category->id));?>" rel="async"></a>
    </span>
</li>
