<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

?>
<h1><?php echo $this->translate('Upload Document');?></h1>
<div class="kvpmContainer">
    <div class="kvpmBox">
        <?php echo $this->translate('A video presentation consists of a document and a video file, synchronized together, Document formats supported are:ppt/pptx, pdf, doc/ docx, xls/ xlsx.'); ?>
        <br/>
        <?php echo $this->translate('After the document is uploaded, it will be converted to a format suitable for display in the presentation (this might take a few minutes).');?>
        <br/>
        <?php echo $this->translate('Once your content is ready it will appear in the document list(step 2).'); ?><br/>
        
        <a id="kvpmLink" href="<?php echo $this->baseUrl('/upload/presentation'); ?>"><?php echo $this->translate('Back to the video presentation creation flow (step 1)'); ?></a>
        <div class="kvpmWidget">
            <div class="widgetContainer">
                <?php echo $this->partial('partials/widgets/documentCreation.phtml'); ?>
            </div>
        </div>
    </div>
</div>
