<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
?>
<h1><?php echo $this->translate('Add Video Presentation');?></h1>
<div class="kvpmContainer">
    <div class="kvpmBox">
        <h4><?php echo $this->translate('To create a Video Presentation, follow these steps');?>:</h4>
        <ul>
            <li><span><?php echo $this->translate('Select media (from a list of already uploaded and ready video and audio items)');?></span></li>
            <li><span><?php echo $this->translate('Select document (from a list of uploaded, and converted documents)');?></span></li>
            <li><span><?php echo $this->translate('Add sync points to synchronize the document with the media');?></span></li>
        </ul>
        
        <?php echo $this->translate('In case you need to upload new documents to the server, use the upload document button below.');?>
        <?php echo $this->translate('Once a Presentation is created, you will be redirected to the "edit page", where you will be able to sync keypoints for playback, and edit metadata.');?>
        <br/>
        <a class="uploadDocButton" href="<?php echo $this->baseUrl('/upload/document'); ?>" title="<?php echo $this->translate('Upload Document');?>">
            <span class="text"><?php echo '+&nbsp;'.$this->translate('Upload Document'); ?></span>
        </a>
        <div class="kvpmWidget">
            <div class="widgetContainer">
                <?php echo $this->partial('partials/widgets/kvpmCreation.phtml'); ?>
            </div>
        </div>
    </div>
</div>