<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

?>
<h1 class="uploadBoxHeading"><?php echo $this->translate('Record from Webcam');?></h1>
<div id="uploadbox1" class="uploadbox webcam">
    <div class="entry_status">
        <div class="progressbar"><span style="position: absolute"></span></div>
        <div class="krecord_container">
            <?php echo $this->partial('partials/widgets/krecord.phtml'); ?>
        </div>
    </div>
    
     <div id="entry_details"  class="entry_details">
        <h4><?php echo $this->translate('Please fill out these details');?>:</h4>
         <?php echo $this->partial()->view->form ?>
    </div>
</div>
<?php
/*
 * 
 * "autoStopRecord","detectedMicrophone", "deviceDetected", "detectedCamera" (same as the one before), "connected", "recordStart", "flushComplete", "connecting", "connectingFinish", "previewEnd", "beforeAddEntry", "addEntryFailed", "addEntryComplete","addEntryFail",
 * "noCamerasFound", "micDenied", "workingMicFound", "noMicsFound"
 * 
 */
?>
