<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

$front = Zend_Controller_Front::getInstance();
if ($front->getPlugin('Kms_Plugin_Access')->hasPermission('channels', 'create')){
    echo '<div id="gallerybuttons"><a class="btn" id="add_channel_media" href="' . $this->baseUrl('channels/create') . '">' . $this->translate('Create Channel') . '<span class="icon">&nbsp;</span></a></div>';
}
