<?php

/* 
 *  All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 *  To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

if($this->comment):
    
    if(trim($this->parentId))
    {
        $this->isReply = true;
        $target = '#comments_tab > .container > ul > li[data-comment-id="'.$this->parentId.'"] > ul.replies';
        $action = $this->repliesNewestFirst ? 'prependFade' : 'appendFade';
        $this->JsonContent(array(
            'target' => '#comments_tab > .container > ul > li[data-comment-id="'.$this->parentId.'"] .replyForm',
            'action' => 'deleteFade',
            'content' => ''
            )
        );
    }
    else
    {
        $this->isReply = false;
        $target = '#comments_tab > .container > ul';
        $action = $this->boxOnTop ? 'prependFade' : 'appendFade';
        
    }
    
    $this->JsonContent(array(
        'target' => '#comments_tab #comment_count',
        'content' => $this->commentsCount,
        'action' => 'replace',
    ));
    
    $this->JsonContent(array(
        'target' => $target,
        'content' => $this->partial('partials/comment.phtml', 'comments', array('allowedToPost' => $this->allowedToPost, 'commentsClosed' => $this->commentsClosed, 'comment' => $this->comment, 'isReply' => $this->isReply, 'replyToUser' => $this->replyTo)),
        'action' => $action,
    ));
    
    

    $this->JsonScript('$("#commentsbox").val("'.$this->defaultText.'").removeClass("focus");');
    $this->JsonScript('$("#comments_tab #comment_count_to").text($("#comments_tab > .container > ul > li.comment").length);');
    if($this->commentsCount)
    {
        $this->JsonScript('$("#comments_tab .nocomments").hide();$("#comments_tab .counters").show();');
    }
    else
    {
        $this->JsonScript('$("#comments_tab .nocomments").show();$("#comments_tab .counters").hide();');
    }
    
endif;

