<?php
/*
 *  All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 *  To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
?>
<div id="edit_entry_comments_options">
<?php
echo $this->partial('partials/entryOptions.phtml', 'comments', array(
    'entryId' => $this->entryId,
    'disableComments' => $this->disableComments,
    'commentsClosed' => $this->commentsClosed,
    'allowClose' => $this->allowClose,
));
?>
</div>

<?php


