<?php

/* 
 *  All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 *  To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

$this->JsonContent(array(
    'target' => '#comments_tab > .container > ul > li[data-comment-id="'.$this->commentId.'"] .replyForm',
    'action' => 'deleteFade',
    'content' => ''
    )
);
$this->JsonContent(array(
    'target' => '#comments_tab > .container > ul > li[data-comment-id="'.$this->commentId.'"] > ul.replies',
    'action' => 'before',
    'content' => '<div class="wrapper replyForm">' . $this->form->render() . '</div>'
    )
);

$this->JsonScript("$('html, body').animate({scrollTop: $('#comments_tab > .container > ul > li[data-comment-id=\"".$this->commentId."\"] .replyForm').offset().top}, 500);");
