<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

if($this->commentsEnabled) : ?>
<li><a data-tab="#comments_tab" id="comments_tab_link" rel="async" href="<?php echo $this->baseUrl('/comments/index/index/entryid/'. $this->entryId); ?>"><?php echo $this->translate('Comments'); ?></a></li>
<script>
    $('.comment .replies .comment').live('mouseover', function() {
        $(this).parents('.comment').addClass('nohover');
    });
    
    $('.comment .replies .comment').live('mouseout', function() {
        $(this).parents('.comment').removeClass('nohover');
    });
</script>
<?php endif;
