<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/
if($this->success)
{
    $this->JsonContent(array(
                'target' => '#player_tabs #addtoplaylist_tab .container div.addnewplaylistform',
                'content' => $this->partial(
                        'partials/playlistCheckbox.phtml', 
                        'addtoplaylists', 
                        array(
                            'playlist' => $this->playlist,
                            'entryId' => $this->entryId,
                            'checked' => $this->checked
                        )
                ),
                'action' => 'before',
            )
    );
    
    $this->JsonContent(array(
                'target' => '#player_tabs #addtoplaylist_tab .baloons ',
                'content' => $this->partial(
                        'partials/playlistBaloon.phtml', 
                        'addtoplaylists', 
                        array
                        (
                            'id' => $this->playlist->id, 
                            'name' =>  $this->playlist->name,
                            'entryId' => $this->entryId
                        )
                    ),
                'action' => 'appendFade'
            )
        );
    $this->JsonScript('$("#player_tabs #addtoplaylist_tab .container input#playlist").addClass("default-text").attr("value","'.$this->translate('Add New Playlist').'")');
}
