<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/
if($this->success && count($this->playlist))
{
    if(!$this->bulk)
    {
        $this->JsonContent(array(
                'target' => '#player_tabs #addtoplaylist_tab .container div[data-id='.$this->playlist->id.']',
                'content' => $this->partial(
                        'partials/playlistCheckbox.phtml', 
                        'addtoplaylists', 
                        array(
                            'playlist' => $this->playlist,
                            'entryId' => $this->entryId,
                            'checked' => $this->checked
                        )
                ),
                'action' => 'replace',
            )
        );

        if($this->checked)
        {
            $this->JsonContent(array
                (
                'target' => '#player_tabs #addtoplaylist_tab .baloons',
                'content' => $this->partial(
                            'partials/playlistBaloon.phtml', 
                            'addtoplaylists', 
                            array
                            (
                                'id' => $this->playlist->id, 
                                'name' =>  $this->playlist->name,
                                'entryId' => $this->entryId,
                            )
                        ),
                'action' => 'appendFade'
                )
            );
        }
        else
        {
            $this->JsonContent(
                array
                (
                    'target' => '#player_tabs #addtoplaylist_tab .baloons li[data-id='.$this->playlist->id.']',
                    'content' => ' ',
                    'action' => 'deleteFade'
                )
            );
        }
    }    
/*    $response = array(
        'content' => $content
    );*/
}
/*else
{
    $response = array(
        'content' => array()
    );
}
echo Zend_Json::encode($response);*/
$this->JsonScript($this->scriptOut);