<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

if($this->allowed) : ?>
<li >
    <button id="addtoplaylistButton">Add to Playlist</button>
    <div id="addtoplaylist">
        <?php  
            if(count($this->playlists)):
                foreach($this->playlists as $playlist):
                    $playlistEntries = explode(',', $playlist->playlistContent);
                    if(in_array($this->entryId, $playlistEntries)): // entry is already in this playlist, set it to disabled...
        ?>
        <a class="exists"><?php echo $playlist->name?></a>
        <?php
                    else:
        ?>
        <a data-id ="<?php echo $playlist->id; ?>" href="<?php echo $this->baseUrl('/addtoplaylists/index/add-entry/playlist/'.$playlist->id.'/entry/'.$this->entryId)?>" rel="async"><?php echo $playlist->name?></a>
        <?php
                    endif;
                endforeach;
            endif;
        ?>
        <form action="<?php echo $this->baseUrl('/addtoplaylists/index/add-new-playlist/entry/'.$this->entryId)?>" method="POST" ajax="1">
        <?php
            if($this->allowCreate)
            {
                $defaultText = 'Create new playlist';
                echo $this->formText('playlist', $defaultText, array(
                    'onfocus' => 'if($(this).val() == "'.$defaultText.'") {$(this).val("");}',
                    'onblur' => 'if($(this).val() == "") { $(this).val("'.$defaultText.'");}',
                    
                ));
            }
        ?>
        </form>
    </div>
</li>
<script>
    var addToPlaylistOpen = false;
    var addToPlaylistOpen_Callback;
    
    
    addToPlaylistOpen_Callback = function(ev){
        //console.log(target);
        if(!addToPlaylistOpen) {
            $('#addtoplaylist').show();
            addToPlaylistOpen = true;
            $(this).addClass('open');
            
            $('html').bind('click', addToPlaylistOpen_Callback);
            return false;
        
        }
        else {
            var target = ev.target;
            var isAddToPlaylistDiv = $(target).closest('div#addtoplaylist').length;
            if(!isAddToPlaylistDiv && target.tagName != 'a')
            {
                $('html').unbind('click', addToPlaylistOpen_Callback);
                $('#addtoplaylist').hide();
                addToPlaylistOpen = false;
                $(this).removeClass('open');
            }
        }
        
      //  return false;
    }        
    
    
    
    $("#addtoplaylistButton").click(addToPlaylistOpen_Callback);
    
</script>
<?php endif;  ?>
