<?php
/*
 *  All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 *  To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

/**
 * @ignore
 * @author Leon Gordin
 */

// increase memory limit
ini_set('memory_limit', '256M');

?>
<?php if(!isset($this->nocontainer) || !$this->nocontainer):?>
<style type="text/css">

#phpinfo body, #phpinfo td, #phpinfo th, #phpinfo h1, #phpinfo h2 {font-family: sans-serif;}
#phpinfo pre {margin: 0px; font-family: monospace;}
#phpinfo a:link {color: #000099; text-decoration: none; background-color: #ffffff;}
#phpinfo a:hover {text-decoration: underline;}
#phpinfo table {border-collapse: collapse; width:80%}
#phpinfo .center {text-align: center;}
#phpinfo .center table { margin-left: auto; margin-right: auto; text-align: left;}
#phpinfo .center th { text-align: center !important; }
#phpinfo td, th { border: 1px solid #000000; font-size: 100%; vertical-align: baseline;}
#phpinfo h1 {font-size: 150%;}
#phpinfo h2 {font-size: 125%;}
#phpinfo .p {text-align: left;}
#phpinfo .e {background-color: #ccccff; font-weight: bold; color: #000000;}
#phpinfo .h {background-color: #9999cc; font-weight: bold; color: #000000;}
#phpinfo .v {background-color: #cccccc; color: #000000;}
#phpinfo .vr {background-color: #cccccc; text-align: right; color: #000000;}
#phpinfo img {float: right; border: 0px;}
#phpinfo hr {background-color: #cccccc; border: 0px; height: 1px; color: #000000;} 

/* debug bar */
.debugBar {
    position: fixed;
    z-index: 2001;
    width: 100%; top: 0px; }
/* end debug bar */
.debugBar ul {list-style-type: none;}
.debugBar > .container {position: relative; width: 960px; margin: 0 auto;}
.debugBar .container > ul {float:left;  background-color: #E5E5E5;}
.debugBar .container > ul.removable {border-left: 1px solid black;}
.debugBar .menu { padding: 0 10px;  }
.debugBar .menu .title {cursor: pointer; }
.debugBar .menu.open .title { display: block; font-weight: bold}
.debugBar .menu.open  {width: auto;padding: 0 10px 10px 10px;  }
.debugBar .menu ul.wrapper {display: none; position: absolute; left: 0px; background-color: #E5E5E5;}
.debugBar .close, .debugBar .clear {padding:0 10px; border-left: 1px solid black; background-color: #E5E5E5;}
.debugBar .menu.open ul.wrapper {padding-left: 5px; width: 100%; display: block}
.debugBar .item { padding-top: 10px; height: 20px;  border-top: 1px solid black}
.debugBar .item.open {height: auto;width: auto}
.debugBar .item > div {max-height: 350px; overflow: auto; padding-top: 10px; padding-bottom: 10px;display: none}
.debugBar .item.open > div {display: block}
.debugBar .item > a { display: block}
.debugBar a {cursor: pointer}
.debugBar .apidebug .one {background-color: #F5F5F0}
.debugBar .apidebug .two {background-color: #FAFAFA}
.debugBar a.logdump {color: #222; display: block}
.debugBar a.logdump:hover {color: #3FC0F0; display: block}
.debugBar div.debugline {display: none; padding:3px; background-color: #EFEFEF}
.debugBar .show {display: block !important}
.debugBar .configswap input, .debugBar .configswap button {float:left}
.debugBar .xmldumpDiv {display: none}
.debugBar .xmldumpDiv.show {display: block}



</style>
<div class="debugBar"> 
    <div class="container">
        <ul>
<?php else: ?>
        <ul class="removable">
<?php endif; ?>
        
            <li class="menu">
                <a class="title" title="<?php echo UNIQUE_ID;?>"><?php echo isset($this->title) ? $this->title : 'DEBUG INFO';?></a>
                <ul class="wrapper">
                    <li class="item">
                        UNIQUE ID: <?php echo UNIQUE_ID;?>
                    </li>
                    <li class="item">
                        REQUEST URI: <?php echo $_SERVER['REQUEST_URI']; ?>
                    </li>
                    <li class="item">
                        <a>REQUEST OBJECT</a>
                        <div>
                            <?php 
                                $req = clone Zend_Controller_Front::getInstance()->getRequest(); 
                                $req->setParam('error_handler', null);
                                Zend_Debug::dump($req);
                                ?>
                        </div>
                    </li>
                    <li class="item">
                        <a>APPLICATION LOG</a>
                        <div class="apidebug">
                        <?php 
                        $this->cycle()->assign(array('one','two'));
                        $logLines = $this->action('log-viewer', 'admin', null, array('uniqueid' => UNIQUE_ID, 'type' => 'general' , 'format' => 'ajax'));
                        if(trim($logLines))
                        {
                            foreach(explode("\n", $logLines) as $logLine)
                            {
                                $logLine = trim($logLine);
                                $requestId = '';
                                if($logLine)
                                {
                                    preg_match('#\[request: (.*)?\]#U', $logLine, $requestMatch);
                                    if(isset($requestMatch[1]))
                                    {
                                        $requestId = $requestMatch[1];
                                    }
                                    echo '<p>'.$this->escape($logLine).'</p>';
                                }
                            }
                        }
                        else
                        {
                            echo '<div>There is nothing in the log file</div>';
                        }
                        ?>
                        </div>
                    </li>
                    <?php if(Kms_Resource_Config::getConfiguration('debug', 'kalturaStats')): ?>
                    <li class="item">
                        <a>API LOG</a>
                        <div class="apidebug">
                        <?php 
                        $this->cycle()->assign(array('one','two'));
                        $logLines = $this->action('log-viewer', 'admin', null, array('uniqueid' => UNIQUE_ID, 'type' => 'api' , 'format' => 'ajax'));
                        if(trim($logLines))
                        {
                            $logNumber = 0;
                            foreach(explode("\n", $logLines) as $logLine)
                            {
                                $logLine = trim($logLine);
                                $requestId = '';
                                if($logLine)
                                {
                                    preg_match('#\[request: (.*)?\]#U', $logLine, $requestMatch);
                                    if(isset($requestMatch[1]))
                                    {
                                        $requestId = $requestMatch[1];
                                    }
                                    echo '<a class="logdump '.$this->cycle()->next().'" data-id="'.UNIQUE_ID.'-'.$requestId.'">'.$this->escape($logLine).'</a>';
                                }
                                if(Kms_Resource_Config::getConfiguration('debug', 'kalturaDebug'))
                                {
                                    $logDebugLines = $this->action('log-viewer', 'admin', null, array('uniqueid' => UNIQUE_ID, 'requestid' =>  $requestId, 'type' => 'apidebug' , 'format' => 'ajax'));
                                    //Zend_Debug::dump($logDebugLines);

                                    echo '<div class="debugline" data-id="'.UNIQUE_ID.'-'.$requestId.'"><pre>';
                                    foreach(explode("\n", trim($logDebugLines)) as $debugLine)
                                    {
                                        $logNumber++;
                                        $debugLineLink = '';
                                        $xmlRes = preg_match('/result \(serialized\): (<\?xml.*\/xml>)$/', $debugLine, $xmlMatches);
                                        if($xmlRes)
                                        {
                                            if(isset($xmlMatches[1]))
                                            {
                                                $debugLineLink = '<a class="xmldump" data-num="'.UNIQUE_ID.'-'.$requestId.'-'.$logNumber.'" title="'.$this->escape($xmlMatches[1]).'">'.$this->escape(substr($debugLine, 0, 120) ).'...</a><br/>';
                                                $debugLineLink .= '<div class="xmldumpDiv" data-num="'.UNIQUE_ID.'-'.$requestId.'-'.$logNumber.'">'.Kms_Resource_Debug::xmlpp($xmlMatches[1], true).'</div>';
                                            }
                                        }
                                        if($debugLineLink)
                                        {
                                            echo $debugLineLink;
                                        }
                                        else
                                        {
                                            echo $this->escape($debugLine)."\n";
                                        }
                                    }
                                    echo '</pre></div>';
                                }
                            }
                        }
                        else
                        {
                            echo '<div>No API calls issued for this request (Maybe they were all cached?)</div>';
                        }
                        ?>
                        </div>
                    </li>
                    <?php endif;?>
                    <li class="item">
                        <a>SESSION DUMP</a>
                        <div>
                        <?php 
                        Zend_Debug::dump($_SESSION);
                        ?>
                        </div>
                    </li>
                    <?php if(!isset($this->nocontainer) || !$this->nocontainer):?>                    
                    <li class="item">
                        <a>CONFIG SWAP</a>
                        <div>
                            <p>Current Config File: <?php echo Kms_Resource_Config::getConfigFileName(); ?>
                            <div class="configswap">
                                <input type="text" id="customconfig" />
                                <button id="changeConfig">GO</button>&nbsp;<button id="clearConfig">RESET</button>
                                <script>
                                    $('#changeConfig').click(function(){
                                        if($('#customconfig').val()) {
                                            document.cookie = "<?php echo Kms_Resource_Config::DEBUG_CONFIG_NAME;?> = "+$('#customconfig').val()+";path=/";
                                            document.location.reload();
                                        }
                                    });
                                    $('#clearConfig').click(function(){
                                        document.cookie = "<?php echo Kms_Resource_Config::DEBUG_CONFIG_NAME;?> =; expires="+new Date(0).toUTCString()+";path=/";
                                        document.location.reload();
                                    });

                                </script>
                            </div>
                        </div>
                    </li>
                    <?php endif; ?>
                    <li class="item">
                        <a>CONFIGURATION INFORMATION</a>
                        <div>
                        <?php 
                        $configModel = new Application_Model_Config();
                        $sections = $configModel->getTabs();


                        $writer =  new Zend_Config_Writer_Ini( );

                        foreach($sections['global'] as $sectionName):?>
                            <h3><?php echo $sectionName; ?></h3>
                            <hr/>
                            <pre><?php 
                                $confObj = Kms_Resource_Config::getSection($sectionName);
                                if($confObj instanceof Zend_Config)
                                {
                                    $writer->setConfig($confObj);
                                    echo $this->escape($writer->render());
                                }
                            ?></pre>
                        <?php endforeach;?>
                        </div>
                    </li>
                    <li class="item">
                        <a>MODULES CONFIGURATION</a>
                        <div>
                        <?php 
                        $modules = $sections['modules'];
                        $writer = new Zend_Config_Writer_Ini();

                        foreach($modules as $moduleName => $enabled)
                        {
                            $moduleConfig = Kms_Resource_Config::getModuleSection($moduleName);
                            if($moduleConfig)
                            {
                            ?>
                            <?php if($enabled):?>
                                <h3><?php echo $moduleName; ?></h3>
                                <hr/>
                            <?php else: ?>
                                <h3><del><?php echo $moduleName; ?></del></h3>
                            <?php endif;?>
                            <pre><?php 
                                {
                                    $writer->setConfig($moduleConfig);
                                    echo $writer->render();
                                }
                            ?></pre>
                                
                        <?php 
                            }
                        }
                        ?>
                        </div>
                    </li>
                    <li class="item">
                        <a>PHPINFO()</a>
                        <div id="phpinfo">
                            <?php
                            ob_start();
                            phpinfo();
                            $pinfo = ob_get_contents();
                            ob_end_clean();
 
                            $pinfo = preg_replace( '%^.*<body>(.*)</body>.*$%ms','$1',$pinfo);
                            echo $pinfo;
                            ?>
                        </div>
                    </li>
                </ul>
            </li>
        </ul>
<?php if(!isset($this->nocontainer) || !$this->nocontainer):?>
    </div>
    <ul>
        <li><a class="close">(Close)</a><a class="clear">(Clear)</a></li>
    </ul>
</div>
<script>
    $('.debugBar li.item > a').live('click', function(event){
        var $li = $(event.target).closest('li');
        var $menu = $(event.target).closest('.menu');
        var isOpen = $li.hasClass('open');
        $($menu).find('li.item').removeClass('open');            
        if(!isOpen) {
            $li.addClass('open');
        }
    });
    
    $('.debugBar li.menu .title').live('click', function(event){
        var $li = $(event.target).closest('li.menu');
        var isOpen = $li.hasClass('open');
        $('.debugBar li.menu').removeClass('open');
        if(!isOpen) {
            $li.addClass('open');
        }
    });
    $('.debugBar .clear').click(function(event){
       $('.debugBar .container ul.removable').remove(); 
    });
    $('.debugBar .close').click(function(event){
       $('.debugBar li.menu').removeClass('open');
    });
    
    $('a.logdump').live('click', function(){
        var id = $(this).attr('data-id');
        var $menu = $(this).closest('.menu');
        $('div.debugline[data-id="'+id+'"]', $menu).toggleClass('show');

    });
    $('div.debugline a.xmldump').live('click', function(){
        var num = $(this).attr('data-num');
        $('.debugBar .xmldumpDiv[data-num='+num+']').toggleClass('show');
    })
</script>
<?php
endif;