<?php
/*
 *  All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 *  To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
?>

<?php if (isset($this->messages) && count($this->messages) > 0): ?>
    <?php foreach ($this->messages as $message): ?>
	<div class="ui-state-highlight ui-corner-all">
	    <p class="ui-icon ui-icon-lightbulb"></p><p class="flash-message"><?php echo $message; ?></p>
	</div>
    <?php endforeach; ?>
    <script>
        $("#flash-messages > div").fadeIn(1000);
        setTimeout('$("#flash-messages > div").fadeOut();', 6000);
    </script>
<?php endif; ?>
