<?php

/* 
 *  All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 *  To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */


?>
<script>
    var debug = <?php echo Kms_Resource_Debug::isEnabled() ? '1' : '0' ?>;
    var jsHighlight = <?php echo Kms_Resource_Config::getConfiguration('debug', 'highlightJs') ? 1 : 0; ?>;
    if(debug) {
        var start = new Date().getTime();
    }
    var baseUrl = "<?php echo $this->baseUrl(); ?>";
    
</script>
<?php

