<?php

/* 
 *  All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 *  To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

/**
 *	render the site footer
 * 	@viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_FOOTER
 */
?>
<div id="kfooter" class="limiter">MediaSpace&trade; <a href="http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal" target="_blank"><?php echo $this->translate('video portal'); ?></a> <?php echo $this->translate('by'); ?> <a href="http://kaltura.com" target="_blank">Kaltura</a></div>
<div id="errorDialog"></div>
<?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_FOOTER);?>
<?php echo $this->footerScript();
