<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

/**
 * Partial template for the header
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_HEADERMENU
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_PRE_HEADERUPLOAD
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_POST_HEADERUPLOAD
 */
$front = Zend_Controller_Front::getInstance();
$isAnonymous = Zend_Auth::getInstance()->hasIdentity() && Zend_Auth::getInstance()->getIdentity()->getRole() == Kms_Plugin_Access::getRole(Kms_Plugin_Access::ANON_ROLE);
?>
<div id="topBar" class="<?php echo Kms_Resource_Config::getConfiguration('header', 'headerStyle') ?> wrapper">
    <div id="kheader" class="limiter">
	<span id="branding">
	    <?php echo $this->KmsLogo(); ?>
	</span>
	<span id="topnav" class="topnav">
	    <ul id="header_menu">
		<?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_HEADERMENU); ?>
		<?php echo $this->UserLink(); ?>
	    </ul>
            <?php if(Kms_Resource_Config::getConfiguration('header', 'enableUploadButton')): // credit goes to Zohar Babin for the idea for this feature ?>
                <?php if ($front->getPlugin('Kms_Plugin_Access')->hasPermission('entry', 'add') || $isAnonymous): ?>
                <ul class="upload_menu">
                    <li>
                        <a rel="require-flash" href="<?php echo $this->baseUrl('/upload'); ?>" id="open_upload"><span><?php echo $this->translate('Add New'); ?></span><em></em></a>
                        <ul>
                                <?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_PRE_HEADERUPLOAD); ?>
                            <li><a rel="require-flash" href="<?php echo $this->baseUrl('/upload'); ?>" title=""><span><?php echo $this->translate('Media Upload'); ?></span></a></li>
                            <li><a rel="require-flash" href="<?php echo $this->baseUrl('/upload/webcam/'); ?>" title=""><span><?php echo $this->translate('Webcam Recording'); ?></span></a></li>
                                <?php if (Kms_Resource_Config::getConfiguration('application', 'enablePresentations')): ?>
                                    <li><a rel="require-flash" href="<?php echo $this->baseUrl('/upload/presentation'); ?>" title=""><span><?php echo $this->translate('Video Presentation'); ?></span></a></li>
                                <?php endif; ?>
                                <?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_POST_HEADERUPLOAD); ?>
                        </ul>
                    </li>
                </ul>
                <?php endif; ?>
            <?php endif; ?>
            
	        <?php $form = $this->partial('partials/headerSearch.phtml'); ?>
		<?php echo $this->partial('partials/modifyGlobalSearch.phtml',array('form' => $form, 'formId' => 'main_search',)); ?>  
	</span>
    </div>
</div>
<!-- navigation -->
<div id="main_nav" class="wrapper">
    <?php
    $pages = Kms_Resource_Nav::getContainer()->getPages();

    if (count(Kms_Resource_Nav::getContainer())) {
	echo $this->navigation()->menu()->renderPartial(Kms_Resource_Nav::getContainer(), 'partials/mainNavigation.phtml');
    } else {
	echo '<ul class="navigation limiter"></ul>';
    }
    ?>
</div>
<script>
    // more menu navigation
    // @todo - add documentation to the function
    moreMenuNavigation = function() {
        var nav = $('#main_nav ul.navigation');
        var nav_width = nav.width();
        var nav_items = $('#main_nav ul.navigation li');
        var more_link = $('<li style="display: none" id="nav_more_li"><div><a><?php echo $this->translate('More'); ?><em>&nbsp;</em></a><ul id="nav_more_ul" class="wrapper"></ul></div></li>');
        nav.append(more_link);
        
        var more_link_width = more_link.outerWidth({margin: true});
        var more_container = $("#nav_more_ul");
        var allowed_width = nav_width;
        var ruler = 0;
        var to_append = [];
	
        $.each(nav_items, function(){
            ruler += $(this).outerWidth({margin: true});
            if(ruler > allowed_width - more_link_width){
                to_append.push($(this));
            }
        }); 
        
        if(ruler > allowed_width){
            $.each(to_append, function(){
                $(more_container).append($(this));
            });
            more_link.show();
        }
    }
    moreMenuNavigation();
    <?php if($this->Device(array('ios','android'))): ?>
        // fix for ipad/iphone
        $('#nav_more_li').click(function(){});
    <?php endif; ?>
</script>
