<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
?>
<div data-id="<?php echo $this->userId; ?>" class="wrapper member">
    <div class="username"><?php echo $this->escape((!empty($this->fullName) ? $this->fullName : $this->userId)); ?></div>
    <div class="user_id"><?php echo $this->escape($this->userId); ?></div>
    <div class="permissions" >
	<span  class="permission" data-id="<?php echo $this->userId; ?>">
	    <?php echo $this->partial('partials/memberPermissions.phtml', 'channelmembers', $this); ?>
	</span>
	<?php if ($this->userId == Kms_Plugin_Access::getId() || $this->userId == $this->partialLoop()->view->owner): ?>
	    <?php 
    	    $text = '';
    	    if ($this->userId == Kms_Plugin_Access::getId()){
    	        $text = $this->translate('you');
    	    }
    	    if ($this->userId == $this->partialLoop()->view->owner){
    	        $text .=  (!empty($text) ? ', ' : '') . $this->translate('owner');
    	    }
	    ?>
        <span class="remove"><?php echo $text; ?></span>    
	<?php else: ?>
	    <?php  	    
	           $params = $this->partialLoop()->view->urlParams;	           
	           $params['action'] = 'delete';
	           $params['categoryid'] =  $this->categoryId;
	           $params['uid'] =  urlencode($this->userId);	           
	    ?>
	    <a class="remove" rel="dialog" href="<?php echo $this->MergeUrl($params,'default'); ?>"><em>&nbsp;</em><?php echo $this->translate('remove') ?></a>
	<?php endif ?>
    </div>
</div>