<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
?>
<span class="current_role"><?php echo $this->permission; ?></span>
<?php if ($this->userId == Kms_Plugin_Access::getId() || $this->userId == $this->partial()->view->owner):?>
<span class="change"><?php echo '&nbsp';?></span>
<?php else:?>
<a class="change" rel="async" href="<?php echo $this->baseUrl('channelmembers/index/edit/channelname/' 
		. urlencode($this->partial()->view->channelName) . '/channelid/' . $this->partial()->view->channelId  
		. '/uid/' .$this->userId . '/perm/' . $this->permissionLevel);?>">
		<?php echo $this->translate('change')?></a>
<?php endif; 
        