<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
?>

<?php $content = '<div class="addmember" id="add_member">'.
    $this->partial('partials/addMember.phtml', 'channelmembers', array('form' => $this->form)).'</div>';
?>

if($('#dialog')) {
    $("body").append('<div id="dialog"></div>');
}
    
<?php
 echo new Zend_Json_Expr("$('#dialog').html(\"".(addcslashes(str_replace(array("\r\n", "\n", "\r"), '', $content), '\"'))."\");") ;
 
 $this->dialogContainer(
        'dialog', $content, array(
            'autoOpen' => true,
            'draggable' => false,
            'modal' => true,
            'width' => 360,
            'height' => 215,
            'resizable' => false,
            'title' => $this->translate('Add Member'),
            'closeOnEscape' => true,
            'close' => new Zend_Json_Expr('function() {
                $("#dialog").remove();
             }'),
        )
    );
 
 $actions = $this->JQuery()->getOnLoadActions();
 $this->JQuery()->disable();
 foreach ($actions as $action)
 {
     echo $action;
 }
 
