<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */


// channel member count
$this->JsonContent(array(
        'target' => '#members_count',
        'content' => $this->partial('partials/memberCount.phtml','channelmembers',$this),
        'action' => 'replace'
)
);

// parse the channel members
$this->placeholder('members')->captureStart('SET', 'members');

if ($this->members && count($this->members))
{
    echo $this->partialLoop('partials/channelMember.phtml', 'channelmembers', $this->members);
}
else
{
    echo $this->translate('There are no members...');
}
$this->placeholder('members')->captureEnd();


// the channels
$this->JsonContent(array(
        'target' => '#members',
        'content' => $this->placeholder('members')->members,
        'action' => 'replace'
)
);

// the pager
$pager = $this->paginationControl($this->paginator, $this->pagerType, 'partials/galleryPaging.phtml',array('urlParams' => $this->urlParams));

$this->JsonContent(array(
        'target' => '#channelmembers_tab #pager',
        'content' => $pager,
        'action' => 'replace'
)
);

// the dialog - if exists
$script = '$("#dialog").remove();';
$this->JsonScript($script);

// messages - if exists
if (!empty($this->message)){
    $this->JsonFlashMessage($this->message);
}