<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

?>
<div id="bulk_actions" class="wrapper">
    <div class="operate fleft">
        <?php 
            $attributes = array();
            if (!count($this->entries)){
                $attributes = array('disabled' => 'disabled');
            }
            echo $this->formCheckbox('checkall',null,$attributes);
        ?>
    </div>
    <div class="fright">
        <div class="views_switch fright">
            <?php if (count($this->entries)):?>
                <a class="short_view" href="<?php echo $this->MergeUrl($this->urlParams + array('view' => 'short', 'page' => '1'), 'default');?>" rel="async"></a>
                <a class="full_view" href="<?php echo $this->MergeUrl($this->urlParams + array('view' => 'full', 'page' => '1'), 'default');?>" rel="async"></a>
            <?php else:?>
                <a class="short_view"></a>
                <a class="full_view"></a>
            <?php endif;?>
        </div>
        <button type="button" class="approve"><?php echo $this->translate('Approve');?></button>
        <button type="button" class="reject"><?php echo $this->translate('Reject');?></button>
    </div>
</div>

<?php // prepare the ajax commands with the current url params
      $this->urlParams['action'] = 'approve';
      $baseApproveUrl = $this->MergeUrl($this->urlParams, 'default');
      $this->urlParams['action'] = 'reject';
      $baseRejectUrl = $this->MergeUrl($this->urlParams, 'default');
?>

<script>
$('#mm_wrap #bulk_actions input#checkall').click(function(){
    if($(this).attr("checked")) {
        $("#pending_media #kitems label.operate .sel-entry").attr("checked", "checked");
        $("#pending_media #kitems li").addClass('selected');
    } 
    else {
        $("#pending_media #kitems label.operate .sel-entry").removeAttr("checked");
        $("#pending_media #kitems li").removeClass('selected');
    }    
});  
    
$('#pending_media #kitems .operate input#sel-entry').live('click', function(){
   if($(this).attr("checked")) {
       $("#pending_media #kitems li[data-entryid="+$(this).val()+"]").addClass("selected");
   } 
   else {
       $("#pending_media #kitems li[data-entryid="+$(this).val()+"]").removeClass("selected");
   }
});

var redirUrl = "<?php echo urlencode($this->MergeUrl());?>";
var baseApproveUrl = "<?php echo $baseApproveUrl;?>";
var baseRejectUrl = "<?php echo $baseRejectUrl;?>";

$("#mm_wrap #bulk_actions button.approve").click(function(){
    var $items = $("#pending_media #kitems label.operate .sel-entry");
    var items = new Array();
    $.each($items, function(index, elem){
        if(($(elem).attr('checked') || $(elem).is('[CHECKED]')) && $(elem).val()) {
            items.push($(elem).val());
        }
    })
    if(items.length) {
    	$('body').addClass('cursorwait');
        var entryIds = items.join(',');
        var url = baseApproveUrl + '/id/' + entryIds + '?format=ajax';
    
        $.getJSON(url, asyncCallback).error( transportError );
    }
});

$("#mm_wrap #bulk_actions button.reject").click(function(){	
    var $items = $("#pending_media #kitems label.operate .sel-entry");
    var items = new Array();
    $.each($items, function(index, elem){
        if(($(elem).attr('checked') || $(elem).is('[CHECKED]')) && $(elem).val()) {
            items.push($(elem).val());
        }
    })
    if(items.length) {
    	$('body').addClass('cursorwait');
        var entryIds = items.join(',');
        var url = baseRejectUrl + '/id/' + entryIds + '?format=ajax';
        
        $.getJSON(url, asyncCallback).error( transportError );
    }
});
</script>
<?php 
