<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
/**
 * Ajax view for channel moderation page
 */

// parse the entries
$this->placeholder('mymedia')->captureStart('SET', 'mymedia');
if ($this->entries && count($this->entries))
{    
    foreach($this->entries as $entry)
    {
        $actions = array();
        $this->urlParams['action'] = 'reject';
        $actions[] = '<a href="'.$this->MergeUrl($this->urlParams + array('id' => $entry->id), 'default').'" rel="async" class="edit_entry"><em></em>'.$this->translate('Reject').'</a>';
        $this->urlParams['action'] = 'approve';
        $actions[] = '<a href="'.$this->MergeUrl($this->urlParams + array('id' => $entry->id), 'default').'" rel="async" class="edit_entry"><em></em>'.$this->translate('Approve').'</a>';
        echo $this->partial('partials/entryItem/detailed.phtml', 
            array(
                'entry' => $entry, 
                'actions' => $actions,
                'itemTag' => 'label'
            )
        );
    }
}
else
{
    echo '<li class="no_items">' . $this->translate("There are no pending entries...") . '</li>';
}
$this->placeholder('mymedia')->captureEnd();

// parse the pager
$pager = $this->paginationControl($this->paginator, $this->pagerType, 'partials/mymedia/myMediaPaging.phtml',array('urlParams' => $this->urlParams));

// bulk actions
$this->urlParams['action'] = 'index';
$this->JsonContent(
array(
        'target' => '#bulk_actions .views_switch',
        'content' => '
        <a class="short_view" href="'.$this->MergeUrl($this->urlParams + array('view' => 'short', 'page' => '1')).'" rel="async"></a>
        <a class="full_view" href="'.$this->MergeUrl($this->urlParams + array('view' => 'full', 'page' => '1')).'" rel="async"></a>
        ',
        'action' => 'replace',
)
);

$this->JsonContent(
array(
        'target' => '#pager',
        'content' => $pager,
        'action' => 'replace'
)
);

$this->JsonContent(
array(
        'target' => '#pending_media #kitems',
        'content' => $this->placeholder('mymedia')->mymedia,
        'action' => 'replace'
)
);


// tags
if(isset($this->params['tag']) && $this->params['tag'])
{ // add a tag next to the header My Media
$this->JsonContent(
array(
        'target' => '.current_tag',
        'content' => '',
        'action' => 'delete',
)
);

$this->JsonContent(
array(
        'target' => '#filter_bar',
        'content' => '<span class="current_tag">'.$this->params['tag'] . '<a href="'.$this->MergeUrl(array('tag' => null)).'" class="closetag" rel="async"></a></span>',
        'action' => 'before',
)
);
}
else // remove the tag
{
    $this->JsonContent(
    array(
            'target' => '.current_tag',
            'content' => '',
            'action' => 'deleteFade'
    )
    );
}

// messages - if exists
if (!empty($this->message)){
    $this->JsonFlashMessage($this->message);
}

$this->JsonScript('$("#mm_wrap #bulk_actions input#checkall").removeAttr("checked")');
$this->JsonScript('$("#mm_wrap").removeClass("short").removeClass("full").addClass("'.$this->itemType.'");');
$this->JsonScript('$("#kitems .item .short_desc[title]").ktooltip({tipclass: "ktooltip-mymedia"});');

// update the base urls for the bulk actions
// user url() and not mergeUrl() because we need to reset the action parameters
$this->params['id'] = null;
$this->urlParams['action'] = 'approve';
$baseApproveUrl = $this->url( array_merge($this->urlParams, $this->params ), 'default',true);
$this->urlParams['action'] = 'reject';
$baseRejectUrl = $this->url( array_merge($this->urlParams, $this->params ), 'default',true);

$this->JsonScript('baseApproveUrl = "'.$baseApproveUrl.'";');
$this->JsonScript('baseRejectUrl = "'.$baseRejectUrl.'";');




