<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

/**
 * Main view of the Channelmoderation module
 * 
 */

$this->headScript()->appendFile($this->baseUrl('build'.BUILD_NUMBER.'/js/ktooltip.js'));

$this->defaultKeyword = $this->translate('Search pending');
?>

<div id="channelmoderation_tab" onshow="$('#embed_code').focus()" class="wrapper">

<h3><?php echo $this->translate('Pending Moderation')?></h3>
<div id="mymedia">
<div id="mm_wrap" class="<?php echo $this->itemType; ?>">    
    <?php if(isset($this->params['tag']) && $this->params['tag']): ?>
        <span class="current_tag"><?php echo $this->params['tag'] ?>
            <a rel="async" href="<?php echo $this->MergeUrl(array('tag' => null));?>" class="closetag"></a>
        </span>
    <?php endif; ?>
    <div id="filter_bar" class="wrapper">
    <?php
		$current_type = null;
		$currentType = $this->params['type'];
		if (empty($currentType)){
			$currentType = 'all';
		}
		
		$filterTypes = $this->FilterBarFilterTypesPreparator($currentType);
        $sorters = $this->FilterBarSortersPreparator($currentType);
        
    echo $this->partial('partials/filterBar.phtml', array(
		'currentType' => $currentType,
		'filterTypes' => $filterTypes,
	    'sorters' => $sorters
	));

    ?>
    </div>
    <?php echo $this->partial('partials/bulkActions.phtml','channelmoderation', $this);?>
    <div id="pending_media" class="wrapper">
        <ul id="kitems">            
        <?php
            if ($this->entries && count($this->entries))
            {
                foreach($this->entries as $entry)
                {
                    $actions = array();
                    $this->urlParams['action'] = 'reject';
                    $actions[] = '<a href="'.$this->MergeUrl($this->urlParams + array('id' => $entry->id), 'default').'" rel="async" class="edit_entry"><em></em>'.$this->translate('Reject').'</a>';
                    $this->urlParams['action'] = 'approve';
                    $actions[] = '<a href="'.$this->MergeUrl($this->urlParams + array('id' => $entry->id), 'default').'" rel="async" class="edit_entry"><em></em>'.$this->translate('Approve').'</a>';
                    echo $this->partial('partials/entryItem/detailed.phtml', 
                            array(
                                'entry' => $entry, 
                                'actions' => $actions,
                                'itemTag' => 'label'
                            )
                    );
                }
            }
            else
            {
                if ($this->channel->moderation){
                    echo '<li class="no_items">' . $this->translate("There are no pending entries...") . '</li>';
                }
                else{
                    echo '<li class="no_items">' . $this->translate("Content moderation is turned off.") . '</li>';
                }
            }
        ?>
        </ul>    
    </div>
    <div id="pager" class="wrapper">
        <?php echo $this->paginationControl($this->paginator, $this->pagerType, 'partials/mymedia/myMediaPaging.phtml', array('urlParams' => $this->urlParams));?>    
    </div>
    <script type="text/javascript" language="javascript">                
        $("#kitems .item .short_desc[title]").ktooltip({tipclass: 'ktooltip-mymedia'});
    </script>
    
</div>
        
</div>
</div>
<?php
