<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
?>
<a class="fright" href="<?php echo $this->url(array('channelname' => $this->channelName, 'channelid' => $this->channelId, 'tab' => 'pending'), 'channelsedit', true); ?>"><?php echo $this->pendingEntriesCount . ' ' .$this->translate('pending media'); ?></a>
<?php 