<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

?>
<li <?php echo $this->tabActive ? 'class="current"' : ''; ?>>
	<?php 
	$channelName = '';
	if (isset($this->channel) && isset($this->channel->name)) {
		$channelName = urlencode(Kms_View_Helper_String::removeSpecialChars($this->channel->name)); 
	}
	?>
    <a href="<?php echo $this->baseUrl('/channels/edit/') . $channelName
    		. '/' . $this->channel->id . '/tab/' . $this->tabName; ?>">
    		<?php echo $this->translate('Pending');?></a>
</li>
