<?php if (count($this->notifications) == 0): ?>
	No templates were found
	<?php return; ?>
<?php endif; ?>
<?php $rowIndex = 0; ?>
<table id="manage-notifications">
	<tr>
		<th>Notification</th>
        <th>Subject</th>
        <th>Body</th>
        <th></th>
	</tr>
	<?php foreach($this->notifications as $systemName => $notificationTemplate): ?>
	<?php if ($systemName == $this->systemNameToNotDuplicate) {continue;} ?>
	<?php $rowIndex++; ?>
    <tr data-id="<?php echo $rowIndex; ?>">
	<?php echo $this->partial('partials/table-row.phtml', array('template' => $notificationTemplate, 'rowIndex' => $rowIndex)); ?>
    </tr>
	<?php endforeach; ?>
	<!-- <script>
	
    $("#bodyText").each(keypress(function() {
  alert("Handler for .keypress() called.");
}));</script>-->
</table>
