<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/
?>
<?php if ($this->error): ?>
<?php $this->errorContent = $this->error; ?>
<?php else: ?>
<?php
	$tableRow = $this->partial('partials/table-row.phtml', array('template' => $this->template, 'rowIndex' => $this->rowIndex));
	//$('').find('').replaceWith('<?php echo $tableRow; ');
	$this->JsonContent(array(
		'target' => '#manage-notifications tr[data-id='.$this->rowIndex.']',
		'content' =>  $tableRow,
		'action' => 'replace'
		)
	);
?>
<?php $this->placeholder('script')->captureStart('SET', 'script'); ?>
<?php $this->placeholder('script')->captureEnd(); ?>
<?php $this->JsonScript($this->placeholder('script')->script); ?>
<?php endif; ?>