<div id="koemei_tab">
<style>
    .koemei_widget .widget_player {
      height: 0 !important;
    }
    .koemei_widget .koemei_video_info {
      display: none !important;
    }
    .koemei_widget .video_info_button {
      display: none !important;
    }
    .koemei_widget .widget_bar {
      display: none !important;
    }
    .koemei_widget input {
      border-radius: 0;
    }
</style>
<script type="text/javascript">
	var kw_entry_id = '<?php echo $this->entry_id; ?>';
	var kw_start_koemei = <?php echo $this->start_koemei; ?>;
	var kw_in_edit = 0;
</script>
<?php if ($this->start_koemei==0) { ?>
	<div class="koemei_info">
    	The automated transcript for this media is not yet available.
    </div>

<?php } else if ($this->allow_edit==1)  { ?>
    <div class="tabActionLinks">
		<a id="show_edit_details" class="btn btn-primary edit_transcript hidden-phone hidden-tablet" href="#"><i class="icon-edit icon-white"></i>Edit transcript</a>
	</div>
<?php } ?>
<div id="koemei_player"></div>

</div>



<div id="pseudo_overlay" class="overlay_new" style="display:none;">
	<div class="pseudo_wrapper">
    	<div id="close_pseudo_widget">&nbsp;</div>
    	<div id="new_player">
        &nbsp;
        </div>
        <div id="new_widget">
        &nbsp;
    	</div>
    </div>

</div>
