<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/
/**
 * Partial view script template for rendering the side bar to the right of My Playlists page main column
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_MYPLAYLISTSSIDE
 */

echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_MYPLAYLISTSSIDE);