<?php $partnerId = Kms_Resource_Client::getUserClient()->getConfig()->partnerId; ?>
    <td><?php echo $this->template->name; ?> <br ><small>(<?php echo $this->template->systemName; ?>)</small></td>
    <td colspan="5"><?php $form = new Emailnotifications_Form_Update(); 
		 	$form->setAction($this->baseUrl('/emailnotifications/index/update/rowindex/'.$this->rowIndex.'/systemname/'.$this->template->systemName)); 
		 	$form->getElement("subText")->setValue($this->template->subject);
		 	$form->getElement("bodyText")->setValue($this->template->body);
		 	echo $form;
		 	?></td>
	<!-- <td><textarea id="SubText"><?php echo $this->template->subject;?></textarea><a href="<?php echo $this->baseUrl('/emailnotifications/index/update/rowindex/'.$this->rowIndex.'/systemname/'.$this->template->systemName."/type/subject" );?>" rel="async">update</a></td>
    <td><textarea id="bodyText"><?php echo $this->template->body;?></textarea><a href="<?php echo $this->baseUrl('/emailnotifications/index/update/rowindex/'.$this->rowIndex.'/systemname/'.$this->template->systemName."/type/body" );?>" rel="async">update</a></td>-->
    <td>
		<?php $hideEnable = false; ?>
		<?php $hideDisable = false; ?>
		<?php if ($this->template->partnerId == $partnerId && $this->template->status == Kaltura_Client_EventNotification_Enum_EventNotificationTemplateStatus::ACTIVE): ?>
		<?php $hideEnable = true; ?>
		<?php else: ?>
		<?php $hideDisable = true; ?>
		<?php endif; ?>
        <button class="button" id="disable-notification" rel="async" href="<?php echo $this->baseUrl('/emailnotifications/index/disable/rowindex/'.$this->rowIndex.'/systemname/'.$this->template->systemName);?>" style="<?php echo $hideDisable ? 'display:none' : '';?>">Disable</button>
        <button class="button" id="enable-notification" rel="async" href="<?php echo $this->baseUrl('/emailnotifications/index/enable/rowindex/'.$this->rowIndex.'/systemname/'.$this->template->systemName);?>" style="<?php echo $hideEnable ? 'display:none' : '';?>">Enable</button>
    </td>
    