<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

/**
 * Edit view for the Channels
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_CHANNELTABLINKS
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_CHANNELTABS
 */

?>
<?php 
$channelName = urlencode(Kms_View_Helper_String::removeSpecialChars($this->channel->name));
$channelUrl = $this->url(array('channelname' => $channelName, 'channelid' => $this->channel->id), 'channelview', true);
?>
<div class="wrapper" id="settings_top">
    <h2 class="fleft"><a href="<?php echo $channelUrl ?>"><?php echo $this->channel->name; ?></a> / <?php echo $this->translate('Settings'); ?></h2>
    <a class="back" href="<?php echo $channelUrl ?>"><?php echo '&lsaquo; ' . $this->translate('Back to channel') ?></a>
</div>
<div id="channel_tabs">
    <ul id="channel_tab_buttons" class="wrapper">
        <?php if (!empty($this->form)): ?>
            <li <?php echo $this->tabActive ? 'class="current"' : ''; ?> >
                <a href="<?php echo $this->baseUrl('/channels/edit/')
                		.( isset($this->channel->name) ? $channelName : '') 
                		. '/' . $this->channel->id; ?>">
                <?php echo $this->translate('Basic'); ?></a>
            </li>
        <?php endif; ?>
        <?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_CHANNELTABLINKS); ?>
    </ul>
    <?php if (!empty($this->form) && $this->tabActive): ?>
        <div id="basic_tab"><?php echo $this->form; ?></div>
    <?php endif; ?>
    <?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_CHANNELTABS); ?>
</div>
<script>
$('#channel_tab_buttons > li > a').click(function(){$('body').addClass('cursorwait')});
</script>
<?php

