<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
/**
 * Main view script for the Channels
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_CHANNEL_SIDENAV
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_PRE_CHANNELS
 */

// search keyword
$this->defaultKeyword = $this->translate('Search').' '.$this->translate('Channels');

// title
$this->headTitle($this->translate('Channels'));

// heading and sidebar
$sidebar = $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_CHANNEL_SIDENAV);
if ($sidebar){
    // sidebar + heading
    $this->placeholder("Side_Bar")->content = $sidebar;
}

if(!$this->ChannelNumber)
{
    $channelsHeading = $this->translate('No Channels');
}
else
{
    $channelsHeading = $this->ChannelNumber . ' ' . ($this->ChannelNumber == 1 ? $this->translate('Channel') : $this->translate('Channels'));
}

$pageheading = (!empty($sidebar)) ? $this->headingOnly($this->translate('Channels'), 'h1', 'inline_heading') : $this->headingOnly($channelsHeading, 'h1', 'inline_heading');
$pageheading .= $this->subHeading('<div>' . $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_PRE_CHANNELS) . '</div>', 'inline_sub_heading');
$pageheading .= $this->partial('partials/channels/createChannel.phtml');
$this->placeholder('pageHeading')->content = $pageheading;
?>

<div id="filter_bar" class="wrapper p_top">
    <?php 
		$current_type = null;
		$currentType = $this->params['type'];
		if (empty($currentType)){
			$currentType = 'all';
		}
		
		$filterTypes = $this->FilterBarFilterTypesPreparator($currentType);
	
		echo $this->partial('partials/filterBar.phtml', array(
			'disableType' => true, 
			'currentType' => $currentType,
			'filterTypes' => $filterTypes,
			'sorters' => array(
                'date' => $this->translate('Date'),
                'name' => $this->translate('Alphabetical'),
                'members' => $this->translate('Members'))
            )
	    	
		);
		?>
</div>
 
<ul id="channels" class="wrapper">        
    <?php 
    foreach ($this->channels as $channel){
        echo $this->partial('partials/channels/channel.phtml', array('channel' => $channel, 'admin' => $this->admin, 'grid_css_class'=> $this->cycle(array('grid_left', 'grid_middle', 'grid_right'))->next()));
    }
    ?>
</ul>

<div id="pager" class="wrapper">
	<?php
	echo $this->paginationControl($this->paginator, $this->pagerType, 'partials/galleryPaging.phtml');
	?>    
</div>
<?php 