<div id="koemei_tab">
<script type="text/javascript">
	kw_entry_id = '<?php echo $this->entry_id; ?>';
	kw_start_koemei = <?php echo $this->start_koemei; ?>;
	kw_in_edit = 0;
</script>
<?php if ($this->start_koemei==0) { ?>
	<div class="koemei_info">
    	No translations found on the Koemei service
    </div>

<?php } else if ($this->alow_edit==1)  { ?>
    <div class="tabActionLinks">
		<a id="show_edit_details" class="edit_transcript" href="#"><em></em>Edit transcript</a>
	</div>

<?php } ?>
<div id="koemei_player"></div>

</div>



<div id="pseudo_overlay" class="overlay_new" style="display:none;">
	<div class="pseudo_wrapper">
    	<div id="close_pseudo_widget">&nbsp;</div>
    	<div id="new_player">
        &nbsp;
        </div>
        <div id="new_widget">
        &nbsp;
    	</div>
    </div>

</div>
