<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
//	include css and js that will go in the page <head>




$this->headLink()->appendStylesheet($this->baseUrl('build' . BUILD_NUMBER . '/koemei/asset/koemei-widget.css'));
$this->headScript()->appendFile($this->baseUrl('build'. BUILD_NUMBER . '/koemei/asset/koemei-widget.js'));

//$this->headLink()->appendStylesheet('//s3.amazonaws.com/static.koemei.com/widget/css/koemei-widget.css');
//$this->headScript()->appendFile('//s3.amazonaws.com/static.koemei.com/widget/javascript/koemei-widget.min.js');

$this->headLink()->appendStylesheet($this->baseUrl('build' . BUILD_NUMBER . '/koemei/asset/koemei-style.css'));
$this->headScript()->appendFile($this->baseUrl('build'. BUILD_NUMBER . '/koemei/asset/koemei-adaptor.js'));
