<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/


    $serviceUrl = Kms_Resource_Config::getConfiguration('client', 'serviceUrl');
    $partnerId = Kms_Resource_Config::getConfiguration('client', 'partnerId');
    $playerId = $this->playerId;
?>
<script type="text/javascript" src="<?php echo $serviceUrl;?>/p/<?php echo $partnerId; ?>/sp/<?php echo $partnerId; ?>00/embedIframeJs/uiconf_id/<?php echo $playerId; ?>/partner_id/<?php echo $partnerId; ?>"></script>