<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

    $flashVarCategoryId = false;
    if(!empty($this->partial()->view->categoryId))
    {
        $flashVarCategoryId = $this->partial()->view->categoryId;
    }

    $ksFlashVar = 'ks=' . Kms_Resource_Client::generateSession(Kaltura_Client_Enum_SessionType::USER, Kms_Resource_Client::DEFAULT_KS_EXPIRY, "sview:" . $this->entryId);
    $serviceUrl = Kms_Resource_Config::getConfiguration('client', 'serviceUrl');
    $partnerId = Kms_Resource_Config::getConfiguration('client', 'partnerId');
    $playerId = Kms_Resource_Config::getConfiguration('player', 'playerId');
    $autoPlayOnLoad = Kms_Resource_Config::getConfiguration('player', 'autoPlayOnLoad');
    $playback = Kms_Resource_Config::getConfiguration('player', 'playback');
    $rtmpUrl = Kms_Resource_Config::getConfiguration('widgets', 'rtmpUrl');
    $enableCapture = isset($this->edit) && $this->edit;
    $enableFlagging = isset($this->edit) && $this->edit;
    $disableExpand = isset($this->edit) && $this->edit;
    
    $moderationReasons = array('reasonSex', 'reasonViolence', 'reasonHarmful', 'reasonSpam');
    $moderationTextsArr = array();
    $moderationTexts = '';
    foreach($moderationReasons as $reason)
    {
        $reasonConfig = Kms_Resource_Config::getConfiguration('moderation', $reason);
        if($reasonConfig)
        {
            $moderationTextsArr[] = 'moderation.'.$reason.'='.urlencode($reasonConfig);
        }
       
    }
    $moderationTexts = join('&', $moderationTextsArr);
    
    if($enableCapture)
    {
        $enableThumbCapture = join('&', 
            array
            (
                'captureThumbBtnControllerScreen.visible=true',
                'captureThumbBtnControllerScreen.includeInLayout=true',
                'captureThumbBtnStartScreen.visible=true',
                'captureThumbBtnStartScreen.includeInLayout=true',
                'captureThumbBtnPauseScreen.visible=true',
                'captureThumbBtnPauseScreen.includeInLayout=true',
                'captureThumbBtnPlayScreen.visible=true',
                'captureThumbBtnPlayScreen.includeInLayout=true',
                'captureThumbBtnEndScreen.visible=true',
                'captureThumbBtnEndScreen.includeInLayout=true',
            )
        );
    }
    else
    {
        $enableThumbCapture = 'captureThumbnail.disableHTML5=true';
    }
    
    if($enableFlagging)
    {
        $enableFlaggingVars = join('&', 
            array
            (
                'flagBtnControllerScreen.visible=false',
                'flagBtnControllerScreen.includeInLayout=false',
                'flagBtnStartScreen.visible=false',
                'flagBtnStartScreen.includeInLayout=false',
                'flagBtnPauseScreen.visible=false',
                'flagBtnPauseScreen.includeInLayout=false',
                'flagBtnEndScreen.visible=false',
                'flagBtnEndScreen.includeInLayout=false',
            )
        );
    }
    else
    {
        $enableFlaggingVars = '';
    }
?>
<!-- html5 fallback library -->
<?php echo $this->partial('partials/widgets/html5Fallback.phtml', array('playerId' => $playerId)); ?>
<!-- kdp embed -->
<object id="kplayer" name="kplayer" type="application/x-shockwave-flash" rel="media:video" resource="<?php echo $serviceUrl; ?>/index.php/kwidget/wid/_<?php echo $partnerId ?>/uiconf_id/<?php echo $playerId; ?>"
        allowFullScreen="true" allowNetworking="all" wmode="transparent" allowScriptAccess="always" height="100%" width="100%"
        xmlns:media="http://search.yahoo.com/searchmonkey/media/" xmlns:dc="http://purl.org/dc/terms/"
        data="<?php echo $serviceUrl ?>/index.php/kwidget/wid/_<?php echo $partnerId; ?>/uiconf_id/<?php echo $playerId; ?><?php echo $this->entryId ? '/entry_id/'.$this->entryId : '' ?>">
    <param name="allowFullScreen" value="true" />
    <param name="allowNetworking" value="all" />
    <param name="allowScriptAccess" value="always" />
    <param name="bgcolor" value="#000000" />
    <param name="wmode" value="transparent" />
    <param name="flashVars" value="<?php echo $ksFlashVar; ?>&applicationName=<?php echo Kms_Resource_Config::getConfiguration('application', 'instanceId'); ?><?php echo $flashVarCategoryId ? '&playbackContext='.$flashVarCategoryId : ''; ?>&disableAlerts=false&externalInterfaceDisabled=false&<?php echo $enableThumbCapture; ?>&<?php echo $enableFlaggingVars; ?>&<?php echo $moderationTexts;?>&autoPlay=<?php echo $autoPlayOnLoad ? 'true' : 'false' ?><?php if($playback == 'RTMP') { ?>&streamerType=rtmp&streamerUrl=<?php echo $rtmpUrl; ?>&rtmpFlavors=1<?php } ?><?php if($disableExpand) { ?>&expandToggleBtn.visible=false&expandToggleBtn.includeInLayout=false<?php } ?>" />
    <param name="movie" value="<?php echo $serviceUrl; ?>/index.php/kwidget/wid/_<?php echo $partnerId; ?>/uiconf_id/<?php echo $playerId; ?>/<?php echo $this->entryId ? '/entry_id/'.$this->entryId : '' ?>" />
</object>
<script>
// script for KDP callbacks
var autoLoadEntry = true;
var playerLoaded = false;
    
jsCallbackReady = function (playerId) {
    kdp = document.getElementById(playerId);
    var isEmpty = (kdp) ? kdp.evaluate("{playerStatusProxy.kdpStatus}") : false;
    
    try{
        if(isEmpty) {
            playerReady();
        }
        else {
            kdp.addJsListener("kdpEmpty", "playerReady");
            kdp.addJsListener("kdpReady", "playerReady");
            kdp.addJsListener("entryFailed", "jsCallbackFailed");
        }
    } catch(e) {
        jsLog(e);
    }
}

jsCallbackFailed = function (e) {
    jsLog('Entry Failed callback from KDP: ' + e);
}

kmh = {};
/**
 * @todo change uiconfs expandShrinkPlayer callback not to call kmh
 * 
 */
kmh.expandShrinkPlayer = function(entryId) {
	// enlarge or shrink the player
        $("#content").toggleClass("bigPlayer");
}

function playerReady()
{
    if(playerLoaded == false) {
        jsLog('KDP player Ready');
        if(debug) {
            var end = new Date().getTime();
            var time = end - start;
            jsLog('KDP load time: ' + time +'ms');            
        }
        playerLoaded = true;
    }
}
// end script for KDP callbacks

</script>