<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

    $cacheSt = time() - (60 * 60);
    $ksFlashVar = 'ks=' . Kms_Resource_Client::getUserClient()->getKs() . "&";
    $serviceUrl = Kms_Resource_Config::getConfiguration('client', 'serviceUrl');
    $partnerId = Kms_Resource_Config::getConfiguration('client', 'partnerId');
    $kpwId = Kms_Resource_Config::getConfiguration('player', 'kpwId');
    $autoPlayOnLoad = Kms_Resource_Config::getConfiguration('player', 'autoPlayOnLoad');
    $playback = Kms_Resource_Config::getConfiguration('player', 'playback');
    $rtmpUrl = Kms_Resource_Config::getConfiguration('widgets', 'rtmpUrl');
    $editMode = isset($this->edit) && $this->edit ? 'true' : 'false';
?>  
<!-- html5 fallback library -->
<?php echo $this->partial('partials/widgets/html5Fallback.phtml', array('playerId' => $kpwId)); ?>
<!-- kdp embed -->
<object id="kpwplayer" name="kpwplayer" type="application/x-shockwave-flash" allowFullScreen="true" allowNetworking="all" allowScriptAccess="always" height="100%" width="100%" bgcolor="#000000" 
        data="<?php echo $serviceUrl; ?>/index.php/kwidget/wid/_<?php echo $partnerId; ?>/uiconf_id/<?php echo $kpwId; ?>" wmode="transparent">
    <param name="allowFullScreen" value="true" />
    <param name="allowNetworking" value="all" />
    <param name="allowScriptAccess" value="always" />
    <param name="bgcolor" value="#000000" />
    <param name="wmode" value="transparent" />
    <param name="movie"	value="<?php echo $serviceUrl; ?>/index.php/kwidget/cache_st/<?php echo $cacheSt; ?>/wid/_<?php echo $partnerId; ?>/uiconf_id/<?php echo $kpwId; ?>" />
    <param name="flashVars" 
           value="videoPresentationEntryId=<?php echo $this->entryId; ?>&jsCallBackReadyFunc=jsDocumentPlayerReady&strings.ENTRY_REJECTED_TITLE=Video%20Cannot%20Be%20Presented&speakerNameContainer.visible=false&speakerNameContainer.includeInLayout=false&pptWidgetClose.visible=false&pptWidgetClose.includeInLayout=false&carouselVisible=true&externalInterfaceDisabled=false&<?php echo $ksFlashVar ?>&editMode=<?php echo $editMode;?>&autoPlay=<?php echo $autoPlayOnLoad ? 'true' : 'false'; ?><?php if($playback == 'RTMP') { ?>&streamerType=rtmp&streamerUrl=<?php echo $rtmpUrl; ?>&rtmpFlavors=1<?php }?>" />
</object>
<script>
// start script for KPW callbacks
var autoLoadEntry = true;
var kpwLoaded = false;

function jsDocumentPlayerReady(player_id) {
    kpw = document.getElementById(player_id);
    if(kpw) {
        var ready = kpw.evaluate("{playerStatusProxy.kdpStatus}");
        if(ready) {
            kpwReady();
        } else {
            kpw.addJsListener("layoutReady", "kpwReady");
//            kpw.addJsListener("playerPlayed", "hideGallery");
        }
    }
        
}

function kpwReady()
{
    if(kpwLoaded == false) {
        jsLog('Presentations player Ready');
        kpwLoaded = true;
        //kpw.sendNotification('changeVideoPresentation', {entryId: '<?php echo $this->entryId; ?>'});
    }
}

// add js to check if height of side nav is higher than height of kgallery, then compact it
if($("div.side_nav").height() > $("#content").height() - $("#player_block").height()) {
    $("#player_block").addClass("compact");
}


// end script for KPW callbacks
</script>