<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/


$movieUrl = Kms_Resource_Config::getConfiguration('client', 'serviceUrl') . '/krecord/ui_conf_id/' . Kms_Resource_Config::getConfiguration('widgets', 'krecordId');
$kalturaHostNoHttp = preg_replace('#http[s]?://#', '', Kms_Resource_Config::getConfiguration('client', 'serviceUrl'));
$flashvars = join('&', array(
    'showUi=true',
    'uid=' . $this->partial()->view->userId,
    'partnerId=' . $this->partial()->view->partnerId,
    'ks=' . $this->partial()->view->ks,
    'entryId=-1',
    'jsDelegate=krecordHandler',
    'limitRecord=0',
    'showPreviewTimer=true',
    '&kshowId=-1',
    'httpprotocol=http',
    'host=' .$kalturaHostNoHttp,
    'rtmpHost='.Kms_Resource_Config::getConfiguration('widgets', 'rtmpUrl'),
    'localeUrl='.Kms_Resource_Config::getConfiguration('client', 'serviceUrl').'/flash/krecord/v1.5.13/locale.xml',
    'themeUrl='.Kms_Resource_Config::getConfiguration('client', 'serviceUrl').'/flash/krecord/v1.5.13/skin.swf',
    
));

?>
<object 
    type="application/x-shockwave-flash" 
    pluginspage="http://www.adobe.com/go/getflashplayer"
    data="<?php echo $movieUrl ?>" 
    id="krecord" width="100%" height="100%">
    <param name="allowScriptAccess" value="always" />
    <param name="allowNetworking" value="all" />
    <param name="wmode" value="window" />
    <param name="flashvars" value="<?php echo $flashvars; ?>" />
    <param name="movie" value="<?php echo $movieUrl ?>" />
</object>
