<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
?>

<?php if (!$this->allowSubscribeToChannel): ?>
	<?php return; ?>
<?php endif; ?>

<?php $hideUnsubscribe = $this->isUserSubscribed ? false : 'style="display:none;"'; ?>
<?php $hideSubscribe = $this->isUserSubscribed ? 'style="display:none;"' : false; ?>

<?php $url = $this->baseUrl('/channelsubscription/index/subscribe/channelid/' . $this->channelId);?>
<a class="btn" data-timeout="120" id="subscribe" href="<?php echo $url; ?>" rel="async" <?php echo $hideSubscribe; ?>><?php echo $this->translate('Subscribe'); ?></a>
<?php $url = $this->baseUrl('/channelsubscription/index/unsubscribe/channelid/' . $this->channelId);?>
<a class="btn" data-timeout="120" id="unsubscribe" href="<?php echo $url; ?>" rel="async" <?php echo $hideUnsubscribe; ?>><?php echo $this->translate('Unsubscribe'); ?></a>

<style type="text/css">
    #gallerybuttons { top: 0; padding: 12px 8px; }
	#gallerybuttons #add_media { width: 105px; float: right; text-align: center; }
    #gallerybuttons #channelSettings { float: left; margin-right: 13px; line-height: 70px; vertical-align: middle; }
    #gallerybuttons #subscribe,
    #gallerybuttons #unsubscribe { width: 105px; clear: right; float: right; margin-top: 5px; text-align: center;  }
    #gallerybuttons .btn { line-height: 31px;  }
    #gallerybuttons #add_media .icon { height: auto; background-position: -5px -33px; }
</style>