<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/
?>
<?php if ($this->error): ?>
	<?php $this->errorContent = $this->error; ?>
<?php else: ?>
	<?php $this->placeholder('script')->captureStart('SET', 'script'); ?>
	$('#subscribe').hide();
	$('#unsubscribe').show();
	<?php $this->placeholder('script')->captureEnd(); ?>
	<?php $this->JsonScript($this->placeholder('script')->script); ?>
<?php endif; ?>