<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/
$this->placeholder('script')->captureStart('SET', 'script');
?>
$('#unsubscribe').hide();
$('#subscribe').show();
<?php
$this->placeholder('script')->captureEnd();
$this->JsonScript($this->placeholder('script')->script);