<script type="text/javascript">
	var kw_entry_id = '<?php echo $this->entry_id; ?>';
	var kw_start_koemei = 0;
	var kw_in_edit = 1;
</script>
<div id="pseudo_overlay" class="overlay_new" style="display:none;">
	<div class="pseudo_wrapper">
    	<div id="close_pseudo_widget_edit">&nbsp;</div>
    	<div id="new_player">
        &nbsp;
        </div>
        <div id="new_widget">
        &nbsp;
    	</div>
    </div>

</div>
