<?php
/*
 * Copyright ©2013 Koemei SA
 * @author Tra!an
 */

//	include css and js that will go in the page <head>

//load widget resources



$protocol = ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') ? 'https' : 'http');
$this->headLink()->appendStylesheet("$protocol://s3.amazonaws.com/static.koemei.com/widget/css/koemei-widget.css");
$this->headScript()->appendFile("$protocol://s3.amazonaws.com/static.koemei.com/widget/javascript/koemei-widget.min.js");



//load custom CSS/JS
$this->moduleHeadLink()->appendStylesheet('koemei', 'koemei-style.css');
$this->moduleHeadScript()->appendFile('koemei', 'koemei-adaptor.js');