<?php
/*
 * Copyright ©2013 Koemei SA
 * @author Tra!an
 */

//	include css and js that will go in the page <head>

//load widget resources
$this->headLink()->appendStylesheet('koemei', '//s3.amazonaws.com/static.koemei.com/widget/css/koemei-widget.css');
$this->headScript()->appendFile('koemei', '//s3.amazonaws.com/static.koemei.com/widget/javascript/koemei-widget.min.js');

//load custom CSS/JS
$this->headLink()->appendStylesheet('koemei', $this->baseUrl('build' . BUILD_NUMBER . '/koemei/asset/koemei-style.css'));
$this->headScript()->appendFile('koemei', $this->baseUrl('build'. BUILD_NUMBER . '/koemei/asset/koemei-adaptor.js'));