<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/


    if($this->partnerAccess)
    {
        echo $this->action('login', 'admin', null, array('ref' => $this->ref, 'format' => $this->format ));
    }
    else
    {
        echo $this->action('login', 'user', null, array('ref' => $this->ref, 'format' => $this->format )); 
    }
?>