<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/


$this->placeholder('script')->captureStart('SET', 'script'); ?>

if($('#dialog')) {
    $("body").append('<div id="dialog"></div>');
}
$("#dialog").dialog('close');

$("#dialog").html("<?php echo str_replace(array("\r\n", "\n", "\r"), '', addslashes($this->form)) ?>");

        <?php 
            $this->dialogContainer(
                'dialog',
                $this->form,
                array(
                    'autoOpen'      => true,
                    'draggable'     => false,
                    'modal'         => true,
                    'resizable'     => false,
                    'title'         => $this->translate('Please Login'),
                    'closeOnEscape' => true,
                    'close' => new Zend_Json_Expr('function() {
                        $("#dialog").remove();
                    }'),
                    'buttons'   => array(
                        $this->translate('Login') =>  new Zend_Json_Expr('function() {
                            $("#loginForm").submit();
                           
                        }'),
                    ),
             )
            );

    $actions = $this->JQuery()->getOnLoadActions();

    $this->JQuery()->disable();

    foreach($actions as $action)
    {
        echo $action;
    }
$this->placeholder('script')->captureEnd(); 
$this->JsonScript($this->placeholder('script')->script);