<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/
/**
 * Ajax view for my-media page
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_PREMYMEDIAENTRIES
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_POSTMYMEDIAENTRIES
 */

$this->placeholder('mymedia')->captureStart('SET', 'mymedia');
echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_PREMYMEDIAENTRIES);

if ($this->entries && count($this->entries))
{
    foreach($this->entries as $entry)
    {
        $actions = array('<a href="'.$this->baseUrl('edit/'.$entry->id).'" class="edit_entry"><em></em>'.$this->translate('Edit').'</a>');
        // check for modules handling this entry type and overriding the editable property.
        if ($this->isEntryEditable($entry) === false) {
            $actions = array();
        }

        echo $this->partial('partials/entryItem/detailed.phtml', 
                array(
                    'entry' => $entry, 
                    'actions' => $actions,
                    'itemTag' => 'label',
                    'showPublish' => true,
                )
        );
    }
}
else
{
    echo $this->translate("No media found").'.';
}
echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_POSTMYMEDIAENTRIES);
$this->placeholder('mymedia')->captureEnd();


$pager = $this->paginationControl($this->paginator, $this->pagerType, 'partials/mymedia/myMediaPaging.phtml');
$pagesInfo = $this->partial()->view->paginator->getPages();


$this->JsonContent(
        array(
            'target' => '#bulk_actions .views_switch',
            'content' => '
            <a class="short_view" href="'.$this->MergeUrl(array('view' => 'short', 'page' => '1')).'" rel="async"></a>
            <a class="full_view" href="'.$this->MergeUrl(array('view' => 'full', 'page' => '1')).'" rel="async"></a>
                ',
            'action' => 'replace',
        )
);

$this->JsonContent(
        array(
            'target' => '#pager',
            'content' => $pager,
            'action' => 'replace'
        )
);
$this->JsonContent(
        array(
            'target' => '#mymedia #kitems',
            'content' => $this->placeholder('mymedia')->mymedia,
            'action' => 'replace'
        )
);
$this->JsonContent(
    array(
        'target' => '#result_counter',
        'content' => $pagesInfo->firstItemNumber . '-' . $pagesInfo->lastItemNumber . ' '.$this->translate('of').' ' . $pagesInfo->totalItemCount . ' '.$this->translate('items'),
        'action' => 'replace'
    )
);

// tags
if(isset($this->params['tag']) && $this->params['tag'])
{ // add a tag next to the header My Media
    $this->JsonContent(
        array(
            'target' => '.current_tag',
            'content' => '',
            'action' => 'delete',
        )
    );
    $this->JsonContent(
        array(
            'target' => '.heading',
            'content' => '<span class="current_tag">'.$this->params['tag'] . '<a href="'.$this->MergeUrl(array('tag' => null)).'" class="closetag" rel="async"></a></span>',
            'action' => 'append',
        )
    );
}
else // remove the tag
{
    $this->JsonContent(
        array(
            'target' => '.current_tag',
            'content' => '',
            'action' => 'deleteFade'
        )
    );

}

$this->JsonScript('$("#mm_wrap").removeClass("short").removeClass("full").addClass("'.$this->itemType.'");');
$this->JsonScript('$("#kitems .item .short_desc[title]").ktooltip({tipclass: "ktooltip-mymedia"});');
$this->JsonScript('redirUrl = "'.urlencode($this->MergeUrl()).'";');
