<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/
/**
 * Main view script for my-media page
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_PREMYMEDIAENTRIES
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_POSTMYMEDIAENTRIES
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_PREMYMEDIA
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_POSTMYMEDIA
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_MYMEDIASIDEBARPRE
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_MYMEDIASIDEBARPOST
 */

$this->headTitle($this->translate('My Media')); 

$this->headScript()->appendFile($this->baseUrl('build'.BUILD_NUMBER.'/js/ktooltip.js'));


$this->placeholder('pageHeading')->captureStart('SET', 'content');
//    echo $this->HeadingOnly($this->translate('Add New'), 'h2', 'inline_heading');
    echo $this->HeadingOnly($this->translate('My Media'), 'h1', 'heading mmheading');

    if(isset($this->params['tag']) && $this->params['tag']): ?>
        <span class="current_tag"><?php echo $this->params['tag'] ?>
            <a rel="async" href="<?php echo $this->MergeUrl(array('tag' => null));?>" class="closetag"></a>
        </span>
    <?php endif;

$this->placeholder('pageHeading')->captureEnd('SET', 'content');

/* wrap the html and assign to Side_Bar placeholder */
$this->placeholder('Side_Bar')->captureStart('SET', 'content');
?>
    <ul class="sidebar_addmedia">
        <?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_MYMEDIASIDEBARPRE); ?>                
        <?php if ($this->mediaUpload): ?>
            <li>
                <a class="btn" rel="require-flash" href="<?php echo $this->baseUrl('/upload'); ?>" id="open_upload"><em></em><span><?php echo $this->translate('Media Upload'); ?></span></a>
            </li>
        <?php endif; ?>
        <?php if ($this->webcamUpload): ?>
        <li>
            <a class="btn" rel="require-flash" href="<?php echo $this->baseUrl('/upload/webcam'); ?>" id="launch_webcam_kcw"><em></em><span><?php echo $this->translate('Webcam Recording'); ?></span></a>
        </li>
        <?php endif; ?>
        <?php if ($this->presentationUpload): ?>
        <li>
            <a class="btn" rel="require-flash" href="<?php echo $this->baseUrl('/upload/presentation'); ?>" id="launch_kpw_wizard" ><em></em><span><?php echo $this->translate('Video Presentation'); ?></span></a>
        </li>
        <?php endif; ?>
        <?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_MYMEDIASIDEBARPOST); ?>                
    </ul>
<?php $this->placeholder('Side_Bar')->captureEnd(); /* end sidebar */ ?>

<div id="mm_wrap" class="<?php echo $this->itemType; ?>">
<?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_PREMYMEDIA); ?>                
<div id="filter_bar" class="wrapper">
<?php
	$current_type = null;
	$currentType = $this->params['type'];
	if (empty($currentType))
	{
		$currentType = 'all';
	}
	$sorters = $this->FilterBarSortersPreparator($currentType);
	$filterTypes = $this->FilterBarFilterTypesPreparator($currentType);

	echo $this->partial('partials/filterBar.phtml', array(
		'currentType' => $currentType,
		'filterTypes' => $filterTypes,
		'sorters' => $sorters,
		'showAdditionalSearches' => true
	));
?>
</div>
<?php
echo $this->partial('partials/mymedia/bulkActions.phtml');
?>
<div id="mymedia" class="wrapper">
    <ul id="kitems">
    <?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_PREMYMEDIAENTRIES);
if ($this->entries && count($this->entries))
{
    foreach($this->entries as $entry)
    {
        $actions = array('<a href="'.$this->baseUrl('edit/'.$entry->id).'" class="edit_entry"><em></em>'.$this->translate('Edit').'</a>');
        // check for modules handling this entry type and overriding the editable property.
        if ($this->isEntryEditable($entry) === false) {
            $actions = array();
        }

        echo $this->partial('partials/entryItem/detailed.phtml', 
                array(
                    'entry' => $entry, 
                    'actions' => $actions,
                    'itemTag' => 'label',
                	'showPublish' => true,
                )
        );
    }
}
else
{
    echo '<li class="no_items">' . $this->translate("No media found") . '.</li>';
}
?>
    <?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_POSTMYMEDIAENTRIES); ?>                
    </ul>    
</div>
<div id="pager" class="wrapper"><?php
    echo $this->paginationControl($this->paginator, $this->pagerType, 'partials/mymedia/myMediaPaging.phtml');
    ?></div>
<script type="text/javascript" language="javascript">                
    $("#kitems .item .short_desc[title]").ktooltip({tipclass: 'ktooltip-mymedia'});
</script>
<?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_POSTMYMEDIA); ?>                
</div>