<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/
/**
 * View script for the main action of My Playlists
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_PREMYPLAYLISTSENTRIES
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_POSTMYPLAYLISTSENTRIES
 */

$this->headScript()->appendFile($this->baseUrl('build'.BUILD_NUMBER.'/js/ktooltip.js'));


$this->headTitle($this->translate('My Playlists')); 
?>
<!--<h1><?php echo $this->translate('My Playlists'); ?></h1>-->
<?php $pageheading = $this->headingOnly($this->translate('My Playlists'), 'h1', 'heading long');
	$pageheading .= $this->subHeading($this->translate('Drag and drop to reorder media'));
	$this->placeholder('pageHeading')->content = $pageheading;
	?>
<div id="mp_wrap" class="<?php echo $this->itemType; ?>">
    <?php
    echo $this->partial('partials/myplaylists/actionBar.phtml', array('playlists' => $this->playlists));
    ?>
    <div id="myplaylists">

        <ul id="kitems">
        <?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_PREMYPLAYLISTSENTRIES); ?>
            <?php
            foreach ($this->entries as $entry) {
                echo $this->partial('partials/entryItem/detailed.phtml', array(
                        'entry' => $entry,
                        'actions' => array(
                            '<a class="remove" data-entryid="' . $entry->id . '"><em></em>'.$this->translate('Remove').'</a>'
                        ),
                        'disableCheckbox' => true,
                        'itemTag' => 'div',
                        'tagUrl' => $this->baseUrl('/tag/%tag%'),
                        'tagRel' => '',
                    )
                );
            }
            ?>
        <?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_POSTMYPLAYLISTSENTRIES); ?>
        </ul>    
    </div>
<?php
echo $this->partial('partials/myplaylists/actionBarBottom.phtml', array('playlists' => $this->playlists));
?>
</div>
<script type="text/javascript" language="javascript">                
    $("#kitems .item .short_desc[title]").ktooltip({tipclass: 'ktooltip-mymedia'});
</script>

<div id="mp_side">
<?php echo $this->partial('partials/myplaylists/sideBar.phtml'); ?>
</div>
