<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

?>
    <li>
      <a href="<?php echo $this->EntryLink($this->id, $this->name); ?>"  >
        <img src="<?php echo $this->thumbnailUrl; ?>/width/96/height/54/type/<?php echo Kaltura_Client_Enum_ThumbCropType::CROP;?>" height="54" width="96" alt="<?php echo $this->escape($this->name); ?>">
        <em></em><!-- for play icon overlay; @todo:replace div-->
        <span><?php echo $this->escape($this->name) ?></span>
        <span class="duration"><?php echo $this->String()->formatDuration($this->duration); ?></span>
      </a>
    </li>