<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

// add the walkmethru js to the footer. i have used direct script and not the scriptFooter view helper,
// bacause the attribute async=true is giving me trouble.
?>
<script language='javascript' async='true' type='text/javascript' src='<?php echo $this->script; ?>'></script> 