<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
?>
<?php $this->showEntryLinks = false; ?>

<div id="player_wrap" class="wrapper webcast">
	<div class="wrapper entry_heading">
		<h1 id="ktitle"><?php echo $this->escape($this->entry->name) ?></h1>
	</div>

	<?php if (!Kms_Plugin_Access::isLoggedIn()): ?>
		<a class="btn" href="<?php echo $this->buttonGuestUrl; ?>" target='_blank'><?php echo $this->buttonText; ?></a>
	<?php else: ?>
		<a class="btn" href="<?php echo $this->baseUrl('webcast/sso/redirect/entryId/' . $this->entry->id); ?>" target='_blank'><?php echo $this->buttonText; ?></a>			
	<?php endif;?>

	<?php echo $this->partial('partials/playerData.phtml', $this->entry); ?>

</div>
<?php 