<?php
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @ignore
 */
$this->placeholder('interface')->captureStart('SET', 'interface');
?>


<div class="interfaceMethods">
    <?php if (is_array($this->interfaceInfo['constants']) && count($this->interfaceInfo['constants'])): ?>
        <div class="interfaceConstants">
            <h3>Constants</h3>
            <table cellspacing="0">
                <tr>
                    <th class="name">Name</th><th>Value</th>
                </tr>
		<?php foreach ($this->interfaceInfo['constants'] as $constName => $constValue): ?>
	            <tr class="<?php echo $this->cycle(array('odd', 'even'))->next(); ?>">
	                <td><?php echo $constName; ?></td>
	                <td><?php echo $constValue; ?></td>
	            </tr>
		<?php endforeach; ?>
            </table>
        </div>
    <?php endif; ?>
    <h3>Methods</h3>
    <?php foreach ($this->interfaceInfo['methods'] as $methodName => $details): ?>
        <div class="cf">
    	<div class="methodName"><?php echo $methodName; ?>()</div>
    	<div>
		<?php foreach ($details as $key => $val): ?>
		    <?php if (!is_array($val)): ?>
	    	    <p>
			    <?php if ($key != 'description'): ?>
				<span class="methodDescriptioncKey"><?php echo $key; ?></span>
			    <?php endif; ?>
			    <?php echo str_replace(PHP_EOL, '<br />', $val); ?></p>

		    <?php elseif (count($val)): ?>
	    	    <div class="<?php echo $key; ?>">
	    		<h4><?php echo $key; ?></h4>
			    <?php foreach ($val as $valKey => $valVal): ?>
				<p>
				    <span class="methodValKey"><?php echo $valKey; ?></span>
				    <?php echo $valVal; ?>
				</p>
			    <?php endforeach; ?>
	    	    </div>
		    <?php endif; ?>
		<?php endforeach; ?>
    	</div>
        </div>
    <?php endforeach; ?>
</div>
<a href="#" onclick="$('#<?php echo $this->target; ?>').html('');" class="closeBtn"><span>close</span></a>
<?php
$this->placeholder('interface')->captureEnd();
$this->JsonContent(
	array(
	    'target' => '#' . $this->target,
	    'content' => $this->placeholder('interface')->interface,
	    'action' => 'replace'
	)
);
?>