<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * @ignore
 */

echo $this->partial('partials/kb/sideNav.phtml');
?>
<div class="tabContent">
    <?php foreach($this->interfaces as $name => $description): ?>
    <div class="tabItem interfaces">
        <dt class="interfaceName"><a rel="async" href="<?php echo $this->baseUrl('/kb/interface-info/interface/'.$name); ?>"><?php echo $name; ?></a></dt>
        <dd class="description"><?php echo str_replace(PHP_EOL, '<br />', $description); ?></dd>
        <div class="interfaceContainer" id="<?php echo $name; ?>"></div>
    </div>
    <?php endforeach; ?>
</div>