<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * @ignore
 */

echo $this->partial('partials/kb/sideNav.phtml');
?>
<div class="tabContent">
    <h1>Interface: <?php echo $this->interfaceInfo['name']; ?></h1>
    <div class="interfaceDescription"><?php echo $this->interfaceInfo['description']; ?></div>
    <?php if(is_array($this->interfaceInfo['constants']) && count($this->interfaceInfo['constants'])): ?>
    <div class="interfaceConstants">
        <h3>Constants</h3>
        <table cellspacing="0">
            <tr>
                <th>Name</th><th>Value</th>
            </tr>
            <?php foreach($this->interfaceInfo['constants'] as $constName => $constValue): ?>
            <tr class="<?php echo $this->cycle(array('odd','even'))->next(); ?>">
                <td><?php echo $constName; ?></td>
                <td><?php echo $constValue; ?></td>
            </tr>
            <?php endforeach; ?>
        </table>
    </div>
    <?php endif; ?>
    <div class="interfaceMethods">
        <h3>Methods</h3>
        <?php foreach($this->interfaceInfo['methods'] as $methodName => $details): ?>
        <div class="tabItem">
            <div class="methodName"><?php echo $methodName; ?></div>
            <div>
                <?php foreach($details as $key =>$val): ?>
                    <?php   if(!is_array($val)): ?>
                    <p>
			<?php if ($key != 'description'):?>
			    <span class="methodDesriptioncKey"><?php echo $key; ?></span><?php echo $val; ?></p>
			<?php endif;?>
                    <?php elseif(count($val) > 0): ?>
                      <div class="<?php echo $key; ?>">
                          <h4><?php echo $key; ?></h4>
                          <?php foreach($val as $valKey => $valVal): ?>
                          <p><span class="methodValKey"><?php echo $valKey; ?></span><?php echo $valVal; ?></p>
                          <?php endforeach; ?>
                      </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
</div>