<?php
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * @ignore
 */

echo $this->partial('partials/kb/sideNav.phtml');
?>
<div class="tabContent">
    <h3 class="toggler"><?php echo $this->translate('Core');?></h3>
    <div style="display: none;">
	<p><?php echo $this->translate('View hooks declared by core views of mediaspace.');?></p>
	<?php foreach ($this->viewhooks['core'] as $name => $viewhook): ?>
    	<div class="tabItem">
            <a name="<?php echo $name;?>"></a>
    	    <span class="viewhookName"><?php echo $name; ?></span> - <?php echo $viewhook['description']; ?>
		<?php if (count($viewhook['viewfiles'])): ?>
                    <p></p>
		    <table cellspacing="0">
				<tr>
				    <th class="name"><nobr><?php echo $this->translate('View Files Implementing');?> <?php echo $name ?></nobr></th>
				</tr>
		    <?php foreach ($viewhook['viewfiles'] as $viewfile): ?>
	    	    <tr class="<?php echo $this->cycle(array('odd', 'even'))->next(); ?>">
                        <td><a href="<?php echo $this->baseUrl('kb/viewfiles#'.preg_replace('/\.|\//', '_', $viewfile)); ?>"><?php echo $viewfile;?></a></td>
	    	    </tr>
		    <?php endforeach; ?>
		    </table>
		<?php endif; ?>
    	</div>
	<?php endforeach; ?>
    </div>
    <h3 class="toggler"><?php echo $this->translate('Modules');?></h3>
    <div>
	<p><?php echo $this->translate('View hooks declared in different modules that wish to let other modules extend their output');?></p>
	<?php 
        if(isset($this->viewhooks) && isset($this->viewhooks['modules']) && is_array($this->viewhooks['modules'])):
            foreach ($this->viewhooks['modules'] as $module => $viewhooks): ?>
            <div class="tabItem">
                <div class="moduleName"><h4><?php echo $module; ?></h4></div>
                    <?php foreach ($viewhooks as $name => $viewhook): ?>
                        <span class="viewhookName"><?php echo $name; ?></span> - <?php echo $viewhook['description']; ?>
                        <?php if (count($viewhook['viewfiles'])): ?>
                            <?php if (isset($viewhook['viewfiles'])): ?>
                                <table cellspacing="0">
                                    <tr>
                                        <th class="name"><nobr><?php echo $this->translate('View Files Implementing');?> <?php echo $name ?></nobr></th>
                                    </tr>
                                    <?php foreach ($viewhook['viewfiles'] as $viewfile): ?>
                                    <tr>
                                        <td class="viewhookName"><a href="<?php echo $this->baseUrl('kb/viewfiles#'.preg_replace('/\.|\//', '_', $viewfile)); ?>"><?php echo $viewfile;?></a></td>
                                    </tr>
                                    <?php endforeach; ?>
                                </table>
                            <?php endif; ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
            </div>
            <?php endforeach; 
        endif;
        ?>
    </div>
</div>
