<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

if($this->allowed) : ?>
<div id="publish_tab">
    <span><?php echo $this->translate('Non published media will only appear to you in your "My Media" page. You can publish to multiple categories and channels.');?></span>
    <div id="publish_options" class="wrapper">
        <?php 
            $entryModel = Kms_Resource_Models::getEntry();
            $categories = $this->entryCats;
            $published = false;
            if(!count($categories))
            {
                $published = false;
            }
            elseif(count($categories) > 0)
            {
                $published = true;
            }
            
        echo $this->partial('partials/publishOptions.phtml', 'publish', array('published' => $published, 'entryId' => $entryModel->id, 'publishCategories' => $this->canPublishToGalleries, 'publishChannels' => count($this->channelsForPublish) ));
        ?>
    </div>
    <div id="publish_messages"></div>
    <div id="publishcats" class="container <?php echo $published? 'published' : 'unpublished'?>">
        <?php if($this->canPublishToGalleries) :?>
            <div class="galleries" >            
            <?php

            // get cats from navigation
            $this->navigation()->setContainer(Kms_Resource_Nav::getContainer());
            $this->navigation()->setMaxDepth(4)->setMinDepth(0);
            echo $this->navigation()
                    ->menu()
                    ->setPartial(array('partials/categoryList.phtml', 'publish'));
            ?>
            </div>
        <?php endif;?>
        <?php if(count($this->channelsForPublish)): ?>
            <ul class="publish_to_channels channels" style="<?php echo $published && !$this->canPublishToGalleries ? 'display: block;' : ''; ?>">
            <?php
            echo $this->partial('partials/channelsList.phtml', 'publish', array('channels' => $this->channelsForPublish, 'entryCats' => $this->entryCats));
            ?>
            </ul>
        <?php endif;?>
    </div>
    <?php if($this->Device(array('ios', 'android'))): ?>
    <script>
        myScroll = new iScroll("publishcats");
    </script>
    <?php endif; ?>
    <ul class="baloons clearfix">
        <li class="appears">Appears in:</li>
        <?php 
        foreach( $this->entryCats as $entryCat )
        {
            echo $this->partial(
                'partials/publishBaloon.phtml', 
                'publish', 
                array(
                    'entryId' => $this->entry->id,
                    'category' => $entryCat,
                )
            ); 
        }
        ?>
    </ul>
</div>
<?php 
endif;

if($this->pending || $this->converting || !$this->readyToPublish) : ?>
<div id="publish_tab">
    <div id="status_notice" class="notice"><?php
         if($this->converting) : 
            ?><span id="converting_media"><?php echo $this->translate('This media is still being converted');?>.&nbsp;</span><?php
         endif; 
        ?><?php 
        if($this->pending) : 
            ?><span id="pending_moderation"><?php echo $this->translate('This media is pending review');?>.&nbsp;</span><?php
         endif; 
        ?><?php 
        if(!$this->readyToPublish) : 
            ?><span id="pending_moderation"><?php echo $this->translate('Please fill out all the required fields first');?>.
                <a href="<?php echo $this->baseUrl('/edit/'.$this->entry->id);?>"><?php echo $this->translate('Edit');?></a>&nbsp;
            </span><?php
         endif; 
    ?></div>
</div>
<?php endif;
