<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
?>

<?php $this->placeholder('webcast')->captureStart('SET', 'form');?>
<div class="webcastSso" id="webcast_sso"><?php echo $this->form;?></div>

<div class="buttons">
    <a class="cancel" onclick="$('#dialog').dialog('close');"><?php echo $this->translate('Cancel');?></a>
    <a class="btn" onclick="$('#webcast_sso form').submit();$('#dialog').dialog('close');"><?php echo $this->translate('Submit');?></a>
</div>
<?php $this->placeholder('webcast')->captureEnd();?>

if($('#dialog')) {
    $("body").append('<div id="dialog"></div>');
}
    
<?php
$content = $this->placeholder('webcast')->form;
 echo new Zend_Json_Expr("$('#dialog').html(\"".(addcslashes(str_replace(array("\r\n", "\n", "\r"), '', $content), '\"'))."\");") ;
 
 $this->dialogContainer(
        'dialog', $this->placeholder('webcast')->form, array(
            'autoOpen' => true,
            'draggable' => false,
            'modal' => true,
            'width' => 342,
            'min-height' => 256,
            'resizable' => false,
            'title' => $this->translate('User Information'),
            'closeOnEscape' => true,
            'close' => new Zend_Json_Expr('function() {
                $("#dialog").remove(); setConfirmUnload(false);
             }'),
        )
    );
 
 $actions = $this->JQuery()->getOnLoadActions();
 $this->JQuery()->disable();
 foreach ($actions as $action)
 {
     echo $action;
 }