<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
?>
<?php // view to be called only on validation error. ?>

<div id="player_wrap" class="wrapper webcast">
	<div class="wrapper entry_heading">
		<h1 id="ktitle"><?php echo $this->translate('User Information') ?></h1>
	</div>
		
	<div class="webcastSso" id="webcast_sso"><?php echo $this->form;?></div>
	<div class="buttons">
	    <a class="cancel" onclick="window.close();"><?php echo $this->translate('Cancel');?></a>
	    <a class="btn" onclick="$('#webcast_sso form').submit();"><?php echo $this->translate('Submit');?></a>
	</div>
</div>
<?php 