<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */


// close the dialog - if exists
$script = '$("#dialog").remove()';
$this->JsonScript($script);

// redirect the browser to the new url
$script = "window.location.href='" . $this->url . "'";
$this->JsonScript($script);