<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

/**
 * This view file renders the extra tab in the entry-details area.
 * Clicking this tab loads the embed code tab into view.
 */
?>
<li><a id="embed" data-tab="#embed_tab"><?php echo $this->translate('Share');?></a></li>