<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

if($this->allowed)
{

    if(!$this->confirmed && $this->entryId && $this->categoryId)
    {
            $text = $this->translate('Are you sure you want to remove this item from the'). ' ' .(isset($this->channel) ? $this->translate('channel') : $this->translate('gallery')).'?'; 
    ?>
            if($('#dialog')) {
                $("body").append('<div id="dialog"></div>');
            }
            $("#dialog").text('<?php echo $text ?>');

            <?php 
                $this->dialogContainer(
                    'dialog',
                    $text,
                    array(
                        'autoOpen'      => true,
                        'draggable'     => false,
                        'modal'         => true,
                        'resizable'     => false,
                        'title'         => $this->translate('Remove Media'),
                        'closeOnEscape' => true,
                        'open' => new Zend_Json_Expr('function() {
                                $("#player").addClass("hideplayer");
                            }'
                        ),
                        'close' => new Zend_Json_Expr('function() {
                            $("#player").removeClass("hideplayer");
                            $("#dialog").remove();
                        }'),
                        'buttons'   => array(
                            $this->translate('Yes') =>  new Zend_Json_Expr('function() {
                                $("body").addClass("cursorwait");
                                var url = "'.$this->baseUrl('/gallery/remove-entry/entry/'.$this->entryId.'/category/'.$this->categoryId.'/confirm/1?format=ajax').'";
                                $.getJSON(url, asyncCallback).error( transportError );
                            }'),
                            $this->translate('No') => new Zend_Json_Expr('function() {
                                $(this).dialog(\'close\');
                            }'),
                        ),
                 )
                );
    }
    }
    else
    {
        $text = $this->translate('You are not allowed to remove this media').'.'; ?>
        if($('#dialog')) {
            $("body").append('<div id="dialog"></div>');
        }
        $("#dialog").text('<?php echo $text ?>');

        <?php 
            $this->dialogContainer(
                'dialog',
                $text,
                array(
                    'autoOpen'      => true,
                    'draggable'     => false,
                    'modal'         => true,
                    'resizable'     => false,
                    'title'         => $this->translate('Remove Media'),
                    'closeOnEscape' => true,
                    'open' => new Zend_Json_Expr('function() {
                            $("#kplayer").addClass("hideplayer");
                        }'
                    ),
                    'close' => new Zend_Json_Expr('function() {
                        $("#kplayer").removeClass("hideplayer");
                        $("#dialog").remove();
                    }'),
                    'buttons'   => array(
                        $this->translate('Ok') => new Zend_Json_Expr('function() {
                            $(this).dialog(\'close\');
                        }')
                    ),
                )
            );
    }
    

$actions = $this->JQuery()->getOnLoadActions();

$this->JQuery()->disable();

foreach($actions as $action)
{
    echo $action;
}
//echo '$("#kplayer").css("visibility", "hidden");';

