<?php

/* 
 *  All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 *  To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */


/*$this->JsonContent(array(
    'target' => '#kgallery #kitems li[data-entryid="'.$this->entryId.'"]',
    'action' => 'deleteFade',
    'content' => ' ')
);
*/
$this->JsonScript('document.location.reload()');