<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
/**
 * Main view script for the Gallery
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_PREGALLERY
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_POSTGALLERY
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_PREGALLERYITEMS
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_POSTGALLERYITEMS
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_PRE_CHANNEL
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_CHANNEL_BUTTONS
 */
// add the tooltip js
//$this->headScript()->appendFile($this->baseUrl('build'.BUILD_NUMBER.'/js/jquery.tools.min.js'));
$this->headScript()->appendFile($this->baseUrl('build' . BUILD_NUMBER . '/js/ktooltip.js'));

$hideGallery = false;

$active = $this->navigation()->findActive($this->navigation()->getContainer());
//Zend_Debug::dump($active['page']);
//exit;
$headLabel = '';
$disableSideNav = false;
if (isset($active['page'])) {
    $headLabel = $this->String()->htmlEntities($active['page']->getLabel());
    $this->headTitle($active['page']->getLabel());
    $pageParams = $active['page']->getParams();
    $disableSideNav = isset($pageParams['disableSideNav']) ? $pageParams['disableSideNav'] : false;
}

// determine if there is only one level of breadcrumbs
// if so, output an <h2> using headingOnly
//$page = new Zend_Navigation_Page_Mvc();
//$page->getParams();
if (!$disableSideNav) {
    /* set side navigation */
    $this->placeholder('Side_Bar')->content = $this->SideNavigation();
}
$breadcrumbs = '';
$counters = '';
$_sub_heading = '';
$pageheading = '';
if ($disableSideNav || ($this->wideLayout && (!isset($active['depth']) || $active['depth'] < 1))) {
    if ($headLabel) {
        if ($this->channel) {
            $mediaCount = $this->channel->directEntriesCount;
            $mediaCount = $mediaCount < 0 ? '' : ($mediaCount > 0 ? $mediaCount : $this->translate('No')) . ' ' .$this->translate('media');
            $memberCount = $this->channel->membersCount < 0 ? '' : $this->channel->membersCount . ' ' . (($this->channel->membersCount == 1) ?  $this->translate('member') : $this->translate('members'));
    	    $back_to_shannels = '<a class="back_to_channels" href="' . $this->baseUrl('channels') . '" title>&laquo; ' . $this->translate('Back to Channels') . '</a>';
    	    $pre_channel_hook = $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_PRE_CHANNEL);
    	    if(isset($this->channel->createdAt)){
    	        $_sub_heading .= '<div><span class="channel_ts">Created ' . $this->Timespan($this->channel->createdAt, time()) . ' </span>';
    	    }
            $_sub_heading .= '<span class="media_counter">' 
		    . $mediaCount . (!empty($mediaCount) && !empty($memberCount) ? ',' : '') . ' </span><span class="members_counter">' 
		    . $memberCount . '</span>' . $pre_channel_hook;
	    $_sub_heading .= '</div>';
            $_sub_heading = $this->subHeading($_sub_heading, 'inline_sub_heading');
            $pageheading = $this->headingOnly($headLabel, 'h1', 'inline_heading wide') . $_sub_heading;
            $pageheading .= $back_to_shannels;
        } else {
            $pageheading = $this->headingOnly($headLabel);
        }
    }
} else {
    $pageheading = $this->headingOnly($headLabel);  
    $separator = '<span>&nbsp;&#92;&nbsp;</span>';
    $breadcrumbs = $this->navigation()->breadcrumbs()->setLinkLast(true)->setMinDepth(0)->setSeparator($separator);
}
$galleryButtons = '<div id="gallerybuttons">';
if (!empty($this->channel)) {
    $buttons = $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_CHANNEL_BUTTONS);
} else {
    $buttons = $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_GALLERY_BUTTONS);
    $pagesInfo = $this->partial()->view->paginator->getPages();
    if ($pagesInfo->lastItemNumber && $pagesInfo->totalItemCount) {
	$counters = '(' . $pagesInfo->firstItemNumber . '-' . $pagesInfo->lastItemNumber . ' ' . $this->translate('of') . ' ' . $pagesInfo->totalItemCount . ' ' . $this->translate('media') . ')';
    }
}
$bc = $this->topBreadCrumbs($breadcrumbs, $counters);
$pageheading .= $bc;

$galleryButtons .= $buttons . '</div>';

$pageheading .= $galleryButtons;
$this->placeholder('pageHeading')->content = $pageheading;
?>
<?php
echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_PREGALLERY);
if ($this->galleryType != 'playlist') {
    // display filter bar (not in playlist view)
    ?>
    <div id="filter_bar" class="wrapper">
	<?php
	$current_type = null;
	$currentType = $this->params['type'];
	if (empty($currentType)){
		$currentType = 'all';
	}
	$sorters = $this->FilterBarSortersPreparator($currentType);
	$filterTypes = $this->FilterBarFilterTypesPreparator($currentType);
	
	echo $this->partial('partials/filterBar.phtml', array(
		'currentType' => $currentType,
		'filterTypes' => $filterTypes,
		'sorters' => $sorters,
		'showAdditionalSearches' => true
	    	
	));
	?>
    </div>
    <?php
}
?>
<?php
if ($this->entries && count($this->entries)):
    
    // hook for search results rendering (my media style) for KMS 4.6
    if(isset($this->params['keyword']) && $this->params['keyword'] || isset($this->searchKeyword) && $this->searchKeyword):
    ?>
    <div id="mymedia" class="gallery">
	<?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_PREGALLERYITEMS); ?>                
        <ul id="kitems">
	    <?php
            foreach($this->entries as $entry)
            {
                echo $this->partial('partials/entryItem/detailed.phtml', 
                        array(
                            'entry' => $entry, 
                        	'showPublish' => false,
                            'actions' => array(
                               // '<a href="'.$this->baseUrl('edit/'.$entry->id).'" class="edit_entry"><em></em>'.$this->translate('Edit').'</a>'
                            ),
                            'disableCheckbox' => true,
                            'itemTag' => 'div',
                            'odd' => $this->cycle(array(false, true))->next()->toString()
                        )
                );
            }
            ?>
        </ul>
	<?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_POSTGALLERYITEMS); ?>                

    <?php
    else:
    ?>
    <div id="kgallery" class="gallery">
	<?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_PREGALLERYITEMS); ?>                
        <ul id="kitems">
	    <?php
	  /*  if ($this->presentationView) {
		    echo $this->partialLoop('partials/entryItem/thumbData.phtml', $this->entries);
	    } else {*/
            $this->partialLoop()->setObjectKey('entry');
		    echo $this->partialLoop('partials/entryItem/thumb.phtml', $this->entries);
	    //}
	    ?>
        </ul>
	<?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_POSTGALLERYITEMS); ?>                
    <?php
    endif;
else:
	?>
        <div class="no_items"><?php echo $this->translate('No media found'); ?>.</div>
    <?php
endif;
    ?>
    <div id="pager" class="wrapper"><?php
	echo $this->paginationControl($this->paginator, $this->pagerType, 'partials/galleryPaging.phtml');
	?></div>
</div>
<?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_POSTGALLERY); ?>   
<script type="text/javascript" language="javascript">                
    $("#kitems li .item_link[title]").ktooltip();
    // parse erros of images
    $('#kitems img').error(function() {
        $(this).attr("src", "<?php echo $this->baseUrl('build' . BUILD_NUMBER . '/img/no-thumbnail.png');?>" ); 
    });

</script>