<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
?>
<div id="captions_header" class="wrapper">
	<div class="column language first"><?php echo $this->translate('Language')?></div>
	<div class="column label"><?php echo $this->translate('Label')?></div>
	<div class="column change">&nbsp;</div>
	<div class="column file"><?php echo $this->translate('File type')?></div>
</div>
<?php 
