<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

/**
 * captions search results within an entry
 */

// anchor parameters for search results within an entry
$rel = '';
$data_cond = '';
if (isset($this->partialLoop()->view->rel)) {
    $rel = $this->partialLoop()->view->rel;
    $data_cond = 'KApps.CaptionsSearch.entryChanged();';
}

// check for start time outside entry duration
if ($this->startTime > $this->entry->msDuration) {
    $this->startTime = $this->entry->msDuration;
}

// thumbnail rotation params
$startTimeInSecs = $this->startTime / 1000;
$thumbRotateStartSec = ($startTimeInSecs) - 2;
if($thumbRotateStartSec < 0) $thumbRotateStartSec = 0;
$thumbRotateEndSec = ($this->endTime/1000) + 2;
	
// playback seek times
$seekTimeInMSecs = $this->startTime-2000;
if($seekTimeInMSecs < 0) $seekTimeInMSecs = 0;
	
$autoPauseTimeInMSecs = $this->endTime+2000;
	
// get thumbnail URL with options
$thumbnailUrl = rtrim($this->entry->thumbnailUrl . '/width/110/height/60/type/' . Kaltura_Client_Enum_ThumbCropType::CROP . '/vid_sec/' . $startTimeInSecs);

// highlight word matches in the result caption text
$captionText = $this->highlightMatches($this->content, $this->partialLoop()->view->keyword);

$active = '';

?>   
<li class="" 
    data-start="<?php echo $seekTimeInMSecs; ?>" 
    data-end="<?php echo $autoPauseTimeInMSecs; ?>" 
    data-entryid="<?php echo $this->entry->id; ?>" 
    data-label="<?php echo $this->asset->label;?>"
    data-lang="<?php echo $this->asset->language;?>"
    <?php if (Kms_Resource_Config::getModuleConfig('captions', 'thumbnailRotator') && !$this->Device(array('ios','android'))):?>
        onmouseover="KalturaCaptionsThumbRotator.start($(this).find('.item_preview > img').get(0), <?php echo $thumbRotateStartSec; ?>, <?php echo $thumbRotateEndSec; ?>)" 
        onmouseout="KalturaCaptionsThumbRotator.end($(this).find('.item_preview > img').get(0))"
    <?php endif;?>>
    <a href="<?php echo $this->EntryLink($this->entry->id, $this->entry->name) . '?inTime='. $seekTimeInMSecs .'&outTime='. $autoPauseTimeInMSecs .'&label='. urlencode($this->asset->label) .'&language=' . urlencode($this->asset->language); ?>"  rel="<?php echo $rel; ?>" data-cond="<?php echo $data_cond; ?>" seturl="1" class="item_link">
	<span class="item_preview">
	    <img src="<?php echo $thumbnailUrl; ?>" height="60" width="110" alt="<?php echo $this->escape($this->name); ?>"  />
	    <span class="duration"><?php echo $this->String()->formatDuration($startTimeInSecs); ?>'</span>
	    <span class="icon"></span>
	    <span class="thumb_frame"></span>
	</span>
	<span class="caption-text"><?php echo $captionText; ?></span>	
    </a>
</li>
<?php 
