<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

// this is the caption search result of a single entry, with all its assets
?>

<li <?php echo isset($divClass) ? 'class="' . $divClass . '"' : '' ?> data-entryid="<?php echo $this->entry->id ?>">
    <label class="operate">
	<div class="item" <?php echo Kms_Resource_Config::getModuleConfig('captions', 'thumbnailRotator') && !$this->Device(array('ios', 'android')) ? $this->thumbRotator('img.tmb_top') : ''; ?>>
	    <h3>
			<a href="<?php echo $this->EntryLink($this->entry->id, $this->entry->name); ?>" ><?php echo $this->escape($this->entry->name); ?></a>
	    </h3>	
        <a href="<?php echo $this->EntryLink($this->entry->id, $this->entry->name); ?>" >
		<?php if ($this->entry->status == Kaltura_Client_Enum_EntryStatus::READY): ?>
		    <?php $thumbnailUrl = rtrim($this->entry->thumbnailUrl . '/width/110/height/60/type/' . Kaltura_Client_Enum_ThumbCropType::CROP); ?>
    		<span class="item_preview">
    		    <img class="tmb_top" src="<?php echo $thumbnailUrl; ?>" height="60" width="110" alt="<?php echo $this->escape($this->name); ?>"  />
    		    <span class="duration"><?php echo $this->String()->formatDuration($this->entry->duration); ?>'</span>
    		    <span class="icon"></span>
    		    <span class="thumb_frame"></span>
    		</span>
		<?php else: ?>
    		<img title="<?php echo $this->translate('Converting'); ?>" src="<?php echo $this->baseUrl('/img/converting.png?');
		echo $this->entry->status ?>" height="60" width="110" alt="<?php echo $this->escape($this->entry->name); ?>" />
		     <?php endif; ?>
	    </a>

	    <div class="item_content">
		<?php
			$displayName = $this->String()->getAuthorNameFromTags($this->entry->tags);
			$displayNameExists = $displayName ? true : false;
			$_name = $displayName ? $displayName : $this->userId;
			$displayName = $_name;
		?>

		<span><?php echo $this->translate('By'); ?>:&nbsp;
		    <a class="nickname" href="<?php echo $this->baseUrl("/createdby/" . $displayName . ($displayNameExists ? '/dn' : '')); ?>"><?php echo $displayName; ?></a>
		    &nbsp;<?php echo $this->translate('uploaded') . ' ' . $this->Timespan($this->entry->createdAt, time()); ?>
		</span>
		<?php if (isset($this->entry->description) && strlen($this->entry->description)): ?>
    		<span <?php echo 'title="' . $this->entry->description . '"' ?> class="short_desc"><?php echo $this->escape($this->String()->shortenDescription($this->entry->description, 200)); ?></span>
		<?php endif; ?>

            <ul id="entry_tags" class="wrapper">
		    <?php
		    $tagsOut = '';
		    if ($this->entry->tags) {
				// max 20 tags
				$entryTags = array_slice(explode(", ", $this->entry->tags), 0, 20);
				foreach ($entryTags as $entryTag) {
				    if (strpos($entryTag, "displayname_") === false) {
						$tagUrl = isset($this->tagUrl) && $this->tagUrl ? str_replace('%tag%', $entryTag, $this->tagUrl) : $this->MergeUrl(array('tag' => $entryTag));
						$tagRel = isset($this->tagRel) && $this->tagRel !== null ? $this->tagRel : 'async';
						$tagsOut .= '<li><a href="' . $tagUrl . '" rel="' . $tagRel . '">' . $this->escape($entryTag) . '</a></li>';
				    }
				}
		    }
		    if ($tagsOut != '') {
				echo $tagsOut;
		    }
		    ?>
            </ul>

			<?php $views = isset($this->entry->views) && $this->entry->views ? number_format($this->entry->views) : "0"; ?>
            <div class="stats">
			    <?php
			    // check if published or not
			    $published = Kms_Resource_Models::getEntry()->isPublished($this->entry);
			    echo $this->translate('Views') . ': ' . "$views&nbsp;";
			    echo '(' . ($published ? $this->translate('Published') : $this->translate('Not published')) . ')';
			    ?>
            </div>
	    </div><!-- item_content -->

	</div><!-- item -->
    </label>
    <ul href="<?php echo $this->EntryLink($this->entry->id, $this->entry->name); ?>" class="captions_results">
	<?php echo $this->partialLoop('partials/entrySearchResult.phtml', 'captions', $this->assetItems); ?>
    </ul>
</li>
<?php 