<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

// partial to hold the caption ksu. used by the upload partial.

$id = 1;
?>

<script>
    ksuHandler = new ksuHandlerPrototype();
    ksuHandler.id = <?php echo $id?>;
</script>

<div id="uploadbox<?php echo $id?>" class="uploadbox">
     <label id="fileSelection"><?php echo $this->translate('Select a file:')?></label>
     <div class="uploadbutton">
                <span class="loader"><?php echo $this->translate('Loading');?>&hellip;</span>
                <span class="text"><?php echo $this->translate('Browse'); ?>&hellip;</span>
                <span class="change"><?php echo $this->translate('Change'); ?></span>
                <object 
                    type="application/x-shockwave-flash" 
                    data="<?php echo $this->movieUrl ?>" 
                    id="ksu<?php echo $id ?>" >
                    <param name="allowScriptAccess" value="always" />
                    <param name="allowNetworking" value="all" />
                    <param name="wmode" value="transparent" />
                    <param name="flashvars" value="entryId=-1&uid=<?php echo $this->partial()->view->userId ?>&partnerId=<?php echo $this->partial()->view->partnerId ?>&ks=<?php echo $this->partial()->view->ks ?>&jsDelegate=ksuHandler" />
                    <param name="movie" value="<?php echo $this->movieUrl ?>" />
                </object>
      </div>
      <div id="changeCaptionFile"><span class="fileName"></span></div>
      <div class="progressbar"><span style="position: absolute"></span></div>
</div> 
<?php 
        