<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

$form = '';
// error box
if(isset($this->saveError) && true === $this->saveError)
{
    $form .= '<div class="errorbox">'.$this->translate('Oops, something went wrong. The information was not saved.').'</div>';
}
elseif(isset($this->formValid) && false === $this->formValid)
{
    $form .= '<div class="errorbox">'.$this->translate('Please fill out all required fields').'</div>';
}

// form header
$form .= '<h4>'.$this->translate('Please fill out these details').':</h4>';

// the form itself
$form .= $this->form->render();


$this->JsonContent(
    array(
        'target' => '#uploadbox'.$this->uploadBoxId.' .entry_details',
        'content' => $form,
        'action' => 'replace'
    )
);

if($this->formValid)
{
    $this->JsonContent(array(
        'target' => '#uploadbox'.$this->uploadBoxId.' .entry_details button.save_edit_entry', 
        'content' => '<span class="pendingsave">* '.$this->translate('The information will be saved, once the file is finished uploading').'.</span>',
        'action' => 'after',
    ));
}
?>
<?php  
    // capture script
    $this->placeholder('script')->captureStart('SET', 'script'); 

if($this->formValid):
/* set form status to saved
 * and auto submit it
  */  
?>
ksuHandlers[<?php echo $this->uploadBoxId;?>].formSaved = true;
if(ksuHandlers[<?php echo $this->uploadBoxId;?>].entryId) {
    $("#uploadbox<?php echo $this->uploadBoxId;?> .Entry-id").val( ksuHandlers[<?php echo $this->uploadBoxId;?>].entryId );
    ksuHandlers[<?php echo $this->uploadBoxId;?>].submitForm();
}

<?php
else:
?>
$('#uploadbox<?php echo $this->uploadBoxId;?> .Entry-name').focus().select();
<?php
endif;

  /*  $actions = $this->JQuery()->getOnLoadActions();

    $this->JQuery()->disable();

    foreach($actions as $action)
    {
        echo $action;
    }*/
    // end script capture
    $this->placeholder('script')->captureEnd(); 

    $this->JsonScript($this->placeholder('script')->script);