<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

/**
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_EDIT_ENTRY_OPTIONS
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_EDIT_ENTRY_TABS
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_EDIT_ENTRY_TABLINKS
 */

$this->headTitle($this->entry->name)->headTitle($this->translate('Edit Media')); 
?>
<div id="edit" class="<?php echo $this->presentationView ? 'kpw' : ''?>">
    <div class="heading_box wrapper">
        <h1 class="fleft"><?php echo $this->translate('Edit Media');?></h1>
        <a href="<?php echo $this->baseUrl('/media/'.$this->entry->id)?>" class="fright">&lsaquo; <?php echo $this->translate('Back to media');?></a>
    </div>
    <div id="edit_player">
    <?php 
        if($this->converting) : 
            
    ?>
        <div class="noplayer_converting"><h3><?php echo $this->translate('Media is being processed');?>  (: !</h3></div>

    <?php 
    elseif($this->presentationView):
    echo $this->partial('partials/widgets/kpw.phtml', array('entryId' => $this->entry->id,'edit' => true)); 
    elseif ($this->noPlayer): ?>
      	<!-- show thumb instead of player -->
      	<img class="tmb" src="<?php echo $this->entry->thumbnailUrl; ?>/width/520/height/320/type/<?php echo Kaltura_Client_Enum_ThumbCropType::CROP;?>" width="520" height="320" alt="<?php echo $this->escape($this->entry->name); ?>" />
    <?php  
        else:
            echo $this->partial('partials/widgets/kdp.phtml', array('entryId' => $this->entry->id,'edit' => true));
    	endif;
    ?>
      
    </div>
    <a href="<?php echo $this->baseUrl('/entry/delete/id/'.$this->entry->id)?>" rel="dialog" class="fright btn"><?php echo $this->translate('Delete')?></a>
    <div id="player_tabs">
    <ul id="player_tab_buttons">
        <li><a data-tab="#entry_details"><?php echo $this->translate('Details');?></a></li>
    <?php if(count(Kms_Resource_Config::getModulesForViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_EDIT_ENTRY_OPTIONS))): ?>
        <li><a data-tab="#entry_options"><?php echo $this->translate('Options');?></a></li>
    <?php endif; ?>
        <?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_EDIT_ENTRY_TABLINKS); ?>
    </ul>
    <div id="entry_details" class="entry_details">
    <?php  // error box
        if(isset($this->saveError) && true === $this->saveError):?>
        <div class="errorbox"><?php echo $this->translate('Oops, something went wrong. The information was not saved.');?></div>
    <?php
        elseif(isset($this->formValid) && false === $this->formValid):?>
        <div class="errorbox"><?php echo $this->translate('Please fill out all required fields');?></div>
    <?php endif; ?>
        <h4><?php echo $this->translate('Please fill out these details');?>:</h4>
        <?php echo $this->form ?>
    </div>
    <?php if(count(Kms_Resource_Config::getModulesForViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_EDIT_ENTRY_OPTIONS))): ?>
    <div id="entry_options">
        <?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_EDIT_ENTRY_OPTIONS); ?>
    </div>
    <?php endif;?>
    <?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_EDIT_ENTRY_TABS); ?>

    <script>
        $('#player_tabs > div').hide();

        $('#player_tabs > div:first').show();
        $('#player_tabs > ul li:first').addClass('current');

        $('#player_tabs > ul li > a').click(function() {
            $('#player_tabs > ul li').removeClass('current');
            $(this).parent().addClass('current');
            var currentTab = $(this).attr('data-tab');
            $('#player_tabs > div').hide();
            $(currentTab).show();
            var onShow = $(currentTab).attr('onshow');
            if(onShow) {
                eval(onShow);
            }

            //return false;
        });
    </script>
</div>
</div>

