<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

?>
var entry = <?php echo Zend_Json::encode($this->entry); ?>;
kdp.sendNotification('changeMedia', {entryId: entry.id});
$('#kitems li').removeClass('playing');
$('#kitems li[data-entryid=<?php echo $this->entry->id ?>]').addClass('playing');
