<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

/**
 * render the player block for an entry.
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_ENTRY_PAGE
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_PLAYERSIDETABLINKS
 */

    $this->titleTag = 'h1';

    $this->showPlayer = true;
    
    if ($this->renderByModule) {
        // the view will be rendered by module (only one will meet the type requirement)
        $playerBlock = $this->viewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_ENTRY_PAGE, null, null, 'Kms_Interface_Functional_Entry_Type', 'isHandlingEntryType', array($this->entry));

        if (!empty($playerBlock)) {
            echo $playerBlock;
        }
        else {
        	$this->showPlayer = false;
            // no module handled this entry - render the base minimal
            echo $this->partial('partials/unknownPlayerBlock.phtml', $this->entry);
        }
    }
    else{
        echo $this->partial('partials/playerBlock.phtml', $this->entry);
    }

     // see if any modules are using the sidetabs viewhook and change layout accordingly
    $enablePlayerBlockSide = count(Kms_Resource_Viewhook::getModulesRegisteredForViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_PLAYERSIDETABLINKS));    
    if($enablePlayerBlockSide):?>
        <div id="playersidebar">
            <?php echo $this->partial('partials/playerBlockSideTabs.phtml', $this->entry); ?>
        </div>
    <?php endif;?>

    <?php if (!$this->renderByModule || empty($playerBlock)): ?>
        <div id="player_data">
        <?php echo $this->partial('partials/playerData.phtml', $this->entry); ?>
        </div>
    <?php endif;?>    
<?php    
