<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

$this->JsonContent(
	array(
	    'target' => '#ktitle',
	    'content' => $this->escape($this->entry->name),
	    'action' => 'replace'
	)
);

$this->JsonContent(
	array(
	    'target' => '#player_data',
	    'content' => $this->partial('partials/playerData.phtml', $this->entry),
	    'action' => 'replace'
	)
);

$this->JsonContent(
	array(
	    'target' => '#player_tabs',
	    'content' => $this->partial('partials/playerBlockTabs.phtml', $this->entry),
	    'action' => 'replace'
	)
);

if(!$this->presentationView) // dont show views for video presentations
{
    $this->JsonContent(
            array(
                'target' => '#player_wrap .views',
                'content' => number_format($this->entry->views).'<span>&nbsp;'.$this->translate('views').'</span>',
                'action' => 'replace'
            )
    );
}
// capture script
$this->placeholder('script')->captureStart('SET', 'script');
if ($this->presentationView):
    ?>

    var kpwReadyInterval = setInterval(function(){
        if(typeof(kpwLoaded) != 'undefined' && kpwLoaded) {
            clearInterval(kpwReadyInterval);
            var kpwEntry = kpw.evaluate("{pptWidgetAPI.dataEntry}");
            if(kpwEntry && kpwEntry.id && kpwEntry.id != '<?php echo $this->entry->id; ?>') {
                kpw.sendNotification('changeVideoPresentation', {entryId: '<?php echo $this->entry->id; ?>'});
                $('#kitems li').removeClass('active');
                $('#kitems li[data-entryid=<?php echo $this->entry->id ?>]').addClass('active');    
            }
        }
    }, 100);
    <?php
else:
    ?>
    var playerReadyInterval = setInterval(function(){
        if(typeof(playerLoaded) != 'undefined' && playerLoaded) {
            clearInterval(playerReadyInterval);
            var kdpEntry = kdp.evaluate("{mediaProxy.entry}");
            if(kdpEntry && kdpEntry.id && kdpEntry.id != '<?php echo $this->entry->id; ?>') {
                kdp.sendNotification('changeMedia', {entryId: '<?php echo $this->entry->id; ?>'});
                $('#kitems li').removeClass('active');  
                $('#kitems li[data-entryid=<?php echo $this->entry->id ?>]').addClass('active');    
            }
        }
    }, 100);

<?php
endif;
// set the title
?>
<?php echo new Zend_Json_Expr('document.title = "' . strip_tags($this->headTitle($this->entry->name)) . '";'); ?>

<?php
// end script capture
$this->placeholder('script')->captureEnd();
$this->JsonScript($this->placeholder('script')->script);