<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/


$text = $this->translate('This will cause this media to be disassociated from all categories and it will not appear anywhere in MediaSpace.'); 

?>
if( !$("#Entry-private").attr('checked')) {
    if($('#dialog')) {
        $("body").append('<div id="dialog"></div>');
    }
    $("#dialog").text('<?php echo $text ?>');
    
    <?php 
        $this->dialogContainer(
            'dialog',
            $text,
            array(
                'autoOpen'      => true,
                'draggable'     => false,
                'modal'         => true,
                'resizable'     => false,
                'title'         => $this->translate('Confirm Unpublishing'),
                'closeOnEscape' => true,
                'close' => new Zend_Json_Expr('function() {
                    $("#dialog").remove();
                }'),
                'buttons'   => array(
                    $this->translate('Confirm') =>  new Zend_Json_Expr('function() {
                        $("#Entry-categories-element").hide();
                        $("label[for=\"Entry-categories\"]").hide();
                        $("#Entry-private").attr("checked", "false");
                        $(this).dialog(\'close\');
                    }'),
                    $this->translate('Cancel') => new Zend_Json_Expr('function() {
                        $(this).dialog(\'close\');
                    }')
                ),
         )
        );


        $actions = $this->JQuery()->getOnLoadActions();

        $this->JQuery()->disable();

        foreach($actions as $action)
        {
            echo $action;
        }
        ?>
} else {
    $("#Entry-categories-element").show();
    $("label[for=\"Entry-categories\"]").show();
    $("#Entry-private").removeAttr('checked');
}