<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
* To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

if($this->success)
{
   $this->JsonContent(
            array(
                'target' => '#klike',
                'content' => '<a class="btn" href="' . $this->baseUrl('/entry/like/id/') . $this->id . '"  rel="async">' . $this->translate('Like') . '<span class="klike_icon">&nbsp;</span></a>',
                'action' => 'replace'
            )
    );

   if(!is_null($this->likes))
    {
        $this->JsonContent(
            array(
                'target' => '#player_data .likes',
                'content' => '<strong>'.number_format($this->likes) . '</strong> '. ($this->likes == 1 ? $this->translate('like') : $this->translate('likes')),                    
                'action' => 'replace'
            )
        );
    }
}