<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

$url = null;
if (isset($this->channelId))
{
    $url = $this->baseUrl('/addcontent/index/index/channelid/' . $this->channelId);
}
elseif (isset($this->categoryId) && Kms_Plugin_Access::getCurrentRole() != Kms_Plugin_Access::getRole(Kms_Plugin_Access::PRIVATE_ROLE))
{
    $url = $this->baseUrl('/addcontent/index/index/categoryid/' . $this->categoryId);
}

if ($url):
    ?>
    <a class="btn" data-timeout="120" id="add_media" href="<?php echo $url; ?>" rel="dialog"><span class="icon">&nbsp;</span><?php echo $this->translate('Add Media'); ?></a>
    <?php
endif;
?>