<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/
    $content = '';
    if ($this->partial()->view->entries && count($this->partial()->view->entries))
    {
        foreach($this->partial()->view->entries as $entryId => $entryModel)
        {
            $content .=  $this->partial('partials/entryLine.phtml', 'addcontent' ,
                array(
                    'entry' => $entryModel->entry, 
                    'enabled' => $entryModel->readyToPublish,
                    'published' => isset($this->partial()->view->published[$entryModel->id]),
                    'itemTag' => 'label'
                )
            );
        }
    }
    else
    {
        $content .= '<li>'.$this->translate("No media found").'.</li>';
    }


    $this->JsonContent(array(
        'target' => '#addcontent #kitems',
        'content' => $content,
        'action' => 'replace'
        )
    );
    
    $this->JsonContent(array(
            'target' => '#addcontent #pager',
            'content' => $this->paginationControl($this->partial()->view->paginator, $this->partial()->view->pagerType, 'partials/galleryPaging.phtml'),
            'action' => 'replace'
        )
    );

    $this->placeholder('script')->captureStart('SET', 'script');
?>
    $("#addcontent #kitems .item .name[title]").ktooltip({tipclass: 'ktooltip-mymedia'});
<?php
    $this->placeholder('script')->captureEnd();
    $this->JsonScript($this->placeholder('script')->script);
