<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
?>

<?php

if ($this->allowed)
{
    $content = $this->partial('partials/addContent.phtml', 'addcontent');
    ?>

    if($('#dialog')) {
        $("body").append('<div id="dialog"></div>');
    }
    
    <?php
    echo new Zend_Json_Expr("$('#dialog').html(\"".(addcslashes(str_replace(array("\r\n", "\n", "\r"), '', $content), '\"'))."\");") ;
    
    
    
    $this->dialogContainer(
        'dialog', $content, array(
            'autoOpen' => true,
            'draggable' => false,
            'modal' => true,
            'width' => 690,
            'height' => 480,
            'resizable' => false,
            'title' => $this->translate('Add Media'),
            'closeOnEscape' => true,
            'open' => new Zend_Json_Expr('function() {
                    $("#player").addClass("hideplayer");
                }'
            ),
            'close' => new Zend_Json_Expr('function() {
                    $("#player").removeClass("hideplayer");
                    $("#dialog").remove();
                }'
            ),
        )
    );
    
    ?>
    $('#addcontent #kitems .operate input#sel-entry').live('click', function(){
       if($(this).attr("checked")) {
           $("#addcontent #kitems li[data-entryid="+$(this).val()+"]").addClass("selected");
       } 
       else {
           $("#addcontent #kitems li[data-entryid="+$(this).val()+"]").removeClass("selected");
       }
    });  


    $("#addcontent #kitems .item .name[title]").ktooltip({tipclass: 'ktooltip-mymedia'});
    
    <?php
    
    
}
else
{
    $content = $this->translate('You are not allowed to add media to this category or channel.');
    ?>
    if($('#dialog')) {
        $("body").append('<div id="dialog"></div>');
    }
    $("#dialog").html('<?php echo $content ?>');

    <?php
    $this->dialogContainer(
        'dialog', $content, array(
            'autoOpen' => true,
            'draggable' => false,
            'modal' => true,
            'resizable' => false,
            'title' => $this->translate('Add Media'),
            'closeOnEscape' => true,
            'open' => new Zend_Json_Expr('function() {
                    $("#player").addClass("hideplayer");
                }'
            ),
            'close' => new Zend_Json_Expr('function() {
                    $("#player").removeClass("hideplayer");
                    $("#dialog").remove();
                }'
            ),
            'buttons' => array(
                $this->translate('Ok') => new Zend_Json_Expr('function() {
                        $(this).dialog(\'close\');
                    }'
                )
            ),
        )
    );
}

$actions = $this->JQuery()->getOnLoadActions();

$this->JQuery()->disable();

foreach ($actions as $action)
{
    echo $action;
}
?>
