<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
?>

<?php

if ($this->allowed)
{
    if($this->noEnries)
    {
        echo $this->partial('partials/noEntries.phtml', 'addcontent');
    }
    else
    {
        echo $this->partial('partials/addContent.phtml', 'addcontent');
        ?>
    <script>
        $('#addcontent #kitems .operate input#sel-entry').live('click', function(){
           if($(this).attr("checked")) {
               $("#addcontent #kitems li[data-entryid="+$(this).val()+"]").addClass("selected");
           } 
           else {
               $("#addcontent #kitems li[data-entryid="+$(this).val()+"]").removeClass("selected");
           }
        });  


        $("#addcontent #kitems .item .name[title]").ktooltip({tipclass: 'ktooltip-mymedia'});
    </script>    
    <?php
    }
}
else
{
    echo $this->translate('You are not allowed to add media to this category or channel.');
}
