<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/
$playlistIds = array();
foreach($this->sideplaylists as $playlist): 
    if(in_array($playlist['id'], $playlistIds))
    {
        continue;
    }
    else
    {
        $playlistIds[] = $playlist['id'];
    }
    ?>

<!--<h3><a href="#"><?php echo $playlist['label']?></a></h3>-->
<ul id="sp_<?php echo $playlist['id'] ?>">
    <?php  
        if(count($playlist))
        {
            echo $this->partialLoop( 'partials/playlistItem.phtml', 'sideplaylists', $playlist['entries']); 
        }
        else
        {
            echo $this->translate("Oops! This playlist is empty... :(");
        }
    ?>
</ul>
<?php
endforeach;

