<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/


/* foreach($this->tabs as $tab): ?>
<li>
    <a name="sp_<?php echo $tab->id ?>" href="#sp_<?php echo $tab->id ?>"><?php echo $tab->label ?></a>
</li>
<?php endforeach; */

    $playlistIds = array();
    if(count($this->tabs)):
        foreach($this->tabs as $tab): 
            if(isset($tab['id']) && trim($tab['id'])):
                if(in_array($tab['id'], $playlistIds))
                {
                    continue;
                }
                else
                {
                    $playlistIds[] = $tab['id'];
                }
        ?>
        
<option value="#sp_<?php echo $tab['id'] ?>"  ><?php echo isset($tab['label']) && trim($tab['label']) ? trim($tab['label']) : $tab['id'] ?></option>
<?php
            endif;
        endforeach;
    endif;