<?php

/* 
 *  All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 *  To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

?>
<div id="bulkplaylists">
    <div class="title">
        <?php echo $this->translate('Playlists allow you to grab embed code for displaying a player and a collection of media').'.'; ?>
    </div>
    <div class="container">
        <?php 
        if(isset($this->partial()->view->playlists) && count($this->partial()->view->playlists))
        {
            foreach($this->partial()->view->playlists as $playlistItem)
            {
                echo $this->partial(
                    'partials/bulkPlaylist.phtml', 
                    'addtoplaylists', 
                    array
                    (
                        'playlist' => $playlistItem,
                    )
                );
            }
        }
        ?>
    </div>        
    <div class="buttons">
        <a class="btn" id="addtopl"><?php echo $this->translate('Add');?></a>
        <a class="cancel" onclick="$('#dialog').dialog('close');"><?php echo $this->translate('Cancel');?></a>
    </div>
</div>
<script>
    
</script>
<?php


