<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

?>
<div data-id="<?php echo $this->playlist->id; ?>" class="pl">
            <?php echo $this->formCheckbox($this->playlist->name, $this->playlist->id, array(
                'id' => 'addtopl_'.$this->playlist->id
            )); ?>
            <?php echo $this->formLabel('addtopl_'.$this->playlist->id, $this->playlist->name); ?>
    </a>
</div>
