<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

?>
<div data-id="<?php echo $this->playlist->id; ?>" class="pl">
    <a href="<?php echo $this->baseUrl('/addtoplaylists/index/add-entry/playlist/' . $this->playlist->id . '/entry/' . $this->entryId) ?>" title="<?php echo $this->escape($this->playlist->name);?>" rel="async">
            <?php echo $this->formCheckbox($this->playlist->name, $this->playlist->name, array(
                'checked' => $this->checked,
                'id' => 'addtopl_'.$this->playlist->id
            )); ?>
            <?php echo $this->formLabel('addtopl_'.$this->playlist->id, $this->playlist->name); ?>
    </a>
</div>
