<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
?>

<?php 
    $content = '<div id="remove">' .$this->translate('Remove this caption file?') . '</div>';
?>

if($('#dialog')) {
    $("body").append('<div id="dialog"></div>');
}
    
<?php
 echo new Zend_Json_Expr("$('#dialog').html(\"".(addcslashes(str_replace(array("\r\n", "\n", "\r"), '', $content), '\"'))."\");") ;
 
 $this->dialogContainer(
        'dialog', $content, array(
            'autoOpen' => true,
            'draggable' => false,
            'modal' => true,
            'resizable' => false,
            'title' => $this->translate('Confirm remove'),
            'closeOnEscape' => true,
            'close' => new Zend_Json_Expr('function() {
                $("#dialog").remove();
             }'),
            'buttons'   => array(
                    $this->translate('Yes') =>  new Zend_Json_Expr('function() {
                        $("body").addClass("cursorwait");
                        var url = "' . $this->MergeUrl( array() ) . '?format=ajax";
                        $.getJSON(url, asyncCallback).error( transportError );
                        $("#dialog").remove();
                    }'),
                    $this->translate('No') => new Zend_Json_Expr('function() {
                        $(this).dialog(\'close\');
                    }'),
           ),
        )
    );
 
 $actions = $this->JQuery()->getOnLoadActions();
 $this->JQuery()->disable();
 foreach ($actions as $action){
     echo $action;
 }