<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

$this->headScript()->appendFile($this->baseUrl('build'. BUILD_NUMBER . '/captions/asset/captions-upload.js'));

?>

<div id="entry_captions" class="entry_edit_tab">
    <div class="wrapper" id="captions_heading">
        <a id="upload" class="btn fright" href="<?php echo $this->baseUrl('captions/index/upload/entryId/' . $this->urlParams['entryId']);?>" rel="dialog"><?php echo $this->translate('Upload file')?></a>
        <h3 id="captions_count" class="fleft"><?php echo $this->partial('partials/captionsCount.phtml','captions',$this) ;?></h3>
    </div>
    
    <?php if (!empty($this->captions->objects)):?>          
        <div id="captions_header_wrapper">
           <?php echo $this->partial('partials/captionsHeader.phtml','captions',$this) ;?>
        </div>
        
        <div id="captions">
            <?php echo $this->partialLoop('partials/captionAsset.phtml', 'captions', $this->captions->objects); ?> 
        </div>
    
        <?php if ($paginator = $this->paginationControl($this->paginator, $this->pagerType, 'partials/galleryPaging.phtml',array('urlParams' => $this->urlParams))): ?>
            <div id="pager" class="wrapper">
                <?php echo $paginator; ?>
            </div>
        <?php endif;?>
    
    <?php else:?>
        <div id="captions_header_wrapper"></div>
        <div id="captions"></div>
        <div id="empty">
            <h4><?php echo $this->translate('No Captions have been added to media')?></h4>
            <div><?php echo $this->translate('Begin by uploading a caption file');?></div>
            <div><?php echo $this->translate('(SRT, DFXP formats are supported)');?></div>
        </div>
     <?php endif;?>  

</div>
<?php 