<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

// parse the caption assets
$this->placeholder('captions')->captureStart('SET', 'assets');

if ($this->captions && count($this->captions->objects))
{
    echo $this->partialLoop('partials/captionAsset.phtml', 'captions', $this->captions->objects);
}

$this->placeholder('captions')->captureEnd();

// replace the caption assets
$this->JsonContent(array(
        'target' => '#captions',
        'content' => $this->placeholder('captions')->assets,
        'action' => 'replace'
)
);


// replace the caption assets header
$this->JsonContent(array(
        'target' => '#captions_header_wrapper',
        'content' => $this->partial('partials/captionsHeader.phtml','captions',$this),
        'action' => 'replace'
)
);

// remove the empty message
$script = '$("#empty").remove();';
$this->JsonScript($script);

// replace the pager
$pager = '';
if (!empty($this->paginator)){
    $pager = $this->paginationControl($this->paginator, $this->pagerType, 'partials/galleryPaging.phtml', array('urlParams' => $this->urlParams));
}
$this->JsonContent(array(
        'target' => '#entry_captions #pager',
        'content' => $pager,
        'action' => 'replace'
)
);

// caption assets count
$this->JsonContent(array(
        'target' => '#captions_count',
        'content' => $this->partial('partials/captionsCount.phtml','captions',$this),
        'action' => 'replace'
)
);

// the dialog - if exists
$script = 'reloadKDPCaptions(); $("#dialog").remove();';
$this->JsonScript($script);

// messages - if exists
if (!empty($this->message)){
    $this->JsonFlashMessage($this->message);
}