<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

//	include css and js that will go in the page <head>
$this->headLink()->appendStylesheet($this->baseUrl('build' . BUILD_NUMBER . '/captions/asset/captions.css'));
$this->headScript()->appendFile($this->baseUrl('build'. BUILD_NUMBER . '/captions/asset/captions-thumbRotator.js'));
$this->headScript()->appendFile($this->baseUrl('build'. BUILD_NUMBER . '/captions/asset/captions-search.js'));
