<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

$content = '<div class="uploadCaption" id="upload_caption">'. $this->partial('partials/upload.phtml', 'captions', array('form' => $this->form)).'</div>';
?>

if($('#dialog')) {
    $("body").append('<div id="dialog"></div>');
}
    
<?php
 echo new Zend_Json_Expr("$('#dialog').html(\"".(addcslashes(str_replace(array("\r\n", "\n", "\r"), '', $content), '\"'))."\");") ;
 
 $this->dialogContainer(
        'dialog', $content, array(
            'autoOpen' => true,
            'draggable' => false,
            'modal' => true,
            'width' => 342,
            'min-height' => 256,
            'resizable' => false,
            'title' => $this->translate('Upload caption file'),
            'closeOnEscape' => true,
            'close' => new Zend_Json_Expr('function() {
                $("#dialog").remove(); setConfirmUnload(false);
             }'),
        )
    );
 
 $actions = $this->JQuery()->getOnLoadActions();
 $this->JQuery()->disable();
 foreach ($actions as $action)
 {
     echo $action;
 }
 