<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

if(!$this->confirmed)
{
    
    if($this->allowed)
    {
        $text = $this->translate('Are you sure you want to delete this playlist?'); 
?>
        if($('#dialog')) {
            $("body").append('<div id="dialog"></div>');
        }
        $("#dialog").text('<?php echo $text ?>');

        <?php 
            $this->dialogContainer(
                'dialog',
                $text,
                array(
                    'autoOpen'      => true,
                    'draggable'     => false,
                    'modal'         => true,
                    'resizable'     => false,
                    'title'         => $this->translate('Confirm Delete'),
                    'closeOnEscape' => true,
                    'close' => new Zend_Json_Expr('function() {
                        $("#dialog").remove();
                    }'),
                    'buttons'   => array(
                        $this->translate('Yes') =>  new Zend_Json_Expr('function() {
                            $("body").addClass("cursorwait");
                            $.ajax({
                                url: "'.$this->baseUrl('/playlist/delete/id/'.$this->id.'/confirm/1?format=dialog').'", 
                                success: function(){
                                    document.location.href = "'.$this->baseUrl('/my-playlists').'";
                                }
                            });
                        }'),
                        $this->translate('No') => new Zend_Json_Expr('function() {
                            $(this).dialog(\'close\');
                        }'),
                    ),
             )
            );
    }
    else
    {
        $text = $this->translate('You are not allowed to delete this playlist').'.'; ?>
        if($('#dialog')) {
            $("body").append('<div id="dialog"></div>');
        }
        $("#dialog").text('<?php echo $text ?>');
        

        <?php 
            $this->dialogContainer(
                'dialog',
                $text,
                array(
                    'autoOpen'      => true,
                    'draggable'     => false,
                    'modal'         => true,
                    'resizable'     => false,
                    'title'         => $this->translate('Confirm Delete'),
                    'closeOnEscape' => true,
                    'close' => new Zend_Json_Expr('function() {
                        $("#dialog").remove();
                    }'),
                    'buttons'   => array(
                        $this->translate('Ok') => new Zend_Json_Expr('function() {
                            $(this).dialog(\'close\');
                        }')
                    ),
             )
            );
        
    }

    $actions = $this->JQuery()->getOnLoadActions();

    $this->JQuery()->disable();

    foreach($actions as $action)
    {
        echo $action;
    }
}