<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * @ignore
 */
?>
<dl class="tabs">
    <?php foreach($this->partial()->view->tabs as $tab): ;?>
    <dd class="tab">
        <a href="<?php echo $this->baseUrl('kb/'.$tab);  ?>" class="<?php echo $tab == $this->partial()->view->currentTab ? 'current' : '';?>"><?php echo ucfirst($tab) ?></a>
    </dd>
    <?php endforeach;?>
</dl>