<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/
/**
 * @ignore
 */

?>
<dt><?php echo $this->translate('Global');?></dt>
<?php foreach($this->partial()->view->globalTabs as $tab): ;?>
<dd class="tab">
    <a href="<?php echo $this->partial()->view->url(array('controller'=>'admin','action'=>'config', 'tab' => $tab), null, FALSE);  ?>" class="<?php echo $tab == $this->partial()->view->currentTab ? 'current' : '';?>"><?php echo ucfirst($tab) ?></a>
</dd>
<?php endforeach;?>

<dt><?php echo $this->translate('Modules');?></dt>
<?php foreach($this->partial()->view->moduleTabs as $tab => $enabled):?>
<dd class="tab">
    <?php echo $enabled ? '' : '<del>'; ?>
    <a href="<?php echo $this->partial()->view->url(array('controller'=>'admin','action'=>'config', 'tab' => $tab), null, FALSE);  ?>" class="<?php echo $tab == $this->partial()->view->currentTab ? 'current' : '';?>"><?php echo ucfirst($tab) ?> </a>
    <?php echo $enabled ? '' : '</del>'; ?>
</dd>
<?php endforeach;?>
