<?php

/* 
 *  All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 *  To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
if(count($this->partial()->view->importantItems)):
?>

<div class="importantConfigs">
    <span class="toggler no-icon"><?php echo $this->translate('Important Notice').'! ('.$this->translate('click to open').')';?></span>
    <div style="display: none" >
    <p class="ui-icon ui-icon-info"></p><p class="text flash-message"><?php echo $this->translate('The default values have not changed. We recommended that you modify the values for your configuration.');?></p>
<?php
    foreach($this->partial()->view->importantItems as $item):
        $parts = explode('/', $item);
        if(count($parts) && isset($parts[0]) && isset($parts[1]) && $parts[0] && $parts[1]):
        ?>
    <div>
        <a href="<?php echo $this->baseUrl("admin/config/tab/" .$parts[0] . "#" . $parts[1]);?>" onclick="setTimeout(flashItem, 100,'<?php echo $parts[1];?>');">
            <?php 
               echo ucfirst($parts[0]).' &gt; '.$parts[1];
            ?>
        </a>
    </div>
        <?php
        endif;
    endforeach;
    
?>
    </div>
</div>
<?php
endif;
