<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/
/**
 * @ignore
 */
    $paramsPageNumber = $this->partial()->view->params && isset($this->partial()->view->params['page']) ? $this->partial()->view->params['page'] : null;
    if ($this->pageCount > 1 || $paramsPageNumber > 1): ?>
    <!-- Previous page link -->
    <?php if (isset($this->previous)): ?>
      <a id="prev_page" href="<?php echo $this->MergeUrl(array('page' => $this->previous)); ?>"><?php echo $this->translate('Previous');?></a>
    <?php endif; ?>
    <!-- Numbered page links -->
    <ol>
    <!-- First Page (if not in range ) -->
    <?php if($this->first != $this->firstPageInRange): ?>
        <li>
            <a href="<?php echo $this->MergeUrl(array('page' => $this->first)); ?>">
                <?php echo $this->first; ?>
            </a>
        </li>
        <!-- add leading spacer if there is a gap between first and firstinrange -->
        <?php if($this->firstPageInRange > $this->first + 1): ?>
            <span id="leading_spacer">...</span>        
        <?php endif; ?>
    <?php endif; ?>
    <!-- end first page (if not in range) -->
    <?php foreach ($this->pagesInRange as $page): ?>
      <?php if ($page != $this->current): ?>
        <li>
            <a href="<?php echo $this->MergeUrl(array('page' => $page)); ?>">
                <?php echo $page; ?>
            </a>
        </li>
      <?php else: ?>
        <li class="active">
            <a href="<?php echo $this->MergeUrl(array('page' => $page)); ?>">
                <?php echo $page; ?>
            </a>
        </li>
      <?php endif; ?>
    <?php endforeach; ?>
    <!-- Last Page (if not in range ) -->
    <?php if($this->last != $this->lastPageInRange): ?>
        <?php if($this->lastPageInRange < $this->last -1 ): ?>
            <span id="trailing_spacer">...</span>        
        <?php endif; ?>
        <li>
            <a href="<?php echo $this->MergeUrl(array('page' => $this->last)); ?>">
                <?php echo $this->last; ?>
            </a>
        </li>
        <!-- add leading spacer if there is a gap between last and lastinrange -->
    <?php endif; ?>
    <!-- end Last page (if not in range) -->
    </ol>
    <!-- Next page link -->
    <?php if (isset($this->next)): ?>
      <a id="next_page" href="<?php echo $this->MergeUrl(array('page' => $this->next)); ?>"><?php echo $this->translate('Next');?></a>
    <?php endif; ?>
<?php endif; ?>