<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

?>
<ul id="related"><li><?php echo $this->translate('Loading');?>...</li>
<script language="JavaScript" type="text/javascript">
    $("ul#related").addClass("cursorwait");
    var url = "<?php echo $this->baseUrl('/related/index/related/id/'.$this->entryId.'?format=ajax'); ?>";
    $.getJSON(url, asyncCallback).error( transportError );
    
</script>    
</ul>
