<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

?>
<ul id="related">
    <?php  
        if(count($this->related))
        {
            echo $this->partialLoop( 'partials/relatedItem.phtml', 'related', $this->related); 
        }
        else
        {
            echo $this->translate("No related media for this entry")."...";
        }
    ?>
</ul>