<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

/**
 * @ignore
 * layout file for admin controller. this file usually does not need to be overridden in theme.
 */
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=9" />
        <?php echo $this->headTitle() ?>
        <?php echo $this->partial('partials/layout/headScript.phtml'); ?>
        <?php
        $this->headLink()
                ->appendStylesheet($this->baseUrl('build' . BUILD_NUMBER . '/css/admin.css'));
        echo $this->JQuery()->enable()->uiEnable()
                ->setLocalPath($this->baseUrl('build' . BUILD_NUMBER . '/js/jquery-1.7.1.min.js'))
                ->setUiLocalPath($this->baseUrl('build' . BUILD_NUMBER . '/js/jquery-ui-1.8.16.custom.min.js'))
                ->addStyleSheet($this->baseUrl('build' . BUILD_NUMBER . '/css/kms/jquery-ui-1.8.16.kms.css'));
        $this->headScript()
                ->prependFile($this->baseUrl('build' . BUILD_NUMBER . '/js/global.js'))
                ->appendFile($this->baseUrl('build' . BUILD_NUMBER . '/js/admin.js'));
        ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>

    </head>
    <body>
        <?php if (Kms_Resource_Debug::isEnabled()): ?>
            <!-- debug bar -->
            <?php echo $this->partial('partials/layout/debugBar.phtml'); ?>
            <!-- end debug bar-->
        <?php endif; ?>
        <ul class="main_nav cf">
            <li><a href="<?php echo $this->baseUrl('admin/config'); ?>"><?php echo $this->translate('MANAGE CONFIGURATION'); ?></a></li>
            <li><a href="<?php echo $this->baseUrl('admin/user-list'); ?>"><?php echo $this->translate('MANAGE USERS'); ?></a></li>
            <li><a href="<?php echo $this->baseUrl('/kb'); ?>"><?php echo $this->translate('KNOWLEDGE BASE'); ?></a></li>
            <li><span>&nbsp</span></li>
            <li><a href="<?php echo $this->baseUrl('admin/clear-cache'); ?>" rel="dialog"><?php echo $this->translate('CLEAR THE CACHE'); ?></a></li>
            <?php if (!Kms_Resource_Config::isSaasEnabled()): ?>
                <li><a href="<?php echo $this->baseUrl('admin/enable-debug'); ?>" rel="dialog"><?php echo $this->translate('ENABLE DEBUG MODE'); ?></a></li>
                <li><a href="<?php echo $this->baseUrl('admin/log-viewer'); ?>"><?php echo $this->translate('LOG VIEWER'); ?></a></li>
            <?php endif; ?>
            <li><a href="<?php echo $this->baseUrl('/'); ?>" target="_blank"><?php echo $this->translate('GO TO SITE'); ?></a></li>
            <li><span>&nbsp</span></li>
<!--            <li><a href="<?php echo $this->baseUrl('/admin/unit-tests'); ?>" target="_blank"><?php echo $this->translate('RUN TESTS'); ?></a></li>-->
            <li class="right"><a id="logout-button" href="<?php echo $this->baseUrl('/admin/logout'); ?>"><?php echo $this->translate('LOGOUT'); ?></a></li>
        </ul>
        <div id="kwrap">

            <?php
            if ($this->requirements && count($this->requirements))
            {
                ?>            
                <div id="req-messages" class="clearfix">
                    <?php
                    foreach ($this->requirements as $key => $arr)
                    {
                        ?>
                        <div class="ui-state-error ui-corner-all">
                            <p class="ui-icon ui-icon-info"></p><p class="flash-message"><?php echo $this->translate('Notice'); ?>: <?php echo $arr ?></p>
                        </div>
                        <?php
                    }
                    ?>
                </div>
                <?php
            }
            ?>
            <div id="header">
                <h1>
                    <?php echo $this->pagehead; ?>
                </h1>
            </div>

            <div id="flash-messages">
                <?php
                if (isset($this->messages)) :
                    foreach ($this->messages as $message):
                        ?>
                        <div class="">
                            <p class="ui-icon ui-icon-info"></p><p class="flash-message"><?php echo $message ?></p>
                        </div>
                        <?php
                    endforeach;
                endif;
                ?>
            </div>
            <script>
                setTimeout('$("#flash-messages").fadeOut()', 5000);
            </script>

            <?php echo $this->layout()->content ?>
            <div id="kfooter">
                <br /><?php echo $this->action('version', 'index'); ?>
            </div>
            <div id="errorDialog"></div>

            <?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_ADMIN_FOOTER); ?>

        </div>
    </body>
</html>
