<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

/**
 * @ignore
 */
if(Kms_Resource_Debug::isEnabled())
{
    if(!isset($this->errorHappened) || !$this->errorHappened)
    {
        $this->JsonContent(array(
            'target' => '.debugBar .container',
            'action' => 'append',
            'content' => $this->partial('partials/layout/debugBar.phtml', array('nocontainer' => true, 'title' => 'AJAX REQUEST')), 
            )
        );
    }
}

$response = array();
if( isset($this->jsonContent) 
        && is_array($this->jsonContent) 
                && count($this->jsonContent))
{
    $response['content'] = $this->jsonContent;
}

if( isset($this->jsonFlashMessages)
        && is_array($this->jsonFlashMessages)
                && count($this->jsonFlashMessages))
{
    $messages = '';
    foreach($this->jsonFlashMessages as $flashMessage)
    {
        $messages .= '
        <div class="ui-state-highlight ui-corner-all" style="display: none">
            <p class="ui-icon ui-icon-lightbulb"></p><p class="flash-message" >'.$flashMessage.'</p>
        </div>
        ';
        
    }
    
    $response['content'][] = array(
        'target' => '#flash-messages',
        'content' => $messages,
        'action' => 'replace',
    );
    
    $this->JsonScript('if(typeof(flashTimeout) != \'undefined\'){clearTimeout(flashTimeout)};$("#flash-messages > div").fadeIn(1000);flashTimeout = setTimeout(\'$("#flash-messages > div").fadeOut()\', 6000);');

}


if( isset($this->jsonScript) 
        && is_array($this->jsonScript) 
                && count($this->jsonScript))
{
    $response['script'] = join(';', $this->jsonScript);
}

if(count($response))
{
    echo Zend_Json::encode($response);
}

echo $this->errorContent;