<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

/**
 * @ignore
 */

echo $this->layout()->content; 

if(Kms_Resource_Debug::isEnabled())
{
    if(!isset($this->errorHappened) || !$this->errorHappened)
    {
        $content = $this->partial('partials/layout/debugBar.phtml', array('nocontainer' => true, 'title' => 'DIALOG REQUEST'));
        echo new Zend_Json_Expr("$('.debugBar  .container').append(\"".(str_replace(array("\r\n", "\n", "\r"), '\n', addcslashes($content, '\"')))."\");");
        if(Kms_Resource_Config::getConfiguration('debug', 'highlightJs'))
        {
            echo new Zend_Json_Expr("$('.debugBar').effect(\"highlight\", {color: \"#ffff99\"}, 3000);");
        }
    }
}