<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
/**
 * Main Layout for most normal pages in KMS3
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_POSTSIDENAV
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_PRESIDENAV
 * @viewhook Kms_Resource_Viewhook::CORE_VIEW_HOOK_POSTHEADER
 */
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="<?php echo Kms_Resource_Config::getConfiguration('application', 'language'); ?>">
    <?php echo $this->partial('partials/layout/headSection.phtml'); ?>
    <body class="<?php echo $this->BodyClasses(); ?>">
	<div class="layout_wrapper">
	<?php
            echo $this->partial('partials/layout/requirements.phtml');
	?>
        <?php if(Kms_Resource_Debug::isEnabled()):?>
        <!-- debug bar -->
            <?php echo $this->partial('partials/layout/debugBar.phtml'); ?>
        <!-- end debug bar-->
        <?php endif;?>
	<!-- header partial -->
	<?php echo $this->partial('partials/layout/siteHeader.phtml'); ?>
	<!-- end header -->
	<!-- postHeader Viewhook -->
	<?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_POSTHEADER); ?>
	<!-- end postHeader Viewhook -->
        <!-- flash messages -->
	<div id="flash-messages" class="wrapper">
	    <?php echo $this->partial('partials/layout/flashMessages.phtml', array('messages' => $this->messages)); ?>
	</div>
        <!-- end flash messages -->
	<div id="pageHeading" class="limiter wrapper">
	 <?php if(isset($this->placeholder('pageHeading')->content) && $this->placeholder('pageHeading')->content):?>
		<?php echo $this->placeholder('pageHeading')->content; ?>
	<?php endif?>
	</div>
	
	<div id="page" class="limiter wrapper">
        <?php
        $accessDenied = Zend_Controller_Front::getInstance()->getRequest()->getParam('accessDenied');

        // side navigation
        // do not show in case of access denied
        if (!$accessDenied) 
        {
            // initialize show sidebar 
            $showSideBar = false;
            
            if(isset($this->placeholder('Side_Bar')->content) && $this->placeholder('Side_Bar')->content)
            {
                // show sidebar if content was pushed to the placeholder
                $showSideBar = true;
            }
            
            if($showSideBar):?>
            <div class="sidebar">
                <?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_PRESIDENAV); ?>
                <?php echo $this->placeholder('Side_Bar')->content; ?>
                <?php echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_POSTSIDENAV); ?>
            </div>
            <?php 
                $this->wideLayout = false;
            else:
                $this->wideLayout = true;
            endif;
        }
                
  
	    $contentClass = '';
	    if ($this->presentationView) {
		$contentClass .= 'kpwPlayer';
	    }

	    if ($this->wideLayout) {
		$contentClass .= ' widelayout';
	    }
            
            if(isset($this->contentClass) && $this->contentClass)
            {
                $contentClass .= ' '.$this->contentClass;
            }
            
	    ?>
            <div id="content" class="<?php echo $contentClass ?>" > 
		<?php 
		    echo $this->layout()->content;
		?>
            </div>
	</div>
	</div>
        <?php echo $this->partial('partials/layout/siteFooter.phtml'); ?>
    </body>
</html>
