<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/


echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="<?php echo Kms_Resource_Config::getConfiguration('application','language');?>">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=9" />
  <?php echo $this->headTitle() ?>
  
  <?php echo $this->partial('partials/layout/headScript.phtml');?>
  
  <?php $this->headLink()
          ->appendStylesheet( $this->baseUrl('build'.BUILD_NUMBER.'/css/style.css') ) ;
        // handling of theme stylesheet
        $themeCss = $this->theme('css/theme.css');
        if(file_exists(APPLICATION_PATH.'/../public/'.$themeCss))
        {
                $this->headLink()
                    ->appendStylesheet( $this->baseUrl($themeCss) ) ;
        }
  ?>
  <?php echo $this->JQuery()->enable()->uiEnable()
          ->setLocalPath($this->baseUrl('js/jquery-1.7.1.min.js'))
          ->setUiLocalPath($this->baseUrl('js/jquery-ui-1.8.16.custom.min.js'))
          ->addStyleSheet($this->baseUrl('/css/kms/jquery-ui-1.8.16.kms.css')); 
  ?>
  <?php $this->headScript()
          ->appendFile( $this->baseUrl('build'.BUILD_NUMBER.'/js/global.js'));     
        // handling of theme javascript
        $themeJs = $this->theme('js/theme.js');
        if(file_exists(APPLICATION_PATH.'/../public/'.$themeJs))
        {
            $this->headScript()
                ->appendFile( $this->baseUrl($themeJs));         
        }

  ?>
  <?php echo $this->headLink(); ?>
  <?php echo $this->headScript(); ?>

</head>
<body>
<div id="kwrap" class="loginscreen wrapper limiter">
    <?php 
        if($this->requirements && count($this->requirements))
        {
        ?>            
        <div id="req-messages">
        <?php
            foreach($this->requirements as $key => $arr)
            {
                ?>
                <div class="ui-state-error ui-corner-all">
                    <p class="ui-icon ui-icon-info"></p><p class="flash-message"><?php echo $this->translate('Notice');?>: <?php echo $arr ?></p>
                </div>
                <?php 
            }
            ?>
        </div>
       <?php     
        }
    
    
    ?>
    <div id="content" class="widelayout clearfix" > 
        <div id="flash-messages" class="clearfix">
        <?php 
            if(isset($this->messages) && count($this->messages)>0) 
            {
                foreach($this->messages as $message):?>
                <div class="ui-state-error ui-corner-all">
                    <p class="ui-icon ui-icon-info"></p><p class="flash-message"><?php echo $message;?></p>
                </div>
            <?php endforeach;?>
            <script>
                setTimeout('$("#flash-messages").fadeOut();', 5000);
            </script>
        <?php 
            }
        ?>
        </div>
        

        <?php echo $this->layout()->content ?>
    </div>
    <?php echo $this->partial('partials/layout/siteFooter.phtml'); ?>
</div> 
</body>
</html>
