<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
/**
 * @ignore
 */
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=9" />

	<?php echo $this->headTitle() ?>

        <?php echo $this->partial('partials/layout/headScript.phtml');?>

	<?php
	$this->headLink()
		->appendStylesheet($this->baseUrl('/css/setup.css'));
	?>
	<?php
	echo $this->JQuery()->enable()->uiEnable()
		->setLocalPath($this->baseUrl('js/jquery-1.7.1.min.js'))
		->setUiLocalPath($this->baseUrl('js/jquery-ui-1.8.16.custom.min.js'))
		->addStyleSheet($this->baseUrl('/css/smoothness/jquery-ui-1.8.16.custom.css'));
	?>
	<?php
	$this->headScript()
		->appendFile($this->baseUrl('/js/global.js'));
	?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>

    </head>
    <body>
	<div id="header">
            <?php if(isset($this->customHeaderText) && $this->customHeaderText): ?>
	    <h2><?php echo $this->customHeaderText; ?></h2>
            <?php else: ?>
	    <h2>Kaltura MediaSpace&trade; <?php echo $this->MajorVersion(); ?> - Installation</h2>
            <?php endif; ?>
	    <?php if(isset($this->steps)):?>
	    <ul class="steps">
		<li class="passed first"><?php echo $this->translate('Requirements');?></li>
		<?php foreach($this->steps as $k => $v):
		    $passed = $v == $k < count($this->steps) - 1 && $this->steps[$k+1] ? 'passed' : '';
		    $class = $v == $this->pagehead ? 'active' : $passed;
		    ?>
		    <li class="<?php echo $class;?>"><?php echo $v?></li>
		<?php endforeach;?>
	    </ul>
	    <?php endif;?>
	</div>
	<div id="flash-messages">
	    <?php
	    if (isset($this->messages)) :
		foreach ($this->messages as $message):
		    ?>
		    <div class="ui-state-error ui-corner-all">
			<p class="ui-icon ui-icon-info"></p><p class="flash-message"><?php echo $message ?></p>
		    </div>
		    <?php
		endforeach;
	    endif;
	    ?>
	</div>
	<script>
	    setTimeout('$("#flash-messages").fadeOut()', 5000);
	</script>
	<h1>
	    <?php echo $this->pagehead; ?>
	</h1>
        <div id="kwrap" class="kwrap">
	    <?php echo $this->layout()->content ?>
            <div id="kfooter"></div>
            <div id="errorDialog"></div>
        </div>
    </body>
</html>
