<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

// category captions search results

// parse the search results
$this->placeholder('captions')->captureStart('SET', 'results');

if ($this->captions && !empty($this->captions->objects))
{    
    echo '<ul class="captions" id="kitems">';
    echo $this->partialLoop('partials/globalSearchResult.phtml', 'captions', $this->captions->objects);
    echo '</ul>';
}
else if ($this->keyword)
{
    echo $this->translate('No captions results were found');
}

$this->placeholder('captions')->captureEnd();

// replace the search results
$this->JsonContent(array(
        'target' => '#kgallery',
        'content' => $this->placeholder('captions')->results,
        'action' => 'replace'
)
);

// replace the pager
$pager = $this->paginationControl($this->paginator, $this->pagerType, 'partials/galleryPaging.phtml',array('urlParams' => $this->urlParams));  
$this->JsonContent(array(
        'target' => '#kgallery',
        'content' => '<div id="pager" class="wrapper">' . $pager . '</div>',
        'action' => 'append'
)
);

// replace the media counter
$pagesInfo = $this->paginator->getPages();
if($pagesInfo->lastItemNumber && $pagesInfo->totalItemCount)
{
    $this->JsonContent(array(
            'target' => '#result_counter',
            'content' => '(' . $pagesInfo->firstItemNumber . '-' . $pagesInfo->lastItemNumber . ' '.$this->translate('of').' ' . $pagesInfo->totalItemCount . ' '.$this->translate('media') . ')',
            'action' => 'replace'
        )
    );
}
else
{
    $this->JsonContent(array(
            'target' => '#result_counter',
            'content' => '',
            'action' => 'replace'
        )
    );
}

// activate the caption thumb rotator js
$this->JsonScript("KalturaCaptionsThumbRotator.init('vidsec');");
