<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
?>

<script>
   KalturaCaptionsThumbRotator.init('vidsec');
   //KApps.debug = true;
</script>

<?php if (!empty($this->inTime)): ?>
<script>
    // this is a captions search result entry - activate the caption search js
    var entry_id = "<?php echo $this->entryId?>";
    var out_time = <?php echo $this->outTime?>;
    var in_time = <?php echo $this->inTime?>;
    var label = "<?php echo $this->label?>";
    var language = "<?php echo $this->language?>";
    KApps.CaptionsSearch.vars.changedMedia = true;
    KApps.CaptionsSearch.searchResultActivate(entry_id,out_time,in_time,label,language);
</script>
<?php endif;?>

<div id="captions_tab" onshow="$('#search_captions').focus()">
<div class="fleft">
<?php 
$keyword = false;
$defaultText = $this->translate('Search in this video');
if ($this->params['keyword'])
{
    $keyword = $this->params['keyword'];
}

$form = new Captions_Form_KeywordSearch(array('keyword' =>$keyword, 'defaultKeyword' => $defaultText));

// take advantage of the model interface that modified the default text
if (!empty($form->_defaultKeyword)){
    $defaultText = $form->_defaultKeyword;
}

$form->setAction($this->baseUrl('/captions/search/entry/entryId/' . $this->entryId));
$form->setAttrib('id', 'search_within');
$form->setAttrib('ajax', '1');

echo $form->render();

?>

<div id="ktype">
    <span><?php echo $this->translate('View'); ?>:</span>
    <?php
    $delimiter = '-----------------------------';
    $select = new Zend_Form_Element_Select(
                    'show_type',
                    array(
                        'multiOptions' => array(
                            '' => $this->translate('All Languages'),
                            $delimiter,
                        ),
                        'disable' => array('0', '1'),
                        'onchange' => '
                            $("#search_within #lang").val($(this).val());  
                            if($("#search_within #search_within_captions").val() != "' . $defaultText .'"){    
                                $("#search_within").submit();
                            }
                            ',
                    )
    );

    // add all the entry languages as options
    foreach ($this->languages as $language) {
        $select->addMultiOption($language, $this->translate($language));
    }

    $select->setDecorators(array('ViewHelper'));
    echo $select;
    ?>
</div>

<div id="captions_search_Results"></div>
<div id="pager" class="fleft"></div>
</div>
</div>


<?php /* Javascript for the live Search functionality */ ?>
<script>
    var defaultKeyword = "<?php echo addcslashes($defaultText, '\"');?>";
    var searchTimeout;
    var searchVal = $('#search_within_captions').val();
    $('#search_within_captions').keyup(function(){
        if($(this).val() == '' || $(this).val() == defaultKeyword) {
            $('#reset_search_within_captions').hide();
            $("#search_within_captions").removeClass("keyword");
        }
        else {
            $('#reset_search_within_captions').show();
            $("#search_within_captions").addClass("keyword");
        }
        
        if(searchVal != $(this).val()) {
            searchVal = $(this).val();
            clearTimeout(searchTimeout);
            searchTimeout=setTimeout(function(){
                $("#search_within").submit();
            }, 800);
        }
    });
</script>
<?php /* end livesearch */ 