<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

// set the rel property for caption search results
$this->rel = 'async';

// parse the search results
$this->placeholder('captions')->captureStart('SET', 'results');

if ($this->captions && !empty($this->captions->objects))
{    
    $caption = array_pop($this->captions->objects);

    echo '<div class="zebra-striped captions"><ul id="kitems" class="captions">';
    echo $this->partialLoop('partials/entrySearchResult.phtml', 'captions', $caption['assetItems']);
    echo "</ul></div>";
}
else if ($this->keyword)
{
    echo $this->translate('No captions results were found');
}

$this->placeholder('captions')->captureEnd();

// replace the search results
$this->JsonContent(array(
        'target' => '#captions_search_Results',
        'content' => $this->placeholder('captions')->results,
        'action' => 'replace'
)
);

// replace the pager
$pager = '';
if (!empty($this->paginator)){
    $pager = $this->paginationControl($this->paginator, $this->pagerType, 'partials/galleryPaging.phtml',array('urlParams' => $this->urlParams));  
}
$this->JsonContent(array(
        'target' => '#captions_tab #pager',
        'content' => $pager,
        'action' => 'replace'
)
);

// activate the caption search js
$script = '
    KApps.CaptionsSearch.vars.currentEntryId = "' . $this->entryId . '";
    $("#captions_search_Results li").click(function() {
		KApps.log("caption ajax results clicked");
		KApps.CaptionsSearch.searchResultClick(this);
	});';
$this->JsonScript($script);