<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/
/**
 * @ignore
 */

    $this->JsonContent(
        array(
            'target' => '#'.$this->target,
            'content' => $this->ConfigFields( array($this->field['name'] => $this->field), true),
            'action' => 'before'
        )
    );
    
    $this->JsonScript('enableRemoveLinks()');
    $this->JsonScript('updateDependencies($("input,select,textarea"))');
    $actions = $this->JQuery()->getOnLoadActions();

//    $this->JQuery()->disable();

    foreach($actions as $action)
    {
        $this->JsonScript($action);
    }
    
    