<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/
/**
 * @ignore
 */
// support for CTRL+S saving 
$this->headScript()->appendScript('
    $(window).keypress(function(event) {
        if (!(event.which == 115 && event.ctrlKey) && !(event.which == 19)) return true;
        $("form#config").submit();
        event.preventDefault();
        return false;
    });
');


if($this->cannotWrite) : ?>
<div>
    <div class="ui-state-error ui-corner-all">
        <p style="float: left;" class="ui-icon ui-icon-info"></p>
        <p class="flash-message">
            <?php echo $this->cannotWrite ?>
        </p>
    </div>
</div>
<?php endif; ?>
<div id="search">
    <?php echo $this->partial('partials/admin/configAutoComplete.phtml'); ?>
</div>
<dl class="tabs">
    <dt><?php echo $this->translate('Developer Tools');?></dt>
    <?php if(APPLICATION_ENV != 'production'): ?>
        <dd><a href="<?php echo $this->baseUrl('/admin/export-config');?>"><?php echo $this->translate('Export configuration to a file');?></a></dd>
        <dd><a href="<?php echo $this->baseUrl('/admin/import-config');?>"><?php echo $this->translate('Import configuration from a file');?></a></dd>
        <dd><a rel="dialog" data-timeout="90" href="<?php echo $this->baseUrl('/admin/deploy/type/uiconfs');?>"><?php echo $this->translate('Create uiConfs for Widgets');?></a></dd>
        <dd><a rel="dialog" data-timeout="90" href="<?php echo $this->baseUrl('/admin/deploy/type/customdata');?>"><?php echo $this->translate('Create Custom Metadata profiles');?></a></dd>
    <?php else:?>
        <dd><a rel="dialog" href="<?php echo $this->baseUrl('/kb/developer-tools');?>"><?php echo $this->translate('How to enable "Developer Tools"');?>?</a></dd>
    <?php endif;?>
    <?php echo $this->partial('partials/admin/configSideNav.phtml'); ?>
</dl>

<div class="tabContent">
    <?php echo $this->partial('partials/admin/configImportantItems.phtml', $this->importantItems); ?>
    <form id="config" method="POST" ajax="dialog" action="<?php echo $this->url(array('controller'=>'admin','action'=>'save-config', 'tab' => $this->currentTab), null, FALSE);  ?>">
    <fieldset class="root">
        <legend><?php echo ucfirst($this->currentTab) ?></legend>        
        <?php 
            echo $this->InfoFields($this->info);
            echo $this->ConfigFields($this->configs);
        ?>
        <input type="submit" value="<?php echo $this->translate('Save')?>" class="save" />
    </fieldset>
    </form>
    
</div>
<?php if($this->cannotWrite) : ?>
<script>
    $('input.save').attr('disabled', 'disabled');
</script>
<?php endif; ?>