<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/
/**
 * @ignore
 */

    $this->JsonContent(
        array(
            'target' => '#user-password,#user-password2',
            'content' => $this->PasswordGenerator(),
            'action' => 'value'
        )
    );