<?php

/* 
 *  All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 *  To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

?>
    <?php
    if ($this->uniqueId):
        if (count($this->lines)):
            ?>
            <?php
            foreach ($this->lines as $line):
                    echo $line;
            endforeach;
        endif;
    else:
        ?>
        <span><?php echo $this->translate('The unique execution id, is a mandatory parameter.'); ?></span>
    <?php
    endif;
    ?>


