<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/
/**
 * @ignore
 */
 
    // capture script
    $this->placeholder('script')->captureStart('SET', 'script'); 
?>

if($('#dialog')) {
$("body").append('<div id="dialog"></div>');
}
<?php echo new Zend_Json_Expr("$('#dialog').html('" . str_replace(array("\r\n", "\n", "\r"), '', addslashes($this->dialogText)) . "');"); ?>

<?php
if ($this->success)
{
    $buttons = array(
        'OK' => new Zend_Json_Expr('function() {
                    setConfirmUnload(0); 
                    $("body").addClass("cursorwait");
                    document.location.reload();
//                    $(this).dialog(\'close\');
                }'),
    );
} else
{
    $buttons = array(
        'Close' => new Zend_Json_Expr('function() {
                $(this).dialog(\'close\');
            }'),
    );
}


$this->dialogContainer(
        'dialog', $this->headerText, array(
        'width' => '550px',
//        'height' => '500px',
        'autoOpen' => true,
        'draggable' => false,
        'modal' => true,
        'resizable' => false,
        'title' => $this->headerText,
        'closeOnEscape' => true,
        'close' => new Zend_Json_Expr('function() {
                    $("#dialog").remove();
                }'),
        'buttons' => $buttons,
    )
);

$actions = $this->JQuery()->getOnLoadActions();

$this->JQuery()->disable();

foreach ($actions as $action)
{
    echo $action;
}

    // end script capture
    $this->placeholder('script')->captureEnd(); 
    $this->JsonContent(
        array(
            'target' => 'div.tabs',
            'content' => $this->partial('partials/admin/configSideNav.phtml'),
            'action' => 'replace'
        )
    );
    $this->JsonScript($this->placeholder('script')->script);
