<?php

/* 
 *  All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 *  To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
/**
 * @ignore
 */

?>
<p><?php echo $this->translate('Unit tests create test categories and content');?>.
<?php echo $this->translate('Please keep in mind that some of the test content may remain in your account after the tests are complete');?>.</p>
<iframe id="tests" src="<?php echo $this->baseUrl($this->testUrl);?>"></iframe>