<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/
/**
 * @ignore
 */

if($this->showDialog): ?>

    if($('#dialog')) {
        $("body").append('<div id="dialog"></div>');
    }
    <?php echo new Zend_Json_Expr("$('#dialog').html('".$this->dialogText."');"); ?>

    <?php
        $this->dialogContainer(
            'dialog',
            $this->headerText,
            array(
                'width'         => '350px',
                'autoOpen'      => true,
                'draggable'     => false,
                'modal'         => true,
                'resizable'     => false,
                'title'         => $this->translate('Delete User'),
                'closeOnEscape' => true,
                'close' => new Zend_Json_Expr('function() {
                    $("#dialog").remove();
                }'),
                'buttons'   => array(
                    $this->translate('Yes') =>  new Zend_Json_Expr('function() {
                        $("body").addClass("cursorwait");
                        $.ajax({
                            url: "'.$this->baseUrl('/admin/user-delete/id/'.$this->userIdArray.'/confirm/1?format=ajax').'", 
                            success: function(){
                                document.location.reload();
                            }
                        });
                    }'),
                    $this->translate('No') => new Zend_Json_Expr('function() {
                        $(this).dialog(\'close\');
                    }'),
                ),
         )
        );


        $actions = $this->JQuery()->getOnLoadActions();

        $this->JQuery()->disable();

        foreach($actions as $action)
        {
            echo $action;
        }
endif;