<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/
/**
 * @ignore
 */

if($this->formValid)
{
    if($this->redirectToFirstPage)
    {
         $this->JsonScript('$(this).dialog(\'close\');document.location.href = "'.$this->baseUrl('/admin/user-list/').'"');
    }
    else
    {
        $this->JsonScript('$(this).dialog(\'close\');document.location.reload();');
    }
}
else
{
    $this->JsonContent(array(
            'target' => '#userForm',
            'content' => $this->form->render(),
            'action' => 'replace'
        )
    );
    
}
