<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
/**
 * @ignore
 */
?>
<div class="clearfix usersearch" id="search">
    <?php echo $this->partial('partials/admin/userListFilterBar.phtml', array('filterForm' => $this->filterForm)); ?>
</div>
<!--start user management -->
<div class="ui-grid userlist">

    <div class="user_actions">
        <button id="add-new" class="edit-button" href="<?php echo $this->baseUrl('/admin/user-add'); ?>" rel="dialog"><?php echo $this->translate('ADD NEW USER'); ?></button>
        <button id="delete-checked" class="delete-button" href="<?php echo $this->baseUrl('/admin/user-delete'); ?>" rel="dialog" onclick="return updateChecked($(this));"><?php echo $this->translate('DELETE CHECKED'); ?></button>
        <button id="submit-csv" class="submit-csv-button" href="<?php echo $this->baseUrl('/admin/user-bulkupload'); ?>" rel="dialog"><?php echo $this->translate('SUBMIT CSV'); ?></button>
    </div>
    <div class="paginator">
        <?php
        if ($this->paginator) {
            echo $this->paginationControl($this->paginator, 'Elastic', 'partials/admin/userAdminPaging.phtml');
        }
        ?>
    </div>
    <table class="ui-grid-content ui-widget-content" cellspacing="0">
        <thead>
            <tr>
                <th class="ui-state-default short"><input class="all-sel" type="checkbox" onclick="if($(this).attr('checked') == 'checked'){$('input[type=checkbox]').attr('checked', 'checked')}else{$('input[type=checkbox]').removeAttr('checked')};updateChecked($('#delete-checked'))" />
                <th class="ui-state-default"><?php echo $this->translate('User ID'); ?></th>
                <th class="ui-state-default"><?php echo $this->translate('First Name'); ?></th>
                <th class="ui-state-default"><?php echo $this->translate('Last Name'); ?></th>
                <?php if ($this->managePasswords): ?>
                    <th class="ui-state-default"><?php echo $this->translate('Password'); ?></th>
                <?php endif; ?>
                <th class="ui-state-default"><?php echo $this->translate('Role'); ?></th>
                <th class="ui-state-default long"><?php echo $this->translate('Email'); ?></th>
                <th class="ui-state-default long"><?php echo $this->translate('Extra data'); ?></th>
                <th class="ui-state-default action"><?php echo $this->translate('Actions'); ?></th>
            </tr>
        </thead>
        <?php if (count($this->users) == 0): ?>
            <tr>
                <td class="ui-widget-content" colspan="<?php echo ($this->managePasswords) ? 9 : 8; ?>"><?php echo $this->translate('No data found'); ?></td>
            </tr>
        </table>
        <?php
    else:
        foreach ($this->users as $user):
            ?>
            <tr class="<?php echo $this->cycle(array('odd', 'even'))->next(); ?>">
                <td class="ui-widget-content short"><input class="user-sel"type="checkbox" value="<?php echo $user['id']; ?>"/></td>
                <td class="ui-widget-content"><?php echo $user['id']; ?></td>
                <td class="ui-widget-content"><?php echo $user['userObject']->firstName; ?></td>
                <td class="ui-widget-content"><?php echo $user['userObject']->lastName; ?></td>
                <?php if ($this->managePasswords): ?>
                    <td class="ui-widget-content"><?php echo $user['password']; ?></td>
                <?php endif; ?>
                <td class="ui-widget-content">
                    <?php echo $user['role']; ?>
                    <?php if ($user['role'] && !$user['roleExists']): ?>
                        <img src="<?php echo $this->baseUrl('img/admin/warn.png'); ?>" alt="" title="<?php echo $this->translate('Role does not exist in config file: user will not be able to log in.'); ?>"/>
                    <?php endif; ?>
                </td>
                <td class="ui-widget-content">
                    <a href="mailto:<?php echo $user['email']; ?>"><?php echo $user['email']; ?></a>
                </td>
                <td class="ui-widget-content" title="<?php echo $user['extradata']; ?>"><?php echo $user['extradata']; ?></td>
                <td class="ui-widget-content action">
                    <button class="edit-button" href="<?php echo $this->baseUrl('/admin/user-edit/id/' . $user['id']); ?>" rel="dialog"><?php echo $this->translate('Edit User'); ?></button>&nbsp;
                    <button class="delete-button" href="<?php echo $this->baseUrl('/admin/user-delete/id/' . $user['id']); ?>" rel="dialog"><?php echo $this->translate('Delete'); ?></button>
                    <input type="hidden" name="userId" value="<?php echo $user['id']; ?>" />
                </td>
            </tr>
            <?php
        endforeach;
        ?>
    </table>
    <div class="paginator">
        <?php
        echo $this->paginationControl($this->paginator, 'Elastic', 'partials/admin/userAdminPaging.phtml');
        ?>
    </div>
    </div>

<?php endif; ?>
<script>
    //$('button').button();
    $("table").click(function(e) {
        if(e.target.tagName == "IMG") {
            alert(e.target.getAttribute("title"));
        }
    });
</script>

