<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
/**
 * @ignore
 */
echo "after save - not used?";
exit();
?>
if($('#dialog')) {
    $("body").append('<div id="dialog"></div>');
}
<?php

echo new Zend_Json_Expr("$('#dialog').html(\"".(addcslashes(str_replace(array("\r\n", "\n", "\r"), '', $this->form), '\"'))."\");")

        ?>

<?php
    $this->dialogContainer(
        'dialog',
        $this->headerText,
        array(
            'width'         => '350px',
            'autoOpen'      => true,
            'draggable'     => false,
            'modal'         => true,
            'resizable'     => false,
            'title'         => $this->headerText,
            'closeOnEscape' => true,
            'close' => new Zend_Json_Expr('function() {
                $("#dialog").remove();
            }'),
            'buttons'   => array(
                $this->translate('Cancel') => new Zend_Json_Expr('function() {
                    $(this).dialog(\'close\');
                }')
            ),
     )
    );


    $actions = $this->JQuery()->getOnLoadActions();

    $this->JQuery()->disable();

    foreach($actions as $action)
    {
        echo $action;
    }
?>
