<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */
?>
<?php 
if(isset($this->showSettings)):
?>
<a id="channelSettings" href="<?php echo $this->url(array('channelname' => Kms_View_Helper_String::removeSpecialChars($this->channelName), 'channelid' => $this->channelId), 'channelsedit');?>">
	<?php echo $this->translate('Settings');?>
</a>
<?php
endif;

if(isset($this->showButtons)) {
    echo $this->ViewHook(Kms_Resource_Viewhook::CORE_VIEW_HOOK_GALLERY_BUTTONS);
} 