<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/

echo $this->headStyle($this->partial('partials/screencapture.css', 'screencapture'));
?>
<li>
    <a id="launch_screen_capture" class="btn screencapture" href="<?php echo $this->baseUrl('/screencapture/index/add'); ?>" ><em></em><span><?php echo $this->translate('Screen Capture'); ?></span></a>
</li>
