<?php
/*
 * All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 * To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
*/
$form = '';
// error box
if(isset($this->formValid) && false === $this->formValid)
{
    if(isset($this->duplicate) && $this->duplicate)
    {
        $form .= '<div class="errorbox">'.$this->translate('You already added this video in the past. Please choose another.').'</div>';
    }
    else
    {
        $form .= '<div class="errorbox">'.$this->translate('Please make sure that the url is valid, and the checkbox is selected').'</div>';
    }
    // the form itself
    $form .= $this->form->render();
    
    $this->JsonContent(
        array(
            'target' => '#uploadbox'.$this->uploadBoxId.' #entry_details',
            'content' => $form,
            'action' => 'replace'
        )
    );  

}
else
{
    $this->JsonContent(
        array(
            'target' => '#uploadbox'.$this->uploadBoxId.' #entry_details',
            'content' => $form,
            'action' => 'delete'
        )
    );  
    
    $this->JsonContent(
        array( // add the "done" div with the textarea and the link to the new entry inside
            'target' => '#uploadbox'.$this->uploadBoxId.' .entry_status',
            'content' => '
                <div class="done">
                    <div>
                        '.$this->translate('Your Screen Capture video will be imported and converted.').'
                        <a href="' .$this->EntryLink($this->entryId, $this->entryName) .'" target="_blank">' . $this->translate('Go to media page') . '</a>
                    </div>
                </div>',
            'action' => 'replace'
        )
    );
    
    $this->JsonContent(
        array( // add the "done" div with the textarea and the link to the new entry inside
            'target' => '#uploadbox'.$this->uploadBoxId.' .entry_status',
            'content' => '
                <div class="done">
                    <div>'.$this->translate('Link to this media').'</div>
                    '.$this->formText('entryLink',$this->serverUrl().$this->EntryLink($this->entryId, $this->entryName), array('onclick' => "$(this).focus().select();")).'
                </div>',
            'action' => 'append'
        )
    );
    
}




