<?php

/*
 *  All Code Confidential and Proprietary, Copyright ©2011 Kaltura, Inc.
 *  To learn more: http://corp.kaltura.com/Products/Video-Applications/Kaltura-Mediaspace-Video-Portal
 */

$this->JsonContent(
        array(
            'target' => '#uploadbox'.($this->uploadBoxId).' .entry_status',
            'content' => '
                <div id="entry_details" class="entry_details" style="display: block">' . $this->form->render() . '</div>',
            'action' => 'replace'
        )
);

